### ISSUE TITLE
** Error in `qalculate-gtk': corrupted double-linked list: 0x0000000001f5e240 ***

### ISSUE THREAD

**Issue by Claws81** [Qalculate/qalculate-gtk#1]
Hi.
Thanks for updating my favorite calculator :)

However, after compiling and installing on Opensuse 42.1, qalculate-gtk produces the error in the headline here and halts.

I have attached a 'strace' of launching qalculate-gtk (not the full strace thought). I hope this helps.
Let me know if I can provide anything else.

/C

`mprotect(0x7f0f8a123000, 4096, PROT_READ) = 0
lseek(10, 0, SEEK_SET)                  = 0
read(10, "\211PNG\r\n\32\n\0\0\0\rIHDR\0\0\0000\0\0\0000\10\6\0\0\0W\2\371"..., 4096) = 3874
futex(0x7f0f937924a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f0f937924a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x7f0f937924a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
close(10)                               = 0
munmap(0x7f0f95d0a000, 4096)            = 0
open("/usr/share/locale-langpack/en_US.UTF-8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en_US.UTF-8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US.utf8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en_US.utf8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en_US/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en_US/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.UTF-8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en.UTF-8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en.utf8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en.utf8/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-langpack/en/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale-bundle/en/LC_MESSAGES/libqalculate.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/dev/tty", O_RDWR|O_NOCTTY|O_NONBLOCK) = 10
writev(10, [{"*** Error in`", 14}, {"qalculate-gtk", 13}, {"': ", 3}, {"corrupted double-linked list", 28}, {": 0x", 4}, {"0000000001fca570", 16}, {" **_\n", 5}], 7**_ Error in `qalculate-gtk': corrupted double-linked list: 0x0000000001fca570 ***
) = 83
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f0f95d0a000
futex(0x7f0f91c9b620, FUTEX_WAIT_PRIVATE, 2, NULL
`

**Comment by hanna-kn** [comment]
Unfortunately the strace output is not very helpful. 

Do you get the same error if you run `qalc`?

It would be helpful if you could share the location (to see if it has been moved by the program from ~/.qalculate to ~/.config) and contents of your configuration file (qalculate-gtk.cfg), as well as a list of files in the local qalculate directory (~/.qalculate or ~/.local/share/qalculate).

**Comment by Claws81** [comment]
Hi.

OpenSUSE Leap 42.1 installs libqalculate (5.0.0) aas a dependency of plasma5 desktop. This is installed in /usr/lib64/ 
My compiled version (5.0.0) is located in /usr/local/lib64 
Just FYI if it creates a conflict.

Re. your questions:

Running qalc gives:
qalc: symbol lookup error: qalc: undefined symbol: _Z14getOldLocalDirv

I don't have a qalculate-gtk.cfg file anywhere or folder in .config or other.
