### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by WeirdOddWodd** [Qalculate/qalculate-gtk#101]
Hanna, it would be great if there was a mobile version of Qalculate!. I have an Android-run smartphone. But, Qalculate! is nowhere to be found. I would prefer it to include at least the unibase function. Thus far, that is the only way that I know of to convert basic (but, far from all) text strings to decimal without having to input the full expression. This is handy when converting one of my favorite names. It is a 10-letter name containing 4 of the same letter. It is, of course, useful for very long strings (example: a page in a book). You might already be working on mobile versions.

**Comment by hanna-kn** [comment]
See issue #24

**Comment by WeirdOddWodd** [comment]
Thank you for the information. It is definitely useful. I wish you the best on the rewrite of the user interface. That will likely take much time to complete. Function implementation will probably go quicker.

**Comment by WeirdOddWodd** [comment]
Hanna, your Unibase function is great! Here might be your next challenge: a
base finder

In an example case, this is what I would like to do. Using a given text
string and a target integer length (number of digits in the integer), find
the highest base to which the string's characters must be raised to maintain
the target length. For example: Using the unibase function, the decimal
conversion for the name Daisy (my favorite) is found to contain 26 digits
for the final time when converted from base 1,101,216. It would be great to
do that in reverse. In this case, my input might look like this: Daisy (a
text string); 27 (number of target digits plus 1). Upon evaluating the
expression, the result 1,101,217 should be returned. (Logically, the base
just prior to this should yield the desired result.) In my primary
practical-application case, I want to take a longer name (of 10 letters) and
find the highest base to which its letters must be raised to obtain a number
containing 6,018 digits. It is a value between 22,221 and 22,222. The exact
value is what I want to find without manually changing each of the 669
digits. It might be an algorithm similar to that used in unibase, except
with logarithms.

**Comment by hanna-kn** [comment]
A simple equation should suffice:
e.g. `log10(unibase(Daisy, x)) = 26` returns `x ≈ 1 101 216.3`

**Comment by hanna-kn** [comment]
I suggest that you disable interval arithmetic until I've improved the appearance of warning messages with high precision.
