### ISSUE TITLE
Feature request: quake mode

### ISSUE THREAD

**Issue by BYT3M3** [Qalculate/qalculate-gtk#102]
Dear maintainer

I'm using the gnome extension quake-mode to call up qalculate with a hotkey, but it's not very stable. I would love to see the quake mode feature added to qalculate, because it is my main daily driver calculator.

**Comment by hanna-kn** [comment]
Does "quake mode" include anything more than a hotkey, a specific window placement, and animation?

Standard gnome hotkeys should work without issue for running qalculate-gtk, and will be default also work on minimized window. wmctrl, or similar, can be used for the initial placement of the window.

**Comment by BYT3M3** [comment]
I fixed it by using the quake-mode gnome extension. This worked reasonably well for me for quite some time, until yesterday. Everytime I try to open qalculate-gtk using the hotkey I set up using the quake-mode extension, all I get is a stuttery mess.

**Comment by BYT3M3** [comment]
Okay, I reinstalled both the extension and Qalculate (using snap) and it magically started working again. I do get some weird error messages in my logs like:

Usage of object.actor is deprecated for WorkspaceSwitcherPopup
get@resource:///org/gnome/shell/ui/environment.js:249:29
onScrollEvent@/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/docking.js:1268:21

Which is probably caused by the Quake-mode extension which is probably out of date.
