### ISSUE TITLE
insert typed text from history

### ISSUE THREAD

**Issue by ngrcld** [Qalculate/qalculate-gtk#105]
I think it would be useful an option to insert typed text from history.
An example: if I type "12:43-8:14 to time", the history shows also "= (763 ∕ 60) − (494 ∕ 60)". If I need to edit the expression loading it from history, only the "expanded" text gets inserted: I have no option to edit the original typed text.

**Comment by hanna-kn** [comment]
The behaviour was also inconsistent.  The typed expression will now be always be used (unless new insert parsed text menu item is used).
