### ISSUE TITLE
Bring back launch of multiple instance by default

### ISSUE THREAD

**Issue by samueljohnson** [Qalculate/qalculate-gtk#11]
Hi, Long time user of Qalculate here.

A recent change in Qalculate makes launching only a single instance of the GUI by default.

However, in my usage, I find that some times there is a need to launch multiple Qalculate instances.

Though there is a switch to bring back the old behaviour, Qalculate is almost always launched using 'Application Shortcuts', 'Alt+F2', 'Application Menus', etc. making it difficult to provide that additional switch.

Can you please switch back the DEFAULT behaviour as it was earlier and make the additional switch necessary only in case a single instance is required.

Thanks.

**Comment by hanna-kn** [comment]
I have now added an option to use multiple instances by default.

I do not currently want to change the default behaviour, but it might be a good idea to ask the user for the desired behaviour when first qalculate-gtk is run with an instance already open.

**Comment by samueljohnson** [comment]
Adding that as a preference option is a good idea.

Thanks for listening.
