### ISSUE TITLE
Starting Q! from calc.exe-debugger crashes Q!

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-gtk#111]
I tried to "replace" calc.exe with Q!:
When doing this https://superuser.com/a/1393866/455184 and try to "map" it to "c:\MyProgramme\qalculate\qalculate.exe", it starts but then, after a second or two, Q! crashes.

```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\Calc.exe]     
"Debugger"="c:\\MyProgramme\\qalculate\\qalculate.exe"
```

BUT: If I start Q! via batch file and add that to the registry, Q! starts and does not crash.
I just don't like this workaround ...

```
echo off
echo Hang on ... I'm starting Qalculate!
start "" "c:\MyProgramme\qalculate\qalculate.exe"
```

Any chance to debug the crash?

**Comment by hanna-kn** [comment]
If I understand this correctly, the registry change will cause `c:\\MyProgramme\\qalculate\\qalculate.exe Calc.exe` to run on execution of Calc.exe. 

Qalculate! calculates command line arguments when run. The expression "Calc.exe" would thus be calculated. There is however a bug (#107) which results in a segfault when providing an expression on the command line.

**Comment by foreachthing** [comment]
Ah, I understand! Well, as long as there is a workaround I'm fine with that.
So, if #107 is fixed, then you can close here...
