### ISSUE TITLE
 compile/install , should ldconfig to update libs 

### ISSUE THREAD

**Issue by lachlanA** [Qalculate/qalculate-gtk#113]
running ldconfig from the install script maybe a good idea,

**Comment by hanna-kn** [comment]
ldconfig -n LIBDIR is run but does not build cache.

ldconfig normally requires root privileges, and might thus not be appropriate for the installation process in some cases.

I will add additional information about the possible need to run ldconfig as root after installation to the README(.md) file of libqalculate.

**Comment by lachlanA** [comment]
Thanks,   a note about running ldconfig, as root will be good :)

Lachlan
