### ISSUE TITLE
stumped

### ISSUE THREAD

**Issue by quiricada** [Qalculate/qalculate-gtk#116]
hi,
in RPN mode, is there a change-sign (CHS) and a put the top stack value back to the display like hp calculator? been using work-around when i needed these but it's been bugging me ever since, like a little pebble inside the shoe :)
thanks

**Comment by hanna-kn** [comment]
I never use RPN myself and therefore need others to tell me what is missing.

I've now added a negate button to the RPN stack buttons, negate action on right-click of subtract keypad button, and a Ctrl+minus keyboard shortcut.

I do not quite understand what "put the top stack value back to the display" would do. The top value is always displayed. Do you mean recalling the previous (before the last operation) top stack value (as LAST _x_, which has now also been implemented)?.

**Comment by quiricada** [comment]
i've been using "ANS" as LAST x. hp have a R down-arrow for rolling the stack on the display.

on reflection, the negate button and the LAST x will hit the spot. the qalculate stack is way more flexible than the hp with it's single line display, so it's time for me to take my blinkers off and shed the hp way :)

thanks much.

**Comment by quiricada** [comment]
since it's been un-stumped, idk what the procedure is for closing this comment. pls close if you are ok with it. thanks.
