### ISSUE TITLE
Bijective Hexavigesimal Converter

### ISSUE THREAD

**Issue by WeirdOddWodd** [Qalculate/qalculate-gtk#117]
Here is a suggestion for you: a bijective hexavigesimal converter. Also, some of its output is a bit odd. For example: Entering pizza and having it converted to decimal yields 7,488,053. But, entering 7,488,053 (excluding commas) yields PJAA (288,003). You can find one [here](https://jsfiddle.net/LeoJH/yct99wtb/). But, it loses accuracy near 12 letters. I would like to verify that I correctly typed the digits for a recently performed conversion. But, it is of a string containing 39 letters. Thus far, the JSFiddle page is all that I have found for bijective hexavigesimal conversions. There are plenty of hexavigesimal converters. But, they all use the standard 0-P system. But, the JSFiddle page allows for input in “English.” It would be great to use Qalculate! to perform these conversions (such as entering, for example, "pizza" and having an output of 7,488,053 and doing the reverse, entering 7,488,053 and having the output of pizza or PIZZA rather than pjaa or PJAA). For spreadsheets, =COLUMN(PJAA1) would likely return the value 288,003, not 7,488,053. That, my friend, would be =COLUMN(PIZZA1). 😉

**Comment by hanna-kn** [comment]
A function ("bijective") for conversion from and to bijective base-26 has now been added.

**Comment by WeirdOddWodd** [comment]
Nice
It makes it difficult for your calculator to be the “one-stop-shop” “go-to” calculator if it doesn’t do “everything,” right? 🤣

**Comment by WeirdOddWodd** [comment]
Happy Halloween, Hanna!

**Comment by WeirdOddWodd** [comment]
I tested the bijective function. It worked flawlessly in my tests of both directions. Incidentally, I found your first name to yield a prime number. Sadly, my favorite name (Daisy) does not yield one of those in base form. Its plural and possessive forms (Daisy’s, excluding the apostrophe [Note] and daisies, respectively), however, do. Thank you for another great function to make my life easier. ☺

Things to look at, though:

1.	I have found that Shift  + (or Caps Lock followed by) A inserts what looks to be an angle symbol. Pressing this combination again with no other keystrokes in between cases Qalculate! to crash.
2.	Sometimes I have to reset the precision level. For example: I have the precision set to 306 significant digits. I perform a calculation of 264. The displayed result is 18,446,744,073,709,551,616. But, on my next use, the same expression returns the result in scientific notation. For me, scientific notation feels wasteful on an arbitrary-precision calculator. I prefer arbitrary precision to avoid scientific notation.
3.	I am guessing that the slashes displayed for the division sign are supposed to be 2 distinct characters of any of the following:

a.	The standard slash: / (character 47 [U + 2f])
b.	The fraction slash: ⁄ (character 8,260 [U + 2044])
c.	The division slash: ∕ (character 8,725 [U + 2215])

But, when pasting a copied expression of the form m/n using either, the pasted result does not appear different. They both look to use character 47.

[Note] apostrophe: In a test, I found spaces to be ignored. However, the apostrophe was not. The string Daisy’s yielded a decimal value of 32,552,215,403. The string Daisyins yielded a value of 32,552,217,275. What value is assigned to the apostrophe? A test showed the value for both the space and the apostrophe to be zero. Perhaps the apostrophe not being ignored, as is the space, is a bug. This seems plausible, since base-26 uses only alphabetic characters, unlike converting from an ANSI, ASCII, or Unicode chart, which would account for spaces and punctuation marks (henceforth, the difficulty in coding the unibase function to output error-free conversions).

**Comment by hanna-kn** [comment]
1. _Ctrl_+Shift+A inserts the angle character. There was a bug (now fixed) which caused a segfault when parsing "∠∠".

2. Are you saying that the precision set is sometimes reset to the default (8), or that the result of the same expressions with the exact same settings is calculated/displayed differently?
If the former is true, is other settings and the history also lost? There are bug reports that indicate that the application sometimes does not close properly.
In some cases the final precision of an approximate calculations (e.g. involving physical constants) is lower than the selected precision. For exact calculations (such as bijective 26 conversion), it might be a better idea to select "Simple" numerical display, which, in these cases, will never use scientific notation (except for numbers with millions of digits).

3. I'm not sure I understand. The division sign used in the result will not be affected by the division sign in the expression, but by the division sign selected in preferences. The text pasted in the expression entry is not modified.

The bijective 26 expression is interpreted as a complete mathematical expression (e.g. D*E = 20) and the apostrophe is in this case initially interpreted as ft (foot), but then unfortunately as digits "FT". This has now been fixed.

**Comment by WeirdOddWodd** [comment]
1.	Good job on fixing the bug.
2.	The precision level is reset to the default. I am not sure about the
history being cleared. I generally clear the history prior to exiting
Qalculate!
3.	It appears that what is affected is the right-hand side of the
history list. I was copying from the left-hand side. When I copied it from
the right-hand side, the copied slashes are differentiated.

I do feel silly about the apostrophe after reading your statement. I did
not try ft. I do not know why I was thinking of the inch for the single
quotation mark (or apostrophe). ☹ That only proves that I am strange
<https://www.youtube.com/watch?v=GJY8jJkDoMY>  (a person). My Coder is not
of our kind. He is much greater. 🤣

**Comment by hanna-kn** [comment]
> 2.	The precision level is reset to the default. I am not sure about the history being cleared. I generally clear the history prior to exiting Qalculate!

Have you observed the same behaviour with the latest version (3.5)? There was a bug in previous versions which caused the application to segfault while saving the configuration (thus the precision would not be saved) if the history was empty.

**Comment by WeirdOddWodd** [comment]
So far, my tests of version 3.5 of Qalculate! have shown a retained precision level upon exiting, with or without entries in the history.

**Comment by WeirdOddWodd** [comment]
I thought it odd that I did not see any mention of the unibase function within the help documentation. But, what I did not know is that that function is fully integrated into the base function. I tested it and it worked flawlessly. Opening all codepoints via the escape sequencing is tedious, but useful. The string Daisy's (with an apostrophe [character 39]) is not equal to the string Daisy’s (with a right single quotation mark [character 8,217]). In light of discovering the integration of the unibase conversions into the base function, I have removed the unibase file that you used to initiate the function, as it is not needed any longer.

**Comment by WeirdOddWodd** [comment]
Hanna, I am not sure if I found a bug or if I am misunderstanding something.
Conversion of the string 131211109876543212345678910111213 from
base-1,114,112 yields a value containing 196 digits. Because the initial
string is a numeric value, I added digit grouping to the string. But, that
reduces the resultant value to containing only 75 digits. To reproduce this
unexpected behavior:

1.	base(131211109876543212345678910111213; 1,114,112) (You should see
the value
1,555,678,142,356,411,856,533,628,075,001,106,580,430,380,412,127,433,983,12
2,506,528,421,050,331,379,214,001,720,012,827,950,396,703,710,862,192,729,28
0,124,603,518,764,348,056,137,094,140,903,720,297,840,913,174,943,071,513,83
4,588,537,755,071,723,463,573,555.)
2.
base(131\44211\44109\44876\44543\44212\44345\44678\44910\44111\44213;
1,114,112) (You should see the value
179,201,941,175,616,200,940,055,207,858,014,005,547,583,630,849,680,946,210,
289,157,852,427,693,237.)
3.
base(131\x2c211\x2c109\x2c876\x2c543\x2c212\x2c345\x2c678\x2c910\x2c111\x2c2
13; 1,114,112) (This produces the same value as the string in item 2.)

In theory, the string 131,211,109,876,543,212,345,678,910,111,213 is longer
than the string 131211109876543212345678910111213 and, as such, will produce
a higher value when converted from a given base (in my test, base-1,114,112)
to decimal. But, the results of evaluating the base function with each
string do not reflect that. That might also happen with other text strings;
but, I do not know of any. Alright, I think that I see the problem. In the
incorrect cases, what are intended to be \44 and \x2c are being interpreted
as, for the leftmost comma, \44,271 and \x2c 211, respectively. It looks
that that conversion must be done manually. That value is
4,583,616,454,764,337,137,967,221,519,277,084,148,547,611,443,734,169,931,84
8,011,336,027,967,807,167,309,320,715,510,750,869,048,056,638,033,760,893,73
0,926,342,250,138,006,460,705,651,668,000,507,769,569,850,476,500,567,747,86
6,792,871,867,362,444,186,571,813,181,476,854,615,055,492,684,784,076,508,81
7,050,778,647,194,817,476,876,632,115. That value contains 256 digits. It is
also, sadly, at most, semiprime. The initial string is a prime number. But,
the result of converting that, in the form of a base-1,114,112 string ends
with a 5 and, as such, equals 5 times at least 1 other prime number. It
looks like there is no bug here. I was an oversight by me when considering
the evaluation logic. Have a wonderful day, Hanna!

**Comment by hanna-kn** [comment]
Is this what you want: 
base("131,211,109,876,543,212,345,678,910,111,213"; 1114112)=
4 583 616 454 764 337 137 967 221 519 277 084 148 547 611 443 734 169 931 848 011 336 027 967 807 167 309 320 715 510 750 869 048 056 638 033 760 893 730 926 342 250 138 006 460 705 651 668 000 507 769 569 850 476 500 567 747 866 792 871 867 362 444 186 571 813 181 476 854 615 055 492 684 784 076 508 817 050 778 647 194 817 476 876 632 115

If you use the base function you need need to put the first argument in quotes to avoid removal of digit grouping characters.  Note that "131\44211" is not interpreted as numerals 1, 3, 1, \44, 2, 1, 1, but as 1, 3, 1, and \44211 (the number ends before the first character that is not a numerical digit).

**Comment by WeirdOddWodd** [comment]
Using quotation marks is something that I do not often think of because most strings that use produce the same result with or without them (as they do not include numeric characters or such things as commas or periods).

**Comment by WeirdOddWodd** [comment]
Happy New Year to all!
