### ISSUE TITLE
Bug in unit conversion? Steradian -> Square degrees

### ISSUE THREAD

**Issue by jimrustle** [Qalculate/qalculate-gtk#118]
I found an issue in converting units:

`1 steradian to degree`

returns 57.295780° instead of the expected value of 
32400/pi^2 (°)^2 ≈ 3282.80635 (°)^2

Converting from deg^2 to steradians also has the same issue:

`1 degree^2 to steradian`
0.00030461742 sr^2 instead of 3.0462×10−4 sr 

Windows Qalculate/GTK 3.2.0

**Comment by jimrustle** [comment]
I see now in the manual that degrees^2 aren't recognized as a unit of solid angle. Should this be a feature?

**Comment by hanna-kn** [comment]
I discovered that steradian by accident was defined as m/m. Unfortunately, when fixed, `sr to deg` will instead only return 1.

Dimensionless units are easy to loose (steradian is first converted to m^2/m^2, which is then simplified as 1 before conversion to degrees). This is not (anymore) an issue with plane angles, but I need to find a solution for solid angles (other other dimensionless units), which obviously has not received the same amount of testing.

I will add degree^2 as a unit for solid angles. This will however only affect units visible in various lists in the UI and will not get us any closer to a solution for the current issue.

**Comment by hanna-kn** [comment]
I've now improved solid angle conversion by defining steradian in relation to radians instead of meters. This is not an optimal solution for conversion of dimensionless units, but it works for this particular case.
