### ISSUE TITLE
Button font

### ISSUE THREAD

**Issue by rk4n3** [Qalculate/qalculate-gtk#122]
Hi, this is a really nice calculator.  I found it searching for a calendar that could resize its view (mainly fonts), because I use a really high-res display and all other calculators I've tried are too small to see at really high resolution.

I was excited to see that you have font settings, but then became somewhat disappointed because the most import aspect one needs to see is the buttons ... and since there is no font setting applied to them, they are still too small to see at the high resolution of my display.

If you could simply add button font to your font settings, that would be WAY COOL :)

**Comment by hanna-kn** [comment]
Done. The new setting only affects the keypad. Let me know if other interface elements should also be affected (or if there should be additional font options).

Normally I would expect the user to change the general desktop settings for fonts and scaling instead (I use a 3840x2160 27" display and have no need for custom fonts in Qalculate, but I seldom use the keypad).

**Comment by foreachthing** [comment]
@hanna-kn, thanks!! I have the same 4k setup and sometimes I wished for a tiny-bit bigger font :-) I am getting older ... But I don't want to scale all of Windows the same.

**Comment by rk4n3** [comment]
AWESOME!   Thanks :)

FYI - the reason I don't "change the general desktop settings for fonts" is because I don't USE a big Desktop Environment (Gnome, KDE, XFCE, etc) ... I use the simplest of window managers (notion, FVWM, etc).

**Comment by hanna-kn** [comment]
> FYI - the reason I don't "change the general desktop settings for fonts" is because I don't USE a big Desktop Environment (Gnome, KDE, XFCE, etc) ... I use the simplest of window managers (notion, FVWM, etc).

You can still change the font (and theme) of GTK applications using desktop independent tools or editing configuration files (see https://wiki.archlinux.org/index.php/GTK).


I've now also added an option to select the default font for the whole application.
