### ISSUE TITLE
Label calculator instances

### ISSUE THREAD

**Issue by edp-d6labs** [Qalculate/qalculate-gtk#123]
Thanks so much for your hard work on this amazing calculator! I have used it almost daily for the past 3 years at work and at home.

I do a lot of work with analog-to-digital converters, voltage dividers, etc, and I usually wind up with 10 to 15 instances of qalculate open. It sometimes gets hard to keep track of which calculator holds the value I need. I would like the ability to label each calculator somehow. It would be especially neat if you could set the text that shows on the taskbar/titlebar.

Thanks.

**Comment by hanna-kn** [comment]
Perhaps the window title could be set to the current result and/or expression (probably configurable). Would that be adequate? This would require minimal effort from the user.

Another option would be to add a window title command line option.

My third idea is to add a "mathematical" function for setting the window title.

All three options would be very easy to implement (I see no reason not to add them all).

**Comment by edp-d6labs** [comment]
>Perhaps the window title could be set to the current result and/or expression (probably configurable)

That would work, however I can see that easily just by looking at the calculator anyway. I would prefer one of your remaining suggestions that give the ability for a custom plaintext label.

**Comment by hanna-kn** [comment]
Done (all four options).

**Comment by edp-d6labs** [comment]
> Done (all four options).

You're awesome! Thank you!
