### ISSUE TITLE
Qalculate doesn't recognize gnuplot installation

### ISSUE THREAD

**Issue by RobertSchuh** [Qalculate/qalculate-gtk#124]
With a fresh install of gnuplot and qalculate, the "Plot Functions/Data" option stays greyed out as if gnuplot wasn't installed.

**Comment by hanna-kn** [comment]
The gnuplot binary must be in the found in the executable search path. Thus the gnuplot/bin directory (e.g. C:\Program Files\gnuplot\bin) should be added to the Path environment variable (found under Advanced System Properties).

During the installation of Gnuplot there is an "Add application directory to your PATH environment variable" option, which does this for you.

**Comment by m-zheng** [comment]
@hanna-kn I have gnuplot installed via homebrew on macos and it's accessible by running `/usr/local/bin/gnuplot`. But it shows "Gnuplot was not found" in Qalculator (also installed via homebrew). Do you know what environment variable I shall add? Please find below to help you reproduce this issue.

OS: macos 11.5.1 
Qalculator: 3.20.1
Gnuplot: 5.4
