### ISSUE TITLE
How do I bind a key for reciprocal?

### ISSUE THREAD

**Issue by ballsystemlord** [Qalculate/qalculate-gtk#126]
Hi,
I tried to access the docs, but the menu option is blanked out (perhaps because I don't have gnome and its fun little toys installed). I also searched online in vain.
How do I bind a key for reciprocal?
Thanks!

**Comment by hanna-kn** [comment]
It is not possible to add or modify keyboard shortcuts in the released versions.

I have now however implemented configurable key bindings and it will be possible to bind a key to any function (and more), including inv() (for reciprocal). 

> I tried to access the docs, but the menu option is blanked out (perhaps because I don't have gnome and its fun little toys installed).

qalculate-gtk does not use any gnome "toys". A web browser is all that is required for display of the manual.
