### ISSUE TITLE
Missing pixmap icon

### ISSUE THREAD

**Issue by scx** [Qalculate/qalculate-gtk#130]
In the `Install multiple icon sizes` commit, you removed the pixmap icon.
https://github.com/Qalculate/qalculate-gtk/commit/7e7404c86f5b303e6cd6364f98da2d2280921d78#diff-c36bdf4f1650ffd3698554e9a363a8d1L24-L32

However, **Qalculate-gtk** still expects that there is the `qalculate.png` icon (64x64) in `/usr/share/pixmaps/`.
https://github.com/Qalculate/qalculate-gtk/blob/28437a77fced912401b114d7404364248df4becd/src/main.cc#L89-L98
https://github.com/Qalculate/qalculate-gtk/blob/28437a77fced912401b114d7404364248df4becd/src/main.cc#L97

Anyway, it is the source of this error:
```
(qalculate-gtk:3): Gtk-WARNING **: 23:23:36.049: Error loading icon from file '/app/share/pixmaps/qalculate.png':
	Failed to open file “/app/share/pixmaps/qalculate.png”: No such file or directory
```

This icon is use e.g. in the About dialog.

## About dialog broken

![qalculate-gtk-about-old](https://user-images.githubusercontent.com/510369/73143393-b3446780-4099-11ea-968f-9142570baa0d.png)

## About dialog fixed

![qalculate-gtk-about-new](https://user-images.githubusercontent.com/510369/73143395-b63f5800-4099-11ea-8c36-79c00ee48b37.png)

## Temporary patch

[qalculate-gtk-3.7.0-pixmap.patch.txt](https://github.com/Qalculate/qalculate-gtk/files/4114793/qalculate-gtk-3.7.0-pixmap.patch.txt)
```
diff --git a/data/Makefile.am b/data/Makefile.am
index a651139..960250a 100644
--- a/data/Makefile.am
+++ b/data/Makefile.am
@@ -22,10 +22,14 @@ appdata_DATA = $(appdata_IN_FILES:.xml.in=.xml)
 appdatadir = $(datadir)/metainfo
 @INTLTOOL_XML_RULE@
 
+pixmapsdir = $(datadir)/pixmaps
+pixmaps_DATA = icons/64x64/qalculate.png
+
 dist_man_MANS = qalculate-gtk.1
 
 EXTRA_DIST = \
 	$(desktop_IN_FILES)	\
 	$(appdata_IN_FILES)	\
+	$(pixmaps_DATA) \
 	$(noinst_DATA)
 
```

PR is on the way.

**Comment by hanna-kn** [comment]
Fixed by using icon name.

**Comment by scx** [comment]
Updated:
https://github.com/scx/qalculate-flatpak/commit/a77bb9ef78a047ffc44144ac989bce2ee70933e6

Single-file bundle:
https://github.com/scx/qalculate-flatpak/releases
https://github.com/scx/qalculate-flatpak/releases/tag/v3.7.0+20200128
