### ISSUE TITLE
Qalculate does not save custom expression font setting

### ISSUE THREAD

**Issue by vixfwis** [Qalculate/qalculate-gtk#139]
Other fonts settings work fine. For expression font neither font nor size are saved. I checked that `.config/qalculate/qalculate-gtk.cfg` contains my fonts:

    custom_result_font=Iosevka Term 14
    custom_expression_font=Times New Roman, 16

I can open settings and uncheck/check custom expression font to reset it, then it works until restart. 

Before rechecking font, right after start:
![before rechecking](https://user-images.githubusercontent.com/13175445/77916123-3e5ffa80-72a1-11ea-8b84-ac92ac5c6fca.png)

After rechecking it worked:
![after rechecking](https://user-images.githubusercontent.com/13175445/77916236-6d766c00-72a1-11ea-8cad-6219dee0080d.png)

**Comment by hanna-kn** [comment]
Fixed.
