### ISSUE TITLE
cylinder_sa() give wrong result

### ISSUE THREAD

**Issue by rcspam** [Qalculate/qalculate-gtk#143]
cylinder_sa(5;10) give ~ 471.23890
the right result is ~ 314.15927

So it's a bug

Cheers

**Comment by hanna-kn** [comment]
cylinder_sa the sum of the area of the lateral surface _and_ the area of the top and bottom, using the formula 2πr²+2πrh (2⋅π⋅5²+2⋅pi⋅5⋅10 ≈ 471).

**Comment by rcspam** [comment]
Sorry
