### ISSUE TITLE
Way to Make a comment (before, during, after) a calculation

### ISSUE THREAD

**Issue by SteveH66** [Qalculate/qalculate-gtk#146]
If there is not a way to make a comment, I think it would be a very useful addition to qalculate.  The closest I have seen so far is title or message in the utilities section of the functions.  It kind of works, but I am thinking arguments is what puts a zero or some other number below it when it shows in the history.  It would be nice to be able to make a comment before, during or after doing a calculation --- so that when you are looking back through your history later, you can find a calculation you made before **much** more easily.

For example, you are making a 543 rule calculation (I believe it is) in construction on a building.  You are not in the 'trade' or profession, so you don't do it all the time, so you don't have that formula memorized.  But you built a shed in the back yard.  Later, you are building another shed.  If you could quickly go through your history and find, by seeing the comment "Making a 543 rule calc" in your history, then you could see how you made the calculation --- how the rule works.  And then easily apply it to your new calculation.  Now I know everyone is going to say "just google it".  That's fine, when you have Internet access.  But what about if you are somewhere that you don't **have** (gasp! horror!) Internet access, so you can "just google it"?

If it would be all that hard to throw something like this into the code, understandable.  Doesn't seem like it would be, so would someone consider adding it to the code?  Thanks

**Comment by hanna-kn** [comment]
Easiest solution:
Right-click the history item and select "Add Bookmark…" (this also means that it will not be removed when to history is full).

Best solution:
Create a custom function for the formula. Use _f(x)_ button or File->New->Function (simplified or full version), paste the formula and replace variables with x, y, z, ...

**Comment by SteveH66** [comment]
> Easiest solution:
> Right-click the history item and select "Add Bookmark…" (this also means that it will not be removed when to history is full).
> 
> Best solution:
> Create a custom function for the formula. Use _f(x)_ button or File->New->Function (simplified or full version), enter the formula and replace variables with x, y, z, ...

How much text can be in put into the bookmark?

With best solution, then I have to go through the process of writing a new custom function for every calculation I might decide to do that I think I might need to find or use again later.  1 or 2? Not bad.  10 or 20? OK, but getting to be a pain.  More than that? Better to just have a way to type in a comment/remark hit enter, then do the calculation.  Is it really that hard to add in commenting in the code?  Not being argumentative, just asking for further knowledge.  Most programming IDE, Speed Crunch calculator, probably others, have comment capability.  Thank you for your time and assistance responding, and thank you for your excellent program.

**Comment by hanna-kn** [comment]
The text length of a bookmark is in theory unlimited, but in the current version it is in reality limited to a single history line (this has now been fixed).

I have now modified the behaviour of the message(), error(), and warning() functions so that only the message is added to the history. In addition, expressions beginning with # are now interpreted as a messages. This attaches the comment to the previous expression, but, if prefereable, I can easily make the comment a separate item added to the top of the history.

**Comment by hanna-kn** [comment]
I have now made the following changes:
- The output of the message functions will be added as a separate item at the top of the history.
- Comments can be placed at the end of an expression, after a hashtag (e.g. `f(x) #Making a 543 rule calc`).
- Text after hashtag will be added to the current history item (after the current expression or result), unless double hashtags are used at the beginning of the expression.

**Comment by SteveH66** [comment]
> I have now made the following changes:
> 
>     * Comments can be placed at the end of an expression, after a hashtag (e.g. `f(x)... #Making a 543 rule calc`).
> 
>     * Text a after hashtag will be added to the current history item (after the current expression or result), unless double hashtags are used at the beginning of the expression.
> 
>     * The output of the message functions will be added as a separate item at the top of the history.

hanna-kn, you (and your team, if you are working with one) are just awesome, thank you so much for adding the commenting functionality into Qalqulate!  It is a great program, and the way you 'went the extra mile' as we say here and responded so quickly is just great.

Unfortunately, I will not be able to try out the new functionality as I am using an older version of my Linux Distro, which has a very old version of your Qalculate in it's repositories.  I would try to figure out what I needed to download and how to install it from a tar file (I am a Linux newbie) so that I could try it out before I upgrade my version but I believe the libraries and such in this old version would probably not meet the requirements for the latest version of Qalculate :(

I know that you also put out both a snap package and flatpak package for Linux, but unfortunately this older distro version does not support either snap or flatpak :(  I can run Appimages on this distro but you do not currently make an Appimage for Qalculate and I hesitate to ask you to go to the trouble of making an Appimage for it as I see you already do so much putting out the source, tar package, snap & flatpak for Linux, the Mac versions and of course both 64 and 32 bit as well as portable versions for Windows as well.  It seems you are quite busy putting out all those different packages for all 3 OS already!

But if you ever do have some spare time, it might be nice if you could look into doing an appimage for Qalculate as well.  I find them quite convenient and user friendly for Linux users, especially newbies coming over to Linux, they are just like the portable versions of programs for Windows -- just download, make executable and run.  Very easy and convenient, and portable as well, the Linux version of portable apps.

Anyway, thank you so much for addressing this feature request so quickly and doing such a fine job of it, it is much appreciated.  If you do not have anything further on this issue you can close it if you like, or send me a short reply and I will close it myself.  Thank you so much.
