### ISSUE TITLE
Q: Function to return converted unit?

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-gtk#147]
This is more of a question than an issue:
How can I have a function (i.e.: `\x mm * \y mm * \z MPa * \A{0.9}`) to be returned in `kN` instead of `kJ/mm`?

**Comment by hanna-kn** [comment]
It is not possible to specify the format or units used for the result of a function. With the default settings, the normal behaviour would be display the result in N instead J/m, but there is a bug (https://github.com/Qalculate/libqalculate/issues/187) that specifically affects automatic conversion to Newton (explicit conversion does however work, e.g. `f(x,y,z) to kN`).

**Comment by foreachthing** [comment]
Thanks, Hanna, for the explanation.
