### ISSUE TITLE
Parsed expression incorrect for specified-length conversions to binary

### ISSUE THREAD

**Issue by benbelov** [Qalculate/qalculate-gtk#148]
When converting numbers to binary of a specified width the parsed expression displays incorrect output, saying that there are units of m^3 (not sure where this comes from), inches, and barns. This applies to all widths that I have tested.

 
![image](https://user-images.githubusercontent.com/32214035/80686556-7cae2c80-8a8e-11ea-97a0-fe298624eb05.png)

**Comment by hanna-kn** [comment]
Fixed.
