### ISSUE TITLE
Unable to relocate -- Runtime appears to have hard-coded location

### ISSUE THREAD

**Issue by mj162** [Qalculate/qalculate-gtk#152]
Thank you for making qalculate-gtk available.

1.  Installed Package: qalculate (0.9.7-6ubuntu2) from https://packages.ubuntu.com
2.  Copied payload to a USB stick
3.  Attempted to run from USB stick on an HP Thin Client (oem'd Ubuntu 16.04) with result:

```shell
$ Obt-Message: Failed to open an Input Method
Obt-Message: Failed to open an Input Method

$ qalculate

(qalculate:7180): Gtk-WARNING **: Error loading icon from file '/usr/share/pixmaps/qalculate.png':
        Failed to open file '/usr/share/pixmaps/qalculate.png': No such file or directory

(qalculate:7180): libglade-WARNING **: could not find glade file '/usr/share/qalculate-gtk/glade/main.glade'
**
ERROR:interface.cc:399:void create_main_window(): assertion failed: (main_glade != NULL)
Aborted
```
4. Looked for config files -- didn't find any
5. Check the man page for command-line arguments or environments to handle installation relocation but didn't find any
6. Strung the executable and found embedded the hard-coded string mentioned in the error (above):

```shell
$ strings /tmp/tmpfs/media/GenericFlash_sdb1/usr/bin/qalculate-gtk | more
...
basic_string::_M_construct null not valid
/usr/share/pixmaps/qalculate.png
%s: __pos (which is %zu) > this->size() (which is %zu)
Enter a mathematical expression above. Ex. 5 + 2 / 3
...
```
7. The runtime environment is the above mentioned thin client and no corresponding development environment is available.  Would kindly request guidance in running qalculate-gtk in this environment and use case.

Thank you.

**Comment by hanna-kn** [comment]
I have now created an experimental AppImage (a self-contained binary package) which you are welcome to try:
https://transfer.sh/xA3Z4/qalculate-3.10.0-pre1-x86_64.AppImage (make the file executable and run from anywhere without installation)

**Comment by mj162** [comment]
NTAC:4UC-11
Hi Hannah,

I'm really impressed with how quickly and positively you came-back.  I'm already using AppImages for LibreOffice etc. and they deploy much easily than flatpacks etc.  Thank you.  I will try after time with Clients are revert this evening.  Again many thanks.

Kind regards.

Mike Jackson

**Comment by mj162** [comment]
NTAC:3NS-20
Dear Hanna

I had a chance to try this evening but the file transfer failed; possibly because the antivirus mail scanner ([urldefense.proofpoint.com]: urldefense.proofpoint.com) will have accessed the URL on the incoming email. This is what I got:

$ curl -kRo qalculate-3.10.0-pre1-x86_64.AppImage https://transfer.sh/xA3Z4/qalculate-3.10.0-pre1-x86_64.AppImage

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:--  0:06:10 --:--:--     0

curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.

$ curl -kRo qalculate-3.10.0-pre1-x86_64.AppImage https://transfer.sh/xA3Z4/qalculate-3.10.0-pre1-x86_64.AppImage

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

curl: (7) Failed to connect to transfer.sh port 443: Connection refused

and again with wget:

$ wget https://transfer.sh/xA3Z4/qalculate-3.10.0-pre1-x86_64.AppImage

--2020-05-06 22:10:04--  https://transfer.sh/xA3Z4/qalculate-3.10.0-pre1-x86_64.AppImage

Resolving transfer.sh (transfer.sh)... 144.76.136.153

Connecting to transfer.sh (transfer.sh)|144.76.136.153|:443... connected.

HTTP request sent, awaiting response... No data received.

Retrying.

?

--2020-05-06 22:12:00--  (try: 2)  https://transfer.sh/xA3Z4/qalculate-3.10.0-pre1-x86_64.AppImage

Connecting to transfer.sh (transfer.sh)|144.76.136.153|:443... failed: Connection refused.

Resolving transfer.sh (transfer.sh)... 144.76.136.153

Connecting to transfer.sh (transfer.sh)|144.76.136.153|:443... failed: Connection refused.

Perhaps you could send a fresh link to my DEC User Society email address in a text/plain message: mailto:jackson@eisner.decus.org

Kind regards,

Mike Jackson

m: +44 7305 745 110

**Comment by hanna-kn** [comment]
The link (and the AppImage) has been updated: https://send.firefox.com/download/4660920e72d8e5ed/#-EhR9mxhiXSp4LerbGbT7Q
(transfer.sh is unreliable)

**Comment by mj162** [comment]
NTAC:3NS-20
Good morning Hanna,

Thank you for your prompt and helpful reply.  Downloaded and works great.

(I did attempt to send a "thankyou" to the built-in issue reporter, however it errored: "Failed to open https://github.com/Qalculate/qalculate-gtk/issues".

Very many thanks.

Mike Jackson
m: +44 7305 745 110

**Comment by mj162** [comment]
Good morning, Hanna, I am happy to confirm that Qalculate! (GTK+) 3.10.0 qalculate-3.10.0-pre2-x86_64.AppImage works perfectly on HP's OEM version of Linux 16.04LTS, i.e. HP ThinPro 7.1.  Thank you for responding to the request to provide an AppImage and doing so very quickly fully resolving the issue raised. :)
