### ISSUE TITLE
fatal error: gnome-search-provider2.h: No such file or directory

### ISSUE THREAD

**Issue by quiricada** [Qalculate/qalculate-gtk#153]
Linux a.krumkaka.com 5.4.27 #1 SMP Sat Mar 21 17:14:16 CDT 2020 x86_64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz GenuineIntel GNU/Linux
xfce

recently upgraded my slackware64-current, so d/l libqalculate-master and qalculate-gtk-master
libqalculate compiled ok
qalculate-gtk?

searchprovider.cc:28:10: fatal error: gnome-search-provider2.h: No such file or directory
   28 | #include "gnome-search-provider2.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~

just saw it in the changelog

2019-05-02 Hanna Knutsson <hanna.knutsson@protonmail.com>

        * Gnome shell search provider

thanks

**Comment by hanna-kn** [comment]
Should be fixed now.

**Comment by quiricada** [comment]
happiness again :)
qalculate 3.10.0
thanks
