### ISSUE TITLE
Parse mode bug

### ISSUE THREAD

**Issue by Vahtera** [Qalculate/qalculate-gtk#154]
Windows/GTK+ version 3.9.0.
Using equation "6/2(1+2)" as an example.

With parsing mode set to Adaptive, produces result of
[6/(2 * (1+2))] (interpreted by Qalculate!) and gives the (wrong) result of 1.

With parsing mode set to Parse Implicit Multiplication First the assumption is that Qalculate would interpret this as [6 / 2 * (1+2)] and provide (correct) result of 9.

However, regardless of parsing mode setting, BOTH result in Qalculate! interpreting the equation as "6/(2 * (1+2))" (and thus giving the wrong answer). 

The command line qalc (and thus by extension libqalcluate?) DO work correctly, and 
qalc -s "parse 2" '6/2(1+2)' will provide a correct answer of 9, with the interpreted equation being "6 / 2 * (1+2)", as it should be. 

So, the command line qalc works as should, Qalculate GTK+ does not and interprets the equation in the first way regardless of Parsing Mode setting.

**Comment by hanna-kn** [comment]
"Parse implicit multiplication first" does of course mean that implicit multiplication is calculated first (e.g. 2(1+2)), before explicit multiplication and division. The third option (beginning at zero in qalc), "Conventional Parsing", does not differ between implicit and explicit multiplication and returns the result you expect. The first default mode takes into account whitespace and other factors (e.g. 5ft 2in is interpreted as 5ft+2in). (Perhaps I should change the behaviour in this mode for implicit multiplication with parentheses (e.g. 6/2(1+2)=6/2*(1+2), but 6/2x=6/(2x)), but this might make it even more confusing.)

**Comment by Vahtera** [comment]
REALLY? It's NOT considered a bug if two parts of the software behave differently with the same settings?! What's the point of having the same settings if they work in different ways in command line or GUI?

To reiterate with examples:
Qalcluate! (default, parsing mode 1): 6/2(1+2) == 6/(2*(1+2) == 1 (Which is incorrect)
Qalculate! (parsing mode 2): 6/2(1+2) == 6(2*(1+2) == 1 (Which is incorrect)

qalc: qalc '6/2(1+2)' == 6 / (2 * (1 + 2)) == 1 (which is incorrect)
qalc: qalc -s "parse 2" '6/2(1+2)' == 6 / 2 * (1 + 2) == 9 (this is the correct answer)

So that is NOT a bug, and working as intended? With parsing mode working differently on GTK+ and console application? Really? Users should expect different results with the GUI vs console even if using identical settings? And that is NOT a bug?

Okay, with the original question over at qalc side solved, I was ready to use this over any other program, but this is REALLY a dealbreaker for me. I need to be able to trust a piece of software to produce the same result with the same settings! 

I.. I'm actually astonished and severely disappointed at the same tame. Did I phrase the first post correctly? I can't believe this is really intended to work like this.

**Comment by hanna-kn** [comment]
Did you read my comment?
There are three parsing modes (0="adaptive", 1="implicit first", and 2="conventional") in qalc.

**Comment by Vahtera** [comment]
SORRY! I bad then! I apologize! I'm so sorry. I thought parse mode 2 on qalc was the second parse mode on Qalculate!

This is rather embarrassing. Or, I should say, really embarrassing. Please people reading this, let me just forget about this :)

Sorry!
