### ISSUE TITLE
Wrong Link in "Help -> Report a Bug"

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-gtk#155]
This link, `Help` -> `Report a Bug` won't work on Windows 10 x64 with Q! version 3.10.0.
![image](https://user-images.githubusercontent.com/10420187/81732490-db14db00-9490-11ea-84fa-abd0198a2ac4.png)

**Comment by hanna-kn** [comment]
Fixed. The binaries have been updated (https://github.com/Qalculate/libqalculate/releases/download/v3.10.0/qalculate-3.10.0a-x64.msi).
