### ISSUE TITLE
[Feature requested] - Euclidienne division

### ISSUE THREAD

**Issue by AL-33** [Qalculate/qalculate-gtk#157]
Hi everybody !

I haven't figured out how to get the same result as in the following image.

![Division_euclidienne](https://user-images.githubusercontent.com/65429094/82104965-3a851c00-9719-11ea-94f2-6fb039c6f8fe.JPG)

However, I saw that there are 3 ways to calculate the rest.
        1) 10%3=1       2)  mod(10;3)=1       3)  rem(10;3)=1

Could you integrate a function that returns the qotient and the rest at the same time or explain me how to do ?

Tanks in advance.

**Comment by hanna-kn** [comment]
You can add a function yourself with the expression `(trunc(x/y);rem(x;y))`, using _f(x)_ button or File->New->Function (simplified), or using the command `function qr (trunc(\x/\y);rem(\x;\y))` (creates function with name qr) in qalc. 

The new function can then be called using `qr(5; 2)`  (assuming _qr_ as function name; the parentheses are not strictly necessary), which returns `(2; 1)`.

**Comment by AL-33** [comment]
Perfect !

Thank you so much, for this advice and this awesome software.
Have a good day.
