### ISSUE TITLE
Removing item from history adds new row of current qalculation

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-gtk#159]
If I remove a history item, anywhere _between_ the last and the first, the current calculation will be added to the end (top) again. Now you have the last calculation twice.
One also can't remove the last calculation from history.

Using Win 10 x64 and Qalculate 3.10.0.

**Comment by hanna-kn** [comment]
I can confirm the behaviour when calculate as you type is activated. This has now been fixed.

**Comment by foreachthing** [comment]
Thanks a bunch!
And my apologize for using the wrong repo.

**Comment by foreachthing** [comment]
Fixed in 3.11.
Thanks, Hanna!
