### ISSUE TITLE
Option to disable history after restart

### ISSUE THREAD

**Issue by toxpal** [Qalculate/qalculate-gtk#160]
Using the app for a few years (migrated from Speedcrunch after it disabled % operator in recent versions) and the only thing which bothers me is persistent history.

If I may ask, can you consider a simple feature which allows to keep or not to keep history after app restart? Just a simple checkbox (like in Speedcrunch and/or other calculators), so users can choose if they want to keep history after restart, or should app load with empty history after restart.

Searched in options, read the manual, but it seems such option doesn't exist. Thank you!

**Comment by hanna-kn** [comment]
Done.
