### ISSUE TITLE
[Feature Request]: Perhaps move keyboard tooltips to status bar....

### ISSUE THREAD

**Issue by geeregman** [Qalculate/qalculate-gtk#164]
Hello,
This is an awesome calculator; thank you.
The keyboard tooltips can be helpful, but if you aren't "using" them, they can be somewhat annoying as they flip on and off and cover up other keys.
Perhaps put the tips in a status bar ............?
Again, nice calculator and thanks.

**Comment by hanna-kn** [comment]
I have made a slight modification which should hopefully reduce the annoyance. The tooltip will now be hidden when a keypad button is clicked, which means that the button hover tooltip delay will be reset.

**Comment by geeregman** [comment]
wow, fast response.
thanks, that helps........................g

________________________________
