### ISSUE TITLE
Misplaced '' ignored

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-gtk#167]
When entering this equation `i=±√(−1)`, Q! answers with:

```
i=±√(−1) = i = sqrt(−1)
Misplaced '' ignored
```
![image](https://user-images.githubusercontent.com/10420187/85409527-3513c080-b566-11ea-878e-6a822302d260.png)

If I remove the ±, all is fine.
I did use the ± from the keypad.

**Comment by hanna-kn** [comment]
That kind of usage (a choice of exactly two possible values) is not supported. In Qalculate!, the plus-minus sign (or +/-) is only used for uncertainties and intervals (e.g. 2±0.1 represents an interval between 1.9 and 2.1).

The plus-minus sign in the error message has now been fixed.

**Comment by foreachthing** [comment]
Only someone who has no clue about math can find something nobody would type 😏
