### ISSUE TITLE
Qalculate won't play nice with Hz

### ISSUE THREAD

**Issue by BYT3M3** [Qalculate/qalculate-gtk#17]
Dear maintainer

Something has been bugging me about Qalculate(which is amazing on ALL other aspects, much great, such wow! many congrats!). It always prefers s^-1 in stead of Hz, as a Telecommunication Engineer, this really is a pet peeve for me. Also, the UI used to have a button next to the result where you could choose your unit, but that's gone and I really miss it, could you please give it back or set some option in the preferences for this? That and/or adding support for Hz if at all possible?

Thanks!

**Comment by hanna-kn** [comment]
Hz issue has now been fixed.
When converting to "optimal" unit, positive exponents are now preferred over negative, unless the result includes a another unit with positive exponent.

Are there any specific reason that you prefer the conversion dialog over the conversion tab (or using "to [unit]" at the end of the expression)?

**Comment by BYT3M3** [comment]
Great to hear that!

I honestly hadn't noticed the conversion tab, I'll give it a go!
