### ISSUE TITLE
cannot find how to set the auto conversion

### ISSUE THREAD

**Issue by mbristol78** [Qalculate/qalculate-gtk#170]
Hi, I have searched but cannot find how to set the app to auto convert into hex and binary under the result when using decimal mode.
I am using the latest version 3.11.0 under ubuntu 20.
I also have the windows version under windows 10 and it does what I want, I just can't find the same option to set, if there is any..

Thanks

**Comment by hanna-kn** [comment]
Press the "P" button in the top left corner of the keypad (next to "Exact").

**Comment by mbristol78** [comment]
oh yeah that was that simple ... ;) 
Thanks
