### ISSUE TITLE
Chinese is not complete

### ISSUE THREAD

**Issue by EricMzky** [Qalculate/qalculate-gtk#173]
File Edit Mode is english， but Functions， Variables，Units is Chinese ！

**Comment by EricMzky** [comment]
Can you add language options please ?

**Comment by hanna-kn** [comment]
There is a Chinese translation of the GUI in progress (https://github.com/Qalculate/qalculate-gtk/pull/162). Please try it and help verify the quality of the translation.

If you do not know what to do with a po file, you can download the compiled translation file at https://0x0.st/ixK_.mo and copy it to C:\Program Files\Qalculate\locale\zh_CN\LC_MESSAGES\qalculate-gtk.mo (or the corresponding location on your system).

**Comment by EricMzky** [comment]
> There is a Chinese translation of the GUI in progress (#162). Please try it and help verify the quality of the translation.
> 
> If you do not know what to do with a po file, you can download the compiled translation file at https://0x0.st/ixK_.mo and copy it to C:\Program Files\Qalculate\locale\zh_CN\LC_MESSAGES\qalculate-gtk.mo (or the corresponding location on your system).

Replace the success！ But some of the calculator parameters have been changed to Chinese ！Sin，tan DEL，to，These buttons

**Comment by EricMzky** [comment]
Replace the success！ But some of the calculator parameters have been changed to Chinese ！Sin，tan DEL，to，These buttons

**Comment by EricMzky** [comment]
Replace the success！ But some of the calculator parameters have been changed to Chinese ！Sin，tan ，DEL，to，These buttons

**Comment by hanna-kn** [comment]
The translation obviously needs some more work. I have removed to erroneous button translations (https://0x0.st/ixm9.mo), but since I do not know any Chinese there is not much else I can do. You may of course edit the po file yourself and collaborate with cesaryuan on the translation (see https://github.com/Qalculate/qalculate-gtk/pull/162).

**Comment by EricMzky** [comment]
> The translation obviously needs some more work. I have removed to erroneous button translations (https://0x0.st/ixm9.mo), but since I do not know any Chinese there is not much else I can do. You may of course edit the po file yourself and collaborate with cesaryuan on the translation (see https://github.com/Qalculate/qalculate-gtk/pull/162).

Hi ，I send email for you 。
