### ISSUE TITLE
Negative values fail to display in scientific mode

### ISSUE THREAD

**Issue by hch12907** [Qalculate/qalculate-gtk#176]
As the title says. The area under "RAD" is supposed to show the result in scientific notation.
![image](https://user-images.githubusercontent.com/7030150/89128970-e4f82880-d52b-11ea-8504-8abc67c7932b.png)

It is not a problem with positive values:
![image](https://user-images.githubusercontent.com/7030150/89128985-09ec9b80-d52c-11ea-9631-c31b5e771d3b.png)

Tested with 3.12.0 on Arch Linux

**Comment by hanna-kn** [comment]
Fixed. A new version of qalculate-gtk has been released (this issue was definitely serious enough to warrant a new version) and the Arch Linux package will hopefully shortly be updated.
