### ISSUE TITLE
BYN to EUR, EUR to BYN currency convertion

### ISSUE THREAD

**Issue by forever-live** [Qalculate/qalculate-gtk#177]
1. BYN to EUR exchange rate looks inverted but not exactly (1 BYN to EUR shows €2.7391000).
2. The program asks to download rates every time just after start, not every 14 days.
3. 1 BYN to BYR should be 10000 exactly

Steps to reproduce (1):

- Run the program
- Enter "1 BYN to EUR" to calculate
- "Do you wish to update the exchange rates now?" dialog box appears.
- Say yes, DO NOT check "Do not ask again" check box.
- Result is €2.7391000
- If to look to downloaded "nrby.json" file then value of "Cur_OfficialRate" is 2.8990 (and this is inverted value, BYN for 1 EUR)

Expected result (1):

1 BYN to EUR = 0.35 Euro, like in Google, or 0.34494653 if to calculate exactly

Steps to reproduce (2):

- Close the program
- Run it again
- Enter "1 BYN to EUR" to calculate
- "Do you wish to update the exchange rates now?" dialog box appears.

Expected result (2):

No dialog for update until 14-day period passed

BTW, thanks for this great calculator!

**Comment by hanna-kn** [comment]
Fixed. (I am truly sorry for these clumsy mistakes.)
