### ISSUE TITLE
How to enable night/dark mode?

### ISSUE THREAD

**Issue by SohMahmood** [Qalculate/qalculate-gtk#18]
One of your screenshots has the calculator in a night theme, i was wondering how to apply that as i can't find the option in the menu.

**Comment by hanna-kn** [comment]
There is no night theme setting specific for qalculate-gtk. 
I am using a dark theme for all applications.

You can run qalculate-gtk with a dark theme variant specified on the command line (but to change the window decorations you need to use xprop or similar):
`GTK_THEME=Adwaita:dark qalculate-gtk`

**Comment by SohMahmood** [comment]
Oh ok, thanks for the help

**Comment by jprobst24** [comment]
Is it possible to specify a dark theme variant in windows 10?

**Comment by hanna-kn** [comment]
> Is it possible to specify a dark theme variant in windows 10?

You can either add environment variable (in advanced system properties) GTK_THEME with value Adwaita:dark, or create a file named settings.ini, in folder C:\Program Files\Qalculate\share\gtk-3.0 or C:\Users\\[username]\AppData\Local\gtk-3.0,  with the following contents
```
[Settings]
gtk-application-prefer-dark-theme=true
```
