### ISSUE TITLE
Qalculate abbreviates and approximates relatively small numbers far too often

### ISSUE THREAD

**Issue by DP-M** [Qalculate/qalculate-gtk#180]
example: 
491,089.14+491,089.15 results in: =~982,178

Another example: 800Million+600Million = 1.4E9 

There's plenty of room on the screen to show the actual number, with commas (or spaces) and everything. I'm sure there are plenty of people out there who instantly know that 1.4E9 is 1.4Billion, but I'm not one of them, I'd just like the number back as long as it fits on the screen. ESPECIALLY with really small numbers like the first example I gave. Why does it drop the decimal amount? That seems counter intuitive for a calculator. 

I've looked through the options, and can't find anything to specify how far out I'd like to calculate before abbreviating. I'm hoping I'm missing it! Thank you! 

P.S. Other than this, I love this application, and have completely switched to it, but this drives me mad, and I have to switch to other calculators for "big numbers".

**Comment by hanna-kn** [comment]
The number of digits displayed is determined by the current precision (Mode->Precision). The default is 8 (the highest precision you can set in the GUI is 100 000), and with the default settings the first result should be displayed as 982 178.29.

Scientific notation (e.g. 1.4 × 10⁹ or 1.4e9) is controlled by the "numerical display" setting. In "normal" mode scientific notation is determined by precision, but you can disable scientific notation completely by activating "simple" mode. With the default settings (unless using a very old version) 800Million+600Million actually returns 1 400 000 000.

**Comment by DP-M** [comment]
Awesome, thank you. And I'd also like to apologize if my note came across as frustrated or rude. I was frustrated trying to get something done quickly. I made the changes you just suggested, and boom life is happy. Thank you very much :)

**Comment by samueljohnson** [comment]
@DP-M While working on my main computer (Debian 11.4, Qalculate! 2.8.2), I encountered this approximation error. I had to switch to using Qalculate! on my secondary computer running Arch Linux, which, as it turned out, had higher default precision.

Thanks to you, I now understand the reason behind this difference.
