### ISSUE TITLE
Add copy result to clipboard to GNOME Shell Search Provider

### ISSUE THREAD

**Issue by arrufat** [Qalculate/qalculate-gtk#183]
Hi, I have a small feature request, which I think it will improve usability a lot: having an extra entry to copy the result to the clipboard directly from the GNOME Shell Search Provider, in the same way as the `gnome-calculator` does it:

![image](https://user-images.githubusercontent.com/1671644/91629788-e28fce00-ea06-11ea-84b2-2361e65eea3d.png)

Here's the related `gnome-calculator` code (in Vala):
https://gitlab.gnome.org/GNOME/gnome-calculator/-/blob/master/search-provider/search-provider.vala

Thank you.

**Comment by hanna-kn** [comment]
Done.

**Comment by arrufat** [comment]
Wow, thank you!
