### ISSUE TITLE
Is there a 32-Bit version

### ISSUE THREAD

**Issue by melolontha-melolontha** [Qalculate/qalculate-gtk#186]
I love Qalculate and therefore I also want to install it on my very old Lenovo T43 running Xubuntu 18.04, but in a 32-Bit-version.
When running

`flatpak run io.github.Qalculate`

I get the error message

`Fehler: app/io.github.Qalculate/i386/master ist nicht installiert`

which means that the part named in the message is missing. Where do I get it?

**Comment by hanna-kn** [comment]
The message indicates that you have not installed the Qalculate flatpak. There is however no 32-bit version of the flatpak (i386 is not supported by the current Gnome platform runtime).

There is a 32-bit version of the snap package (install using `sudo snap install qalculate`) available. You also have the option compile and install Qalculate from source.

**Comment by melolontha-melolontha** [comment]
It worked fine and the snap installation was done in 35 seconds installation time. I got version 3.12.1.
I am impressed by the capabilites of this Qalculator!
Thank you very much.
