### ISSUE TITLE
decimal ignored in E notation

### ISSUE THREAD

**Issue by mmccoo** [Qalculate/qalculate-gtk#19]
1/2.5e-6 which should give 400k. it interprets it as 1/25x10-6 yielding 40k.

see attached photo

I'm using the sudo apt install version that goes with ubuntu 16.04

![qalc](https://user-images.githubusercontent.com/1066156/28208094-62610856-688c-11e7-8118-15620df362db.jpg)

**Comment by hanna-kn** [comment]
The version in ubuntu is very old, but the only way I was able to reproduce the issue on the ubuntu version was nevertheless with "Ignore dots in numbers" activated (using a locale with comma as decimal separator), in which case this is obviously the expected behaviour.

**Comment by mmccoo** [comment]
Ah. That could be it. I'm in Germany, but most of my habits are American.

Miles
