### ISSUE TITLE
Invitation to Linux App Summit

### ISSUE THREAD

**Issue by sramkrishna** [Qalculate/qalculate-gtk#191]
Sorry, there didn't seem to be a way to send you email - but we would love to have you give a talk at Linux App Summit about your experience in maintaining Qcalculate for I believe 15 years? If you would be so kind - perhaps you can reach me at sri dot gnome.org - thank you so much!

**Comment by hanna-kn** [comment]
Thanks for asking, but I will unfortunately have to decline the invitation.

My email address should be visible in my profile (https://github.com/hanna-kn).

**Comment by sramkrishna** [comment]
Ah, so it is. 
Thanks for considering the invite.
