### ISSUE TITLE
Qt vs. GTK naming "conventions"

### ISSUE THREAD

**Issue by hyiltiz** [Qalculate/qalculate-gtk#195]
I always just assumed that Qalculate! was a Qt app since most Qt apps love to use the letter `q` somewhere in the name, frequently as a pun; this is prevalent in most KDE apps. I just found that as I removed Gnome out of my system, Qalculate also disappeared and then discovered that, contrary to my assumption, Qalculate wasn't actually a Qt based app.

Maybe either always go with the `Qalculate-gtk` name instead of the `Qalculate!` name, or maybe even `Galculate!`? Q and G here works almost the same effect as a pun.

**Comment by hanna-kn** [comment]
Qalculate! is the title of the whole project, which includes libqalculate, qalc, and qalculate-gtk (there was also a qalculate-kde application, but the transition to KDE 4 was not deemed worth the effort).

qalculate-gtk is not a Gnome application and I see no significant reason to only use it in specific desktop environments (or operating systems). The dependencies (including GTK) are normally installed on GNU/Linux desktop systems regardless of DE.

The name was chosen before 2003. I'd then decided to use the letter q to make the names of my projects unique (e.g. E**q**onomize!, which does however use Qt). Calculate is arguably to generic as a name. During a period Qalculate! was described as "the **q**ueer calculator". The Q can possibly be considered as a continuation of the tradition of R (and S).

It would be difficult to change the name after this long time, and if I were to change it I would definitely not be influenced by the GUI toolkit used (and Galculate! does sound quite ridiculous).

I do not think that it's a good idea to include the name of the GUI toolkit in the name presented to the user.

**Comment by hyiltiz** [comment]
Thanks for the detailed answer along with a review of the history. I've been using `qalc` for at least 3 years now, and didn't realize or forgot that it is in the same family (even though I knew they all relied on `libcalculate`). Thanks for the awesome work, and sorry about the weird nudge.

**Comment by hanna-kn** [comment]
I should mention that I'm aware that Qalculate! is a less then optimal name. I welcome suggestions for a new name, but to be worth replacing the old name, it must be a unique and marketable name, that somehow captures the essence of the application/project and strengthens its identity.
