### ISSUE TITLE
Extra chars when typing `^` on (Swiss) keyboard

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-gtk#196]
When typing `12^2` in Qalculate, it actually prints `12^^q2`.
This is only in Qalculate! Notepad++, Notepad, TexStudio, Browser, etc. it does print `12^2` on screen.
When typing `12` `[CTRL]+[*]` `2` it prints correct.

Please let me know if you need more info.

OS: Win10x64 (English with Swiss keyboard)
Q!: 3.13.0

**Comment by foreachthing** [comment]
Thanks Hanna!
Any chance of a tutorial on "how to build on Windows 10"?
This is rather an annoying issue for me and I'd like to fix it as soon as possible. 
Thanks again!!!!

**Comment by hanna-kn** [comment]
> Any chance of a tutorial on "how to build on Windows 10"?

MSYS2/MinGW (https://www.msys2.org/) is required for compilation on Windows. The build instructions is otherwise the same as for GNU/Linux.

> This is rather an annoying issue for me and I'd like to fix it as soon as possible.

I plan to release the next version on Monday.

**Comment by foreachthing** [comment]
Just wanted to thank you, for this fix and the release (I was not able to build on Windows and MinGW)!
it's working as expected, now! :ok_hand: :relaxed:
