### ISSUE TITLE
Unexpected Behavior

### ISSUE THREAD

**Issue by WeirdOddWodd** [Qalculate/qalculate-gtk#197]
Hanna,
Your documentation on Qalculate! reads as follows: “Bases over 62 use Unicode characters as digits, with the character code as value (e.g. '0' equals 48). Escaped characters are in this case supported (e.g. '\0' = 0, '\523' = 523, '\x7f' = 127).” (Qalculate! manual, Appendix A. Function List, Section: Number Bases)
However, the input base("Daisy"; 64) yields Digit '_digit_' is too high for number base. (where _digit_ is each digit of, in this case, the string Daisy). Unless base-64 is somehow unique, that should have been calculated as follows: 68 × 64⁴ + 97 × 64³ + 105 × 64² + 115 × 64 + 121, which equals 1,166,716,217. I observed that Qalculate! did, in fact, calculate the expression properly. However, it also behaved as if the digit set (in my example: D, a, i, s, and y) is invalid for the target base (in my example: 64). I do not know if that happens with other bases. My Qalculate! version is 3.13.0.

**Comment by hanna-kn** [comment]
Normally only digits with a value lower than the radix are allowed. In this case only a warning is shown and the digit are nevertheless excepted (for bases <= 62, digits >= radix are simply not recognized as digits).

**Comment by hanna-kn** [comment]
I will change the warning message and only show a single warning.

**Comment by WeirdOddWodd** [comment]
Ah

To pull a Homestar Runner: “That explains everything.” <http://homestarrunner.com/halloween2002.html>  Oh, how we can feel so dumb sometimes. 🤣
