### ISSUE TITLE
Default currency no longer detected on Windows (regression)

### ISSUE THREAD

**Issue by benplumley** [Qalculate/qalculate-gtk#198]
In previous versions of Qalculate (I'm not sure which exactly - the problem affects at least versions 3.11 to 3.13), typing a query such as `100 USD` would return an answer in my local currency, GBP. Now, it returns 100 USD as the answer. My Windows default currency is set to GBP.

However, qalc.exe does pick up my default currency correctly - this seems to only affect qalculate-gtk:
![image](https://user-images.githubusercontent.com/7894368/96909765-65c52180-1496-11eb-817f-37a27274bc38.png)

I have made sure "Conversion to local currency" is enabled in Qalculate's preferences.

**Comment by hanna-kn** [comment]
Is "convert to optimal unit" activated and exact mode deactivated?

**Comment by benplumley** [comment]
Thanks Hanna, exact mode was activated. I've changed it to try exact and it's converting properly again.

If this comes up a lot perhaps implicit currency conversions should give a warning when exact mode is active, since it's unlikely anyone would want to convert $100 to $100 using a calculator. But if it's just me then never mind.

**Comment by hanna-kn** [comment]
I will change the behaviour so that conversion to optimal unit is always performed when the expression is a number multiplied by a unit and input equals output.
