### ISSUE TITLE
Clear expression history

### ISSUE THREAD

**Issue by circcc** [Qalculate/qalculate-gtk#199]
"Clear history on exit" preference only clear history.

I want to clear expression history also that is stored in qalculate-gtk.cfg "General" section "expression_history".

Please add "Clear expression history on exit" preference.
or "Clear history on exit" preference clear expression history too.

**Comment by hanna-kn** [comment]
Done ("Clear history on exit" preference will now also clear expression history).

_(qalc.history is used by the command line program, qalc, and is not affected by the GUI settings.)_
