### ISSUE TITLE
qalculate-kde doesn't show choices for "Mode" pop up

### ISSUE THREAD

**Issue by Jonrysh** [Qalculate/qalculate-gtk#2]
1. Who, if anyone, is maintaining qalculate-kde
2. In any case, clicking on "Mode" in the title bar creates a pop-up showing various items: "Number Base", "Numerical Display", ...   However hovering over or clicking on an item doesn't show the menu of choices for the item, so it can't be set; the pop-up works correctly for other title bar choices.  Editing the corresponding item in ~/.qalculate/qalculate-kde.cfg has the desired effect, so I have been able to use qalculate-kde successfully, for at least a few calculations.

**Comment by hanna-kn** [comment]
qalculate-kde has been unmaintained for almost a decade. It uses the obsolete KDE3 libraries, and the KDE4 and KF5 versions are far from finished and not usable.

The correct way to avoid any issues with qalculate-kde is to use qalculate-gtk (or the CLI version 'qalc' if you for any reason really want to avoid GTK+).
