### ISSUE TITLE
Compile Error callbacks.cc in qalculate-gtk-1.0.0 - gcc version 5.4.0 20160609 ubuntu

### ISSUE THREAD

**Issue by HoracioDos** [Qalculate/qalculate-gtk#20]
Hello 
I can't compile callbacks.cc in qalculate-gtk-1.0.0. Please see attached files. I didn't have any problem with version 0.9.9
Thanks in advance!
[Errors.txt](https://github.com/Qalculate/qalculate-gtk/files/1208279/Errors.txt)
[gcc version.txt](https://github.com/Qalculate/qalculate-gtk/files/1208280/gcc.version.txt)

**Comment by hanna-kn** [comment]
It is a gtk version issue.
gtk_show_uri() has been deprecated in favour of gtk_show_uri_on_window(), which however was introduced gtk+ 3.22. I should have kept gtk_show_uri() for older versions of gtk.

Here is a patch for v1.0.0:
https://gist.githubusercontent.com/hanna-kn/5946456a89b8f17db53f84c1a5816b8b/raw/b663ae4ee2786a04aaa9203ec2981742105b2676/qalculate-gtk-20.patch

**Comment by HoracioDos** [comment]
Hello!
I've downloaded the patch in the /qalculate-gtk-1.0.0 folder and I've applied it with:
`git apply qalculate-gtk-20.patch `
Then qalculate-gtk compiled without errors
Thank you very much!
