### ISSUE TITLE
translation items missed...

### ISSUE THREAD

**Issue by circcc** [Qalculate/qalculate-gtk#204]
I can't find "Cut", "Copy", "Pase", "Delete", "Select All" of expression input context menu in latest qalculate-gtk.pot(https://raw.githubusercontent.com/Qalculate/qalculate-gtk/master/po/qalculate-gtk.pot).
![translation](https://user-images.githubusercontent.com/72944033/98454117-428fb700-21a4-11eb-8e24-c4364fdd39ec.png)
and "Insert Emoji" in unit expression context menu.
![1](https://user-images.githubusercontent.com/72944033/98456796-e12c1000-21c4-11eb-8d4b-aea811b2ec43.png)
and this "Close" button in set unknowns.
![close](https://user-images.githubusercontent.com/72944033/98457306-16d2f800-21c9-11eb-85ab-7ae7d9dbcc99.png)

**Comment by hanna-kn** [comment]
These are translated by the GUI toolkit, GTK (in the file gtk30.mo which should be placed in share\locale\zh_CN\LC_MESSAGES in the Qalculate folder). I will include this translation file for all locales with GUI translations (although I've until now forgotten add them to the installer).
