### ISSUE TITLE
Crash in unit window

### ISSUE THREAD

**Issue by circcc** [Qalculate/qalculate-gtk#205]
when convert from is "1 abA" and convert result is "1 abA",
then when I click one of unit, Qalculate is crashed.
I have to change "1" to other number to prevent it from crashing.
![crash](https://user-images.githubusercontent.com/72944033/98456009-5a266a00-21bb-11eb-9fdf-177b69ab606d.png)

**Comment by hanna-kn** [comment]
Fixed.

This was caused by an uninitialized pointer. This was difficult to discover since it did not cause a segfault on my main systems, and did not occur if any sort of calculation had been performed (which would initialize the pointer) before the conversion was attempted.
