### ISSUE TITLE
French translation missing

### ISSUE THREAD

**Issue by oceanborn2** [Qalculate/qalculate-gtk#208]
Hello. I see that the French translation could be improved and would propose my contribution. How can I contribute? Submitting a PR?

**Comment by hanna-kn** [comment]
To create a French translation for qalculate-gtk, edit https://raw.githubusercontent.com/Qalculate/qalculate-gtk/master/po/qalculate-gtk.pot (as fr.po) and submit a PR (or send the file to me in some other way).

For a complete translation, libqalculate (https://github.com/Qalculate/libqalculate) should also be translated (there is already an old partial French libqalculate translation).

**Comment by oceanborn2** [comment]
Ok, understood. Thanks for Qalculate. A great calculator.
