### ISSUE TITLE
sin(), cos(), and friends only display the result if the angle is in radians

### ISSUE THREAD

**Issue by ariand** [Qalculate/qalculate-gtk#21]
If the angle is **not** in radians, the result is always just `≈ sin(<angle in radians>)` (the same is true for cos() and tan()). To get the actual result, I have to specify the angle in radians.

Is there a setting to turn this off, or is this a bug? It used to work just fine in older (< 1.0.0) versions.

**Comment by hanna-kn** [comment]
This was fixed by commit [b135608](https://github.com/Qalculate/libqalculate/commit/b135608d5f7dd3d2521d01ecf0a3fc87f73319ff).

**Comment by ariand** [comment]
Great, thanks. Looking forward to a new release.
