### ISSUE TITLE
Feature Request - Default Order of Operations

### ISSUE THREAD

**Issue by masterq1** [Qalculate/qalculate-gtk#210]
Right now the default for 2+2x2 = 6. Could there be an option where the default would be 2+2x2 = 8? So the order just defaults to the order each operator is entered instead of the proper order of operations?

This app is awesome!
Thanks.

**Comment by hanna-kn** [comment]
I've now implemented different options with similar effect. 
When "chain syntax" is activated the expression "2+2×2" is interpreted as "(2+2)×2". 
If 2+2*2 is typed (using the corresponding keyboard keys or the calculator keypad) with "chain mode" activated, it will result in the expression "(2+2)×2" (with partial results displayed intermittently).

While the appropriate order of operations is obvious for addition, subtraction, (explicit) multiplication, and division, in theses modes, it is less so for other operations (and functions). In the current implementation "2+2sin^2" is interpreted as "(2+sin(2))^2".

**Comment by masterq1** [comment]
Can't wait to see it.  Thanks!

**Comment by masterq1** [comment]
Looks good except the setting isn't being retained after the app is closed.

**Comment by hanna-kn** [comment]
> Looks good except the setting isn't being retained after the app is closed.

Fixed.
