### ISSUE TITLE
[Feature Request]: Execute commands from a file

### ISSUE THREAD

**Issue by drewg3r** [Qalculate/qalculate-gtk#212]
Now in `qalc` there is `qalc -f FILE -i` option that interprets specified file contents as script. For me, it is very useful to create a file like this:
```
Z1 := 5 + 3j
Z2 := 18
Z3 := Z1+Z2
Z23 := conj( (Z2*Z3)/(Z2+Z3) )
...
```
and get access to these variables. It is very convenient to modify or share such a file.
Could there be the same option in qalculate(GUI) the way I can open some file and get it interpreted?

**Comment by hanna-kn** [comment]
Support for reading expressions and commands from a file, as in qalc, has been added in version 3.16.0.
