### ISSUE TITLE
How to restore the default settings

### ISSUE THREAD

**Issue by ddok6** [Qalculate/qalculate-gtk#214]
The font is too large for me to display completely. How to recover?

**Comment by hanna-kn** [comment]
Do you mean that you have selected a font that is so large that you cannot access the font preferences (Edit->Preferences->Fonts) anymore? You can always edit or remove the configuration file (~/.config/qalculate/qalculate-gtk.cfg on GNU/Linux or c:\User\[UserName]\AppData\Local\Qalculate\qalculate-gtk.cfg on Windows)-

**Comment by ddok6** [comment]
Thank you very much.
so easy  hahaha
