### ISSUE TITLE
Segmentation fault on macOS Big Sur 11.1

### ISSUE THREAD

**Issue by b-fitzpatrick** [Qalculate/qalculate-gtk#215]
I'm running qalculate-gtk on macOS 11.1, installed via Homebrew. I upgraded from 3.14.0 to 3.15.0, and it now won't start. I tried downgrading to 3.14.0, and it still crashes. One of the Homebrew maintainers said it was unlikely a packaging issue. It's crashing when calling cairo.

See: https://github.com/Homebrew/discussions/discussions/409 and https://gitlab.freedesktop.org/cairo/cairo/-/issues/420

**Comment by hanna-kn** [comment]
This seems to be fixed in cairo.
