### ISSUE TITLE
[Feature request] Add a function for the number of days in a month

### ISSUE THREAD

**Issue by OmarNamis** [Qalculate/qalculate-gtk#217]
I wanted to get the number of days in the current month or a selected month, but I couldn't find a function or a variable for that.

For example: daysinmonth( today )
If the current date is 2021/01/28, the function should return 31 which is the number of days in January.

It should also account for February, which has 28 days in common years and 29 in leap years.

I hope you can add this.

**Comment by hanna-kn** [comment]
Done,

You can easily add the function yourself using the following expression (select "\x, \y, \z", if using simple function dialog):
`if([month(\X{today})=2;month(\x)=4||month(\x)=6||month(\x)=9||month(\x)=11];[if(year(\x)%4=0&&(year(\x)%100!=0||year(\x)%400==0);29;28);30];31)`

**Comment by OmarNamis** [comment]
Thanks a lot, worke perefectly!
