### ISSUE TITLE
Incorrect download link

### ISSUE THREAD

**Issue by C4illin** [Qalculate/qalculate-gtk#219]
The download link in the description of https://github.com/Qalculate/qalculate-gtk/releases/tag/v3.16.0 is wrong.

https://github.com/Qalculate/libqalculate/releases/download/v3.16.0/qalculate-3.16.1-x64.msi gives 404 and should be
https://github.com/Qalculate/qalculate-gtk/releases/download/v3.16.0/qalculate-3.16.1-x64.msi

**Comment by hanna-kn** [comment]
Fixed.
