### ISSUE TITLE
Enter should re-push last RPN value to stack, not enter a zero

### ISSUE THREAD

**Issue by bulletmark** [Qalculate/qalculate-gtk#22]
Most (all?) RPN calculators allow you to press enter/return to push the current value to the RPN stack 
which duplicates the value in top 2 stack positions. Qalculate instead pushes a 0 to the top of the stack which precludes many of the normal use cases of an RPN calculator. You can use the Copy function but that is inconvenient and awkward.

Please consider changing this so that Qalculate works like other RPN calculators.

**Comment by hanna-kn** [comment]
Fixed in libqalculate. 

This change will be included in the next version planned for Monday).

**Comment by bulletmark** [comment]
Qalculate updated in the Arch repo today and I see this is fixed. Thanks.

    2017-08-29 06:44 libqalculate  1.0.0-2 -> 2.0.0-1
    2017-08-29 06:44 qalculate-gtk 1.0.0-1 -> 2.0.0-1
