### ISSUE TITLE
Local grouping doesn't work in 3.16.1

### ISSUE THREAD

**Issue by regs01** [Qalculate/qalculate-gtk#221]
It was working in 3.15, but in 3.16 it is acting same as Off. No grouping at all. Standard is adding thousand separator into both thousands and decimals. But here it's only thousand separator. Decimals shouldn't be grouped.

**Comment by foreachthing** [comment]
I could not find a standard for grouping numbers below one. Do you have an article or paper about that?

What have you set in the `Preferences` under `Numbers & Operators` in `Digit grouping`?

BTW: No grouping on my end (I'm using `local` settings for grouping; on Windows 10):
![image](https://user-images.githubusercontent.com/10420187/104276437-26124280-54a5-11eb-9ff9-8292c244f68b.png)

**Comment by hanna-kn** [comment]
That is strange. No changes have been made that should have any effect on digit grouping.

> I could not find a standard for grouping numbers below one. Do you have an article or paper about that?

https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf (section 5.4.4, page 150)

**Comment by regs01** [comment]
Figured out. It was Ignore system language that i probably accidentally tickled on while checking Use system tray icon. Unchecked Ignore system language, restarted he app and now grouping properly following local standards.
