### ISSUE TITLE
Handle SIGTERM signal

### ISSUE THREAD

**Issue by maximbaz** [Qalculate/qalculate-gtk#222]
Hello 👋 

Can't thank you enough for this awesome app!

Just one small feature request: it would be nice to properly handle SIGTERM signal and just do exactly what the app does when you press `Ctrl+Q`. SIGTERM is a standard signal which should tell the app that it needs to shutdown normally.

I want to have a simple key shortcut that toggles Qalculate, the easiest way to do it is to bind a key to `pkill qalculate-gtk || qalculate-gtk`, which tries to close Qalculate by sending SIGTERM signal, and if it couldn't close it, then it opens it instead.

What happens right now is that window gets closed, but state is not being saved: history will not be saved, changed settings, changed mode, etc.

Thanks 🙂

**Comment by hanna-kn** [comment]
Done.
