### ISSUE TITLE
Trying to convert to oz_t gives me many units

### ISSUE THREAD

**Issue by danuker** [Qalculate/qalculate-gtk#227]
Hello,

First of all, I want to thank you for creating this magnificent piece of software. I discovered it since KDE's KRunner refactoring made the formula you enter a click away from disappearing, and have been using it ever since, with Alt+F1 as the shortcut.

But I have a small problem: I want to convert a number of grams to a number of troy ounces. This is common when trying to evaluate the price of jewelry. When I input:

`120g to oz_t`

 I get the following result:

`3 oz_t + 17 pwt + 3.883 002 353 gr`

I have no idea what a pennyweight is, nor do I care. What I would love to disable this multi-unit result. Is there a way to do so?

Right now, I have to do `1 oz_t` -> `31.103 476 8 g`, then divide `120/31.103 476 8` to get `3.858 089 588` as oz_t.

I used Qalculate! GTK+ 3.16.0 .

**Comment by hanna-kn** [comment]
Deactivate Mode->Unit Display->Convert to Mixed Units, or prefix the unit expression with "-" (e.g. `120g to -oz_t`).

> Right now, I have to do 1 oz_t -> 31.103 476 8 g, then divide 120/31.103 476 8 to get 3.858 089 588 as oz_t.

`120g/oz_t` should be more efficient.

**Comment by danuker** [comment]
> Deactivate Mode->Unit Display->Convert to Mixed Units

Thank you very much! This is amazing. Also the `120g/oz_t` is very useful when I don't want the unit.

I expected it under Preferences.
