### ISSUE TITLE
RPN arithmetic operators only work on keypad

### ISSUE THREAD

**Issue by bulletmark** [Qalculate/qalculate-gtk#23]
I prefer RPN mode and started using Qalculate on my PC where it works fine. Installed it on my laptop but I can't use it because I don't have a numeric keypad so when you press the operator, e.g. +, it just echos the  character behind the number.

On Arch Linux with libqalculate 2.0.0-1 and qalculate-gtk 2.0.0-1.

**Comment by hanna-kn** [comment]
There is a setting, "Use only keypad keys for RPN", in the preferences dialog. Deactivate it and other keys on the keyboard will also be used for RPN stack operations.

**Comment by bulletmark** [comment]
Thanks, that works. Not sure why anybody would ever want it any other way when using RPN as it seems of zero use to have that option on. Perhaps consider deleting that option?

**Comment by hanna-kn** [comment]
I thought it would be nice to be able to use both RPN and full expressions at the same time, but I will definitely consider deactivating it by default.

**Comment by bulletmark** [comment]
But how is it possible to use an expression when in RPN mode?

**Comment by hanna-kn** [comment]
You just write the expression (using the keyboard) as if you were not in RPN mode. The expression will then first be calculated using the current syntax (which might be RPN syntax) and the result is then pushed to the stack. 

If the expression only contains an operator or a function without arguments, the operator/function will instead be applied to the stack.

There are currently three different RPN mode options: full RPN mode, RPN stack only and RPN syntax only. I think it might be a good idea to change the full RPN mode to use all keyboard operator keys for RPN stack operations and perhaps require that a modifier key is pressed for the other modes.

**Comment by hanna-kn** [comment]
I have made the following changes:
* All operator keys are now used by default for stack operations
* The preferences option now affects both the keypad and the rest of the keyboard
* RPN mode (stack) and syntax options have completely separated again
