### ISSUE TITLE
Error with SI prefix

### ISSUE THREAD

**Issue by AndreaDiPietro92** [Qalculate/qalculate-gtk#232]
Qalculate! (GTK+) 3.16

When i try to use the SI prefix (micro, kilo, mega) the calculator report "invalid character"

Example
![image](https://user-images.githubusercontent.com/36949583/106112009-0d648680-614d-11eb-8772-b1fc87deeae8.png)
![image](https://user-images.githubusercontent.com/36949583/106112246-4b61aa80-614d-11eb-9d54-4670d2d97739.png)

**Comment by hanna-kn** [comment]
Qalculate does not support prefixes without units.

**Comment by AndreaDiPietro92** [comment]
Could it be a future feature? it would be very useful.

**Comment by hanna-kn** [comment]
> Could it be a future feature? it would be very useful.

Possibly for full prefix names, but probably not for abbreviations/symbols (because of conflicts, e.g. m = meter, K = Kelvin, G = gravitational constant).

**Comment by AndreaDiPietro92** [comment]
Thanks
