### ISSUE TITLE
Make order of settings stable in qalculate-gtk.cfg 

### ISSUE THREAD

**Issue by maximbaz** [Qalculate/qalculate-gtk#233]
Hello,

I have another small usability request 🙂 

I keep `qalculate-gtk.cfg` in my dotfiles, a git repo that is synchronized between multiple computers, so that I can use exactly the same settings everywhere.

The issue is, `keyboard_shortcuts` are stored as `unordered_map`, so when they are being dumped to config, they are written in random order. This makes `qalculate-gtk.cfg` "unstable", i.e. it changes all the time, and `git status` always marks this file as changed.

It would be nice to make the config file stable, so that git marks it as changed only if it is indeed updated.

**Comment by hanna-kn** [comment]
Done (keyboard shortcuts are now always saved in the same order, but there might be other settings that are saved in random order).

**Comment by maximbaz** [comment]
Thank you! I think that's the only one, I'll close the ticket and if I spot anything else I'll let you know 🙂
