### ISSUE TITLE
'Handle vector' Custom Function Argument Rule Isn't Kept After Application Restart

### ISSUE THREAD

**Issue by Tynach** [Qalculate/qalculate-gtk#234]
I have some custom functions I've written that rely on the 'Handle vector' argument rule, because sometimes I want to apply the function to a single value, and other times I want it to apply to each value in a vector or matrix (sometimes I use the same function with a vector, sometimes with a matrix, but I always want the function applied to each individual item).

However, in recent versions of Qalculate, that particular rule always gets disabled after I close and re-open the program. Enabling it again lets it work again, but it's a pain because I have several functions I use together that all depend on it being set.

I can change other rules for the arguments and those changes stick, just not 'Handle vector'. If I change several rules, including enabling 'Handle vector' in the set of changes to that argument, all of the other changes (that I've tried) stick after restarting the application... But not 'Handle vector'. So it's not as if I'm just forgetting to click 'Apply' or in some other way not doing it correctly. And besides, making the change *does* work, but it's disabled again the next time I launch Qalculate.

**Comment by Tynach** [comment]
Okay, if I manually add `<handle_vector>true</handle_vector>` to the definitions stored in `~/.local/share/qalculate/definitions/functions.xml`, the next time I load Qalculate the custom functions will have 'Handle vector' set properly.

However, closing Qalculate removes those lines from the XML file. So it's not a usable workaround.

**Comment by hanna-kn** [comment]
Fixed (in libqalculate).

**Comment by Tynach** [comment]
Thank you, @hanna-kn! I was going to compile from master to get the fix right away, but ran into a new problem at the configure stage. Filed Qalculate/libqalculate#250.
