### ISSUE TITLE
Expression widget sometimes not working

### ISSUE THREAD

**Issue by simonflick** [Qalculate/qalculate-gtk#237]
I have "Use system tray icon", "Hide on startup" and "Remember window position" enabled and autorun Qalculate on Windows 10 startup. But sometimes when I open Qalculate the expression widget ist not selectable. There is no cursor and the only thing working is to close the window and open it again.

**Comment by simonflick** [comment]
I have some further information on this issue. I reinstalled Windows 10 on one computer but the issue is still happening and it's always the first time I click on the icon in the taskbar to run Qalculate. I run it on system startup trough a registry entry:
Path: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run
Type: REG_SZ
Data: "C:\Program Files\Qalculate\qalculate.exe"

**Comment by hanna-kn** [comment]
Unfortunately, I still haven't been to reproduce this issue (despite the new information).
Does it always happen?
Does it make any difference if you do not autostart the program or add a shortcut in the startup folder instead?

**Comment by simonflick** [comment]
It does always happen on the first start. I have now switched the method of autostart to a shortcut inside "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup".
Maybe the bug is caused by my high DPI setting? I have 125% scaling on both computers.

**Comment by hanna-kn** [comment]
I've now been finally able to reproduce the issue. 

The issue seems to primarily occur when Qalculate is started before the user has actually logged in. All keyboard input are affected. It is enough for the window to lose and regain focus for the expression entry to start working again.

My simple solution is to activate the window (using gtk_window_present) twice. So far it seems to work.

**Comment by simonflick** [comment]
An alternative might be to add a setting for autostart and implement it according to this Microsoft guide: [Starting an Executable When a User Logs On](https://docs.microsoft.com/en-us/windows/win32/taskschd/starting-an-executable-when-a-user-logs-on)
