### ISSUE TITLE
[Question] Use of custom functions for equations?

### ISSUE THREAD

**Issue by foreachthing** [Qalculate/qalculate-gtk#239]
I'd like to add a function, like [Hooke's Law](https://en.wikipedia.org/wiki/Hooke%27s_law), to the functions list so I don't have to remember the equation _(all my books are at work; I'm not)_. The equation is `F/A=E*dL/L`. Now I'd like to be able to use any variable as output. If I know `F`, `A`, `L` and `E`, I want to know what `dL`'s value is.
Preferably with the corresponding unit.

How do I do that (if possible at all)? I tried with new function but I had to rewrite the equation and enter a new function for each variable. That's a lot of work and easier with MS Excel to realize.

Units:
`F` ~[MPa]~ [N]
`A` [mm^2]
`E` [MPa]
`dL` [mm]
`L` [mm]

EDIT: Force needs to be in [N], of course!

**Comment by hanna-kn** [comment]
Create a function, with expression `\x/\y=\z*\a/\b` or `solve(\x/\y=\z*\a/\b;x)` (optionally units can be added, e.g. `solve((\x*MPa)/(\y*mm^2)=(\z*MPa*\a*mm)/(\b*mm);x)`), and use _x_ instead of a value for the unknown quantity when using the function (e.g. `hookes(1;2;3;x;5)`).

**Comment by foreachthing** [comment]
@hanna-kn, this is awesome!!  😃 
This `solve((\x*N)/(\y*mm^2)=(\z*MPa*\a*mm)/(\b*mm);x))` works like a charm!!!
Couldn't be easier to integrate Hooke's Law. Thanks a bunch!!
