### ISSUE TITLE
config.status: error: po/Makefile.in.in was not created by intltoolize

### ISSUE THREAD

**Issue by idamir** [Qalculate/qalculate-gtk#246]
A new version 3.17.0 cannot be compiled in Debian with the error.
It seems that the issue is due to migration from intltool to gettext and it had started with e0fb16a.

The gettext tool after 0.19.7 is not compatible with deprecated intltool [1].

[1] https://wiki.gnome.org/MigratingFromIntltoolToGettext

**Comment by hanna-kn** [comment]
I'm not able to reproduce this issue on Arch Linux (gettext 0.21), Ubuntu 20.04 (0.19.8), Ubuntu 16.04 (0.19.7), or Ubuntu 14.04 (0.18.3).

**Comment by idamir** [comment]
The same issue took place for other projects that were built in Debian eco-system. E.g. https://github.com/amsynth/amsynth/issues/108, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=724555, https://gitlab.gnome.org/GNOME/gcr/-/merge_requests/17

**Comment by hanna-kn** [comment]
I can reproduce the issue if I run `autopoint -f`, but you really shouldn't. po/Makefile.in.in should not be replaced.

How exactly are you trying to compile qalculate-gtk? Are you not experiencing the same issue when compiling libqalculate? 

The only significant difference seems to be that libqalculate specifies version 0.19.8 and qalculate-gtk version 0.21 in `AM_GNU_GETTEXT_VERSION`. Does it help the change the specified gettext version? Should perhaps this macro should simply removed? Or would it help to add `AM_GNU_GETTEXT_REQUIRES_VERSION`? `AM_GLIB_GNU_GETTEXT` is deprecated and should presumably not be restored.

**Comment by idamir** [comment]
According to debian/watch file, uscan tool gets files from https://github.com/Qalculate/qalculate-gtk/releases with a mask of https://github.com/Qalculate/qalculate-gtk/archive/v(\d[\d.]*).tar.gz

debian/rules is very simple:
>#!/usr/bin/make -f`
>
>export DEB_BUILD_MAINT_OPTIONS = hardening=+all
>
>%:
>        dh $@ --with autoreconf

libqalculate 3.17.0 is built with no problem.

After some changes, I am able to build qalculate-gtk within gettext only, without intltool.
The patches are attached.
By the way, po/sv.po must be fixed to be built (see fix-sv-translation.diff in the patch set).

[patches.tar.gz](https://github.com/Qalculate/qalculate-gtk/files/6123623/patches.tar.gz)

**Comment by idamir** [comment]
qalculate-gtk.desktop is not fully translated. To translate it, po/LINGUAS file must be created filled by ALL_LINGUAS value.

**Comment by hanna-kn** [comment]
I looked at the libqalculate debian package and noticed a patch which removes AM_GNU_GETTEXT (and AM_GNU_GETTEXT_VERSION) from configure.ac and @LTLIBINTL@ from Makefile.am (in libqalculate and src dirs). Perhaps a similar patch for qalculate-gtk would solve this issue.

The main issue with your patches is that the whole appdata file is translated. Developer name and countless lines of release changes should not be translated.

**Comment by idamir** [comment]
Indeed, applied the same patch solved all issues.

[fix_autogen.patch.gz](https://github.com/Qalculate/qalculate-gtk/files/6129358/fix_autogen.patch.gz)

**Comment by idamir** [comment]
I think the issue is solved.
