### ISSUE TITLE
Answer Not Visible

### ISSUE THREAD

**Issue by samueljohnson** [Qalculate/qalculate-gtk#247]
The Answer section and Answer font, both are in dark color, thereby making it difficult to read the answer.

![Screenshot from 2021-03-13 16-57-00](https://user-images.githubusercontent.com/916918/111028658-f5577680-841d-11eb-9d90-abe78f00991e.png)

Even after changing themes, the result is same.

Is there anyway to fix this?

**Comment by hanna-kn** [comment]
Please specify Qalculate version (version number and binary source), operating system/distribution (and version), and GTK theme and version.

**Comment by samueljohnson** [comment]
Qalculate Version: 3.17.0
Operating System: Arch Linux
GTK Theme: Zukitre

Screenshot below shows Gnome's Adwaita theme:

![Screenshot from 2021-03-13 19-03-46](https://user-images.githubusercontent.com/916918/111031748-1379a280-842f-11eb-858c-d6b5881aa4ef.png)

**Comment by hanna-kn** [comment]
Arch Linux is my primary platform and I've never experienced anything similar.

Which desktop environment/window manager/compositor are you using?
Are you using Xorg or Wayland?
Are there anything unusual in ~/.config/gtkrc or ~/.config/gtk-3.0/?

The background of the widgets are set using `* {background-color: @theme_base_color}` (@theme_base_color should be the same colour as the background of text widget).

**Comment by samueljohnson** [comment]
![Screenshot from 2021-03-14 07-55-54](https://user-images.githubusercontent.com/916918/111055426-b36d1580-849b-11eb-9872-50d1edd83c53.png)


After recreating the ~/.config/gtk-3.0 directory, the issue has disappeared. After investigating, I find that the previous directory had 'colors.css' file with '@define-color theme_base_color #232629;'. I'm not sure how this file got created.

Since none of my other applications were affected, I incorrectly assumed that this is Qalculate's fault.

Thanks for your help.
