### ISSUE TITLE
Install problem: libqalculate.so.21

### ISSUE THREAD

**Issue by a-Rahmati** [Qalculate/qalculate-gtk#248]
I've installed libqalculate and qalculate-gtk with source code from [download page](https://qalculate.github.io/downloads.html).
I did whatever was described in the README files. But it doesn't work
```
$ qalculate-gtk 
qalculate-gtk: error while loading shared libraries: libqalculate.so.21: cannot open shared object file: No such file or directory
```

How do I install libqalculate.so.21?
***
![Selection_125](https://user-images.githubusercontent.com/52320192/111076543-f06bf300-8501-11eb-9aaf-9e7d0e8174e1.png)

**Comment by hanna-kn** [comment]
Did you run ldconfig (as root)?

**Comment by a-Rahmati** [comment]
I had not run `ldconfig`. I did and it's working now.
Thank you.
