### ISSUE TITLE
Strange result for derivative

### ISSUE THREAD

**Issue by nickovchinnikov** [Qalculate/qalculate-gtk#249]
d(x^(−1))/dx

![image](https://user-images.githubusercontent.com/7540752/112487879-22951480-8d8e-11eb-9b57-67c60f870761.png)

**Comment by hanna-kn** [comment]
That kind of notation is obviously currently not supported (even though the result was surprisingly close), and, as you can see below the expression, d is instead interpreted as day. Use `d/dx x^-1`, or preferably `diff(x^-1)`, instead.
