### ISSUE TITLE
erreur d'affichage dans Qalculate

### ISSUE THREAD

**Issue by Yann48** [Qalculate/qalculate-gtk#25]
Quand on fait: Functions → Économie → Finance → ...
La première fois le menu s'affiche bien.
Mais si on sort de ce menu et qu'on y retourne, le menu ne s'affiche plus.
Sorry, I speak (write) french.
Yann48

**Comment by hanna-kn** [comment]
I cannot reproduce the issue. You seem to be using an old version, since the Finance menu does not exist in recent versions (> 1.0). Otherwise there might be leftover/conflicting files, from an earlier version, causing unexpected behaviour.

**Comment by Yann48** [comment]
I use the version 0.9.9 (source: ubuntu-artful-universe).

I can't obtained a recent version with snap.

Don't worry... It's not really a problem for me.

Thank you very much for your answer.

Yann48.

 

 

 

 

> Message du 02/11/17 18:41
> De : "Hanna Knutsson" 
> A : "Qalculate/qalculate-gtk" 
> Copie à : "Yann48" , "Author" 
> Objet : Re: [Qalculate/qalculate-gtk] erreur d'affichage dans Qalculate (#25)
> 
>
> I cannot reproduce the issue. You seem to be using an old version, since the Finance menu does not exist in recent versions (> 1.0). Otherwise there might be leftover/conflicting files, from an earlier version, causing unexpected behaviour.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Qalculate/qalculate-gtk","title":"Qalculate/qalculate-gtk","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Qalculate/qalculate-gtk"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hanna-kn in #25: I cannot reproduce the issue. You seem to be using an old version, since the Finance menu does not exist in recent versions (\u003e 1.0). Otherwise there might be leftover/conflicting files, from an earlier version, causing unexpected behaviour."}],"action":{"name":"View Issue","url":"https://github.com/Qalculate/qalculate-gtk/issues/25#issuecomment-341502063"}}}
