### ISSUE TITLE
Strange value when converting °C/cm to K/m

### ISSUE THREAD

**Issue by malvarenga123** [Qalculate/qalculate-gtk#253]
The conversion works fine isolated:
1cm to m = 0.01 m
1°C to K = 274.15 K

But when you try:
1°C/cm to K/m = 373.15 K ∕ m

Shouldn't the result be 27415 K/m?

**Comment by foreachthing** [comment]
I'd expect 27415 K/m. 1°C per cm, and there are 100 cm in a meter, hence times 100.

And also this happened:
![image](https://user-images.githubusercontent.com/10420187/113662606-b3ca8c00-96a8-11eb-909a-d25b8719c59d.png)
So, you'll need to know whether it's an absolut or relative problem.

Three modes, three results:
1 = hybrid
2 = absolut
3 = relative
![image](https://user-images.githubusercontent.com/10420187/113662939-613d9f80-96a9-11eb-8711-56e437266c96.png)

**Comment by hanna-kn** [comment]
The expression before "to" is always evaluated independently first.
In hybrid mode degree Celsius is not converted, unless there are other temperature units in the expression.
"1 °C/cm" returns "100 °C/m". "100 °C/m" is then converted to K/m (100 °C = 373.15 K).

**Comment by malvarenga123** [comment]
Ok, I understand now. Thank you for the answers.
