### ISSUE TITLE
Rethink "ignore dots in numbers" default setting

### ISSUE THREAD

**Issue by stephtr** [Qalculate/qalculate-gtk#255]
I would pledge for disabling the setting "ignore dots in numbers" by default.
In Europe it is quite common to use "," as a comma separator in daily live, but sometimes also "." when doing scientific work.
If one isn't aware of qalculate's default setting, it can happen by habit that one sometimes uses the wrong comma separator, resulting in an error of several orders of magnitude.

As an alternative one could also add a new option: error on dots in numbers, which just shows an error message together with the hint to specify the desired behavior in the settings.

**Comment by hanna-kn** [comment]
"Ignore dots in numbers" is enabled by default when the (system) locale specifies that dot is the default thousands separator.

I think I've come up with a better solution. The user will now be asked for the correct interpretation when a dot is first encountered in a number (if comma is decimal separator).

**Comment by stephtr** [comment]
Wow that sounds great!
Thanks for your fast work!
