### ISSUE TITLE
Custom Themes and dark/light theme preference

### ISSUE THREAD

**Issue by snaphat** [Qalculate/qalculate-gtk#258]
So I know a dark theme setting has been added to qalculate to make it easier for windows users to get the dark theme enabled.

I just wanted to note that one thing I found out when using custom themes is that if the config file contains a preference for either light/dark theme, then the custom theme will be (mostly) ignored. In order to get it to work, you have to manually delete the setting from the config.  I'm not necessarily asking for this to be fixed or changed, just wanted to let the dev know

**Comment by hanna-kn** [comment]
The next version will replace the dark theme check box with a menu with options "default", "light", "dark", "high contrast", and "dark high contrast". The "default" option will reset the theme option and use the (custom) desktop wide theme.
