### ISSUE TITLE
Display bug on dual screens 

### ISSUE THREAD

**Issue by pedoc** [Qalculate/qalculate-gtk#259]
Envs
Display 1: Main display, resolution 2560*1440
Display 2: Resolution 1920*1080

Issue：
When the program is on the main display, menus, etc. will be displayed on the second screen. 
But if you drag the program to the second monitor, the menu can be displayed correctly. 

Expected：
The menu should be displayed in the correct position。

Snapshots:
monitor layout: left as main,right as second.

On main monitor:
![image](https://user-images.githubusercontent.com/6604230/115643967-4e38f980-a350-11eb-9129-8ed0f56b72ad.png)

![image](https://user-images.githubusercontent.com/6604230/115643992-5a24bb80-a350-11eb-99fe-3132f7bda11d.png)

![image](https://user-images.githubusercontent.com/6604230/115644012-6577e700-a350-11eb-891f-72e9d957b443.png)

On second monitor:
![image](https://user-images.githubusercontent.com/6604230/115644071-82acb580-a350-11eb-9ad5-8149bd1950d5.png)
![image](https://user-images.githubusercontent.com/6604230/115644090-8d674a80-a350-11eb-9a66-b13ef9795e0a.png)

**Comment by pedoc** [comment]
The problem still exists in 3.19

**Comment by hanna-kn** [comment]
I still haven't been able to reproduce the issue.

With similar (virtualized) configuration (on the left is the main left monitor):
![Skärmbild från 2021-05-29 16-07-58](https://user-images.githubusercontent.com/19703699/120073873-7f68c000-c09a-11eb-86ba-f234ff6b629c.png)

**Comment by pedoc** [comment]
@hanna-kn hi,thanks u time
Guess the possible reasons are:
1.Maybe need to set the 2 monitors to different resolutions 
2.Maybe the reason for the virtual display

**Comment by hanna-kn** [comment]
> 1. Maybe need to set the 2 monitors to different resolutions

The right screen in my test has resolution 1920x1080 and left screen approximately 2560x1440.

> 2. Maybe the reason for the virtual display

From the point of view of the operating system (Windows) there should not be any difference.

**Comment by pedoc** [comment]
Another possibility is a bug in the preview system itself. I am currently using Windows10 21H1 (19043.1023) .

I will use a virtual machine to try to reproduce this problem on other versions of Win10, and I will give back later :)

**Comment by pedoc** [comment]
I also failed to reproduce this problem on another win10 (version 20h1), so I have reason to believe that this is caused by a bug in the preview system itself or due to the mutual influence of other environmental factors. This is not a Qalculate bug.
