### ISSUE TITLE
[Question] Is it possible to display numbers in 2^X format?

### ISSUE THREAD

**Issue by joshpetit** [Qalculate/qalculate-gtk#262]
I'm doing some calculations with bits and is it possible to output expressions as 2^X? 

For example, having `2B` output as `2^3 bits`?

**Comment by hanna-kn** [comment]
No.

The primary solution is to use the log2() function (e.g. `log2(8) = 3`).

Alternatively the floating point value of the floating point conversion dialog will show similar output (e.g. `1 × 2^3`). Enter any mathematical expression, without units, in the decimal value field.

If decimals in the exponent (or multiplier) are not of interest, activate binary output and use to position of the leftmost 1 to determine the exponent.

**Comment by joshpetit** [comment]
Alright makes sense! I appreciate it thank you.
