### ISSUE TITLE
Feature request: variable assignment

### ISSUE THREAD

**Issue by ferenczy** [Qalculate/qalculate-gtk#266]
I have a feature request to implement an easier assignment of values to temporary/intermediate variables.

The current way of variable management using the _Variables_ and the _New Variable_ dialogs are fine for defining which will be used repeatedly for a longer period of time, e.g. mathematical/physical constants, etc. But for temporary/intermediate variables, which I'm reassigning very often during calculations, it would be convenient to be able to assign value to a variable simply by typing an equation directly into the Qalculate's input box, for example:

    x = (some calculation)

It's implemented, for example, in SpeedCrunch and it's very convenient.

If it would collide with any existing feature, it may use a different assignment operator, for example `:` or `:=` ([the assignment operator used in Python](https://www.python.org/dev/peps/pep-0572/)).

Since it wouldn't be possible to set the variable category when a new variable is being created that way, I'm proposing to simply use the _Temporary_ category for all variables created by the assignment. It's the goal of this feature request anyway, to assign values to temporary variables.

I know, I can just press <kbd>Ctrl</kbd>+<kbd>S</kbd> to open the _New variable_ dialog, but it requires more key-presses and apart from setting the category, it doesn't add any value. It does add a value when I need to set the category, which means I'm probably crating some longer-lasting variable.

Also, the standard memory function (`MS`, `MR`, `MC`, `M+`, `M-`) is not a sufficient replacement since it can contain just one value and I cannot set a name.

## Unrelated variable-related question

Since variables in the _Unknow_ category have names I'm usually using for quick/temporary calculations (`x`, `y` and `z`), can I use them for such purpose (storing temporary/intermediate results) without any side-effects or do they have any special purpose, please?

**Comment by hanna-kn** [comment]
It's already possible to use `:=` (e.g. `x:=5`). The temporary category is used. In addition the save() function (e.g. `save(x, 5)`) or the store and save qalc commands (e.g. `/store x`) can be used. `=` is used for equalities (primarily equations, e.g. `y^3=8` returns `y=2`).

If you save the variable as x, y, or z (or any other name used by a predefined object), a warning messages will be shown which informs you that the object will be deactivated until the new variable is removed.

**Comment by ferenczy** [comment]
Oh, I'm really sorry that for a moment, I had doubts about Qalculate being perfect already! 😉 My bad. I should read the manual better next time (yep, [it's there](https://qalculate.github.io/manual/qalculate-variables.html)).

Also, thank you for the explanation regarding the use of names of predefined variables.

You can close this issue. I'm more than satisfied. 👍 Your calculator is really awesome! Not so far from being perfect actually. 🙂
