### ISSUE TITLE
thousand separator

### ISSUE THREAD

**Issue by quiricada** [Qalculate/qalculate-gtk#27]
thanks much, just discovered this gem, seems to have everything that i need, one thing that bugs me, is there any way to display result with thousand separators? millions and above just makes me cross-eyed, anyway to remedy this basic ui requirement?

**Comment by hanna-kn** [comment]
Done.

By default thin space will be used as thousands separator for all locales.

**Comment by quiricada** [comment]
thanks, one pair of eyes saved :)
 

    On Wednesday, November 22, 2017, 1:09:53 AM GMT+8, Hanna Knutsson <notifications@github.com> wrote:  
 
 
Done.

By default thin space will be used as thousands separator for all locales.

**Comment by quiricada** [comment]
oops, didn't close the issue!

i don't know if this is a new issue?
the result copied to clipboard contain the thin space separator, when i paste it into a number field, some programs just hate having thin space between numbers. default on "de-spacing" or a switch on whether to "de-space" when copied?

**Comment by hanna-kn** [comment]
I've now added an option to not copy digit separators (default off).

It might be a better idea to add an additional action for copying unformatted result. The preferences dialog will at least need a new layout.

**Comment by quiricada** [comment]
thanks!

it's not working at the moment

copy digit separator = unchecked
digit grouping / standard = selected

pasted result include digit separator

**Comment by hanna-kn** [comment]
Fixed (it worked for me because standard and local separator is equal for my locale).

**Comment by quiricada** [comment]
back in town.
just d/l the git and everything works!
thanks again.
