### ISSUE TITLE
FR: Allow setting color of text (especially in dark mode)

### ISSUE THREAD

**Issue by Gitoffthelawn** [Qalculate/qalculate-gtk#270]
I find the contrast in dark mode to be too extreme.  It would be nice to be able to specify the foreground color of the text.

Ideally, allowing the user to also specify the background color would be great, but the dark background happens to work fairly well for my eyes (if I had a choice, I would go a little darker).

**Comment by Gitoffthelawn** [comment]
@hanna-kn Thanks Hanna!  I will give that a try.  Since I never formally installed GTK, to where would I install a GTK theme?

**Comment by hanna-kn** [comment]
> Since I never formally installed GTK, to where would I install a GTK theme?

I've never tried installing a GTK theme on Windows.

It should it least work to install the theme in the share\themes folder in the location where Qalculate is installed (e.g. C:\Program Files\Qalculate). 

To theme should then be specified by creating the file settings.ini in C:\Users\[username]\AppData\Local\gtk-3.0 with contents (replace `[name-of-theme]` with the name of the theme):
```
[Settings]
gtk-theme-name=[name-of-theme]
```

**Comment by Gitoffthelawn** [comment]
Thank you!

When you wrote:

> Install the theme in C:\Users[username]\AppData\Local\themes.

was that correct, or does it have a small mistake?

Obviously, you meant to have a backslash between `Users` and `[username]`, but is there also supposed to be a `gtk-3.0` in there?

Is:

`C:\Users\[username]\AppData\Local\themes`

correct, or:

`C:\Users\[username]\AppData\Local\gtk-3.0\themes`?

**Comment by hanna-kn** [comment]
The backslash was missing, but the rest was correct (without gtk-3.0). It is possible that there are other folders that work, but I only tried with AppData\Local\themes\ (on GNU/Linux themes are placed ~/.themes/ or /usr/share/themes/).

**Comment by Gitoffthelawn** [comment]
Thank you so much Hanna!

I used the CSS trick and it WFM.

Would you like us to close this issue, or keep it around since it would still be nice to have the functionality in Qalculate's UI?

As an aside, the portable release of Qalculate isn't quite portable due to GTK, but I'm guessing there is little you can do about that.  Is my guess correct?
