### ISSUE TITLE
Feature Request: Mode -> Always on Top

### ISSUE THREAD

**Issue by IWaZzAI** [Qalculate/qalculate-gtk#274]
It would be wonderfully efficient if the calculator could be set to stay on top of other windows. This might be difficult to implement because it's a cross platform program, but if it was easy to implement then it would be a good feature to add, especially with the minimal window.

Thanks!

**Comment by hanna-kn** [comment]
Done. (I have tested it successfully on Window and GNU/Linux, with Xfwm.)

**Comment by IWaZzAI** [comment]
Wow. That was incredibly fast. Thank you!
