### ISSUE TITLE
Feature Request: Shortcut added to use top result of completion suggestions.

### ISSUE THREAD

**Issue by IWaZzAI** [Qalculate/qalculate-gtk#275]
If this was easy to implement, it would be great to have the ability to that allows a key press (like Tab) to complete the first suggested completion. I'm not sure if this is already implemented somewhere.

I couldn't see it in the "Edit" -> "Keyboard Shortcuts" -> "Add" list.

I assume because Tab is used for moving through the UI this might be trickier than it seems, checking if the Suggestion Completion list is visible and treating the command differently in that situation.

At the moment I'm using AutoHotKey to press "Down -> Enter" when I hit Tab and Qalculate is focused, so I've got a work around if this is too hard to implement.

**Comment by hanna-kn** [comment]
Done. (With this change it is possible to assign a keyboard shortcut to activation of the first (or selected) completion item. Tab is set as the default key.)
