### ISSUE TITLE
Restricted keys on Shortcut menu prevent assigning defaults back

### ISSUE THREAD

**Issue by IWaZzAI** [Qalculate/qalculate-gtk#276]
While seeing if I could assign "Tab" to a hotkey shortcut to test if the program overwrote it's standard functionality of moving through the UI, I noticed I couldn't assign anything to it. I anticipate this is to prevent problems by resticting special keys.
I then decided to try the same for F1 replacing "Help" but was unable to assign anything to "F1".
I then deleted the "Help" shortcut to test if I could assign something to F1 if it was no longer assigned to anything, and was unable to.
I then tried to reassign "Help" to F1 and was unable to.

**Comment by hanna-kn** [comment]
Fixed. (Keyboard shortcuts without modifier was unintentionally not allowed.)
