### ISSUE TITLE
Segfault when using Names Details button in New Variable dialog

### ISSUE THREAD

**Issue by rux616** [Qalculate/qalculate-gtk#28]
When defining a new variable (`Edit` menu -> `Manage Variables` option -> `New` button -OR- `File` menu -> `New` submenu -> `Variable` option), if you click the `Names Details` button, the program crashes with a segmentation fault.

I'm using the v2.1.0 tagged branches of both `libqalculate` and `qalculate-gtk` on Ubuntu 16.04.

**Comment by hanna-kn** [comment]
Fixed.
