### ISSUE TITLE
Crashes when opening periodic table (v3.19.0)

### ISSUE THREAD

**Issue by Gitoffthelawn** [Qalculate/qalculate-gtk#283]
When opening the periodic table, v3.19.0 crashes.  No problem with v3.18.0.

Test system: Qalculate v3.19.0 32-bit portable on Win7 64-bit.

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	qalculate.exe
  Application Version:	0.0.0.0
  Application Timestamp:	60abe617
  Fault Module Name:	qalculate.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	60abe617
  Exception Code:	c0000005
  Exception Offset:	0020cd52
```

**Comment by hanna-kn** [comment]
Fixed (I forgot that `setlocale(LC_MESSAGES, NULL)` cannot be used on Windows).

**Comment by hanna-kn** [comment]
Fixed in version 3.19.1 (https://github.com/Qalculate/qalculate-gtk/releases/download/v3.19.0/qalculate-3.19.1-i386.zip).

**Comment by Gitoffthelawn** [comment]
Thanks for the fix!

**Comment by Gitoffthelawn** [comment]
Tested... fixed!  Thank you!
