### ISSUE TITLE
Additional Windows in "Keep above other windows" mode

### ISSUE THREAD

**Issue by IWaZzAI** [Qalculate/qalculate-gtk#285]
First off, thank you so much for this feature, it is really very useful.

I've noticed that the handling of any other windows created by Qalculate are also placed behind the main window. This could be particularly problematic if any windows don't let you move the main window before answering the prompt (not sure if this is the case for things like the Update Currency prompt). If the user isn't able to answer the question, or move Qalculate out of the way. Maybe applying the rule to all windows Qalculate! creates (if the setting is selected) would be the easiest solution?

**Comment by hanna-kn** [comment]
Fixed in version 3.19.1.
