### ISSUE TITLE
Dark Theme visibility (on Linux)

### ISSUE THREAD

**Issue by LeDilam** [Qalculate/qalculate-gtk#286]
There are visibility issues with some parts of Qalculate in Dark mode ("Dark" and "Dark high contrast" themes).
Issues are not the same depending on if the application is in foreground or in background.

When Qalculate is in foreground, the toolbar is white (should be dark) with white text : impossible to read what's on it.
![Qalculate in forground](https://user-images.githubusercontent.com/77668246/119675456-5a2b4600-be3d-11eb-97c4-7004ee3db0af.png)

When Qalculate is in foreground, the toolbar is still white but since the text is black then it is readable. On the other hand, buttons and some text become black on a dark background which is very difficult to read.
![Qalculate in background](https://user-images.githubusercontent.com/77668246/119675522-66af9e80-be3d-11eb-8c12-d4c59fa23fc0.png)

I think these changes between colors depending on whether the app is selected or not are not normal.

I'm on Linux KDE neon 5.21, with the desktop KDE Plasma 5.21.5 .
I have downloaded Qalculate by FlatPak and I'm currently on Qalculate version 3.19.0 .

I'm french, sorry for my mistakes in English.

**Comment by hanna-kn** [comment]
The button borders are also odd. I do not know what might cause this. (The slightly different colour of the expression entry when inactive is however a known issue.)

This is the expected appearance (Flatpak 3.19.0, Ubuntu 20.04, KDE Plasma 5.18.5, "Dark" theme):
![VirtualBox_Ubuntu 20](https://user-images.githubusercontent.com/19703699/119702528-d92c7880-be55-11eb-82f0-c3a8e483448f.png)
<img width="257" alt="VirtualBox_Ubuntu 20b" src="https://user-images.githubusercontent.com/19703699/119702542-dc276900-be55-11eb-9992-ec92087114f1.png">
or with Breeze theme (snap version of Qalculate):
![VirtualBox_Ubuntu 20d](https://user-images.githubusercontent.com/19703699/119703969-66240180-be57-11eb-866d-296017df85b7.png)

**Comment by suryanisaac** [comment]
Hey, I'd love to add some Manjaro inspired themes, can you please tell me where/how you guys deal with themes? Thanks
