### ISSUE TITLE
error from callbacks.cc on Mac

### ISSUE THREAD

**Issue by jjstickel** [Qalculate/qalculate-gtk#3]
Compiling on Mac (Yosemite; likely for other flavors):

`In file included from callbacks.cc:27:
In file included from ./callbacks.h:27:
In file included from ./main.h:33:
In file included from /opt/local/include/libqalculate/qalculate.h:15:
In file included from /opt/local/include/libqalculate/includes.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/vector:265:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__bit_reference:15:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:702:71: error: invalid operands to binary expression ('const tree_struct' and 'const tree_struct')
    bool operator()(const _T1& __x, const _T1& __y) const {return __x < __y;}
                                                                  ~~~ ^ ~~~`

**Comment by jjstickel** [comment]
This patch fixes it:
[https://trac.macports.org/browser/trunk/dports/math/qalculate-gtk/files/patch-src_callbacks.cc-const.diff](url)
It was generated with version 0.9.7 but still applies cleanly for 0.9.8.

**Comment by hanna-kn** [comment]
Patch applied (it did not cause any issues on my Linux system).
