### ISSUE TITLE
Bug: Arguments default value can not be set in subfunction

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/qalculate-gtk#301]
While creating a function we can set a default value for x like \x{5}. But when we only use this variable with a subfunction this does not work. The sub-function editor interface does not even allow to type in curly braces.
 To hack around I simply edited the user's functions XML file and replaced \x with \x{5}. Then function works as expected with the default value. That means Libqalculate supports this but GUI does not support it. Now, worst part is even if I simply hit 'save definitions' from File menu,  without doing any editing of the actual function, the default values are removed from XML file. So, now again I have to edit the XML file.

**Comment by hanna-kn** [comment]
Fixed.

**Comment by SubhashBose** [comment]
This issue is not solved in the latest version 3.20.

Although the GUI now allows to enter curly braces { }, but in functions.xml those braces are removed and the variable is changed to lowercase. For example, '\Y{5}' will be saved as '\y' only.
