### ISSUE TITLE
Using plot() in expression textbox causes spawned gnuplot to steal focus in Windows

### ISSUE THREAD

**Issue by CrendKing** [Qalculate/qalculate-gtk#305]
When using the File -> Plot Function/Data, everything works as expected. However, when I try to use `plot(sin(x))`, the moment I type `s`, a gnuplot window spawns, and steals the focus from Qalculate. Even if I switch back, every new character typed causes the focus stealing to happen again. And I don't find an option to turn off this annoying behavior.

Is it possible to change it so that gnuplot only happens when I press Enter?

OS: Window 10. Not sure about other OS.

-----

Orthogonal issue: Just found that `plotsinx` plots the same as `plot(sin(x))`. What the magic?

**Comment by hanna-kn** [comment]
I assume that calculate-as-you-type is activated? If that is the case then you will unfortunately need to deactivate it before using the plot function. This will be fixed in the next version.

**Comment by CrendKing** [comment]
Yes. After turning off, it works fine.

**Comment by hanna-kn** [comment]
> Orthogonal issue: Just found that plotsinx plots the same as plot(sin(x)). What the magic?

The parser is not very strict. It finds the name of the plot function (and plots, plotsi, plotsin, plotsinx are not recognized as the name of any object) and assumes that what comes next is the argument(s) regardless if a parenthesis is found or not. This behaviour can be avoided by activating Mode->Parsing Mode->Limit Implicit Multiplication (which apparently not only affects multiplication).

**Comment by CrendKing** [comment]
I personally don't mind typing that `*`, but it would be nice if only multiplication is specially parsed.
