### ISSUE TITLE
Reopened - Bug: Arguments default value can not be set in subfunction

### ISSUE THREAD

**Issue by SubhashBose** [Qalculate/qalculate-gtk#308]
This is the reopening of previous bug #301 

The issue is not solved in the latest version 3.20.

Although the GUI now allows to enter curly braces { }, in functions.xml those braces are removed and the variable is changed to lowercase. For example, a subfunction '\Y{5}' will be saved as '\y' only. 
Now the issue might be related to libqalculate.

**Comment by hanna-kn** [comment]
Should be fixed in version 3.20.1 (primarily released because of segfault without Gnuplot).

**Comment by SubhashBose** [comment]
Thanks. This works perfect now.
