### ISSUE TITLE
Snap on Wayland: cannot open display: :0

### ISSUE THREAD

**Issue by cioma** [Qalculate/qalculate-gtk#31]
Using v2.2.0 snap package in Ubuntu 17.10 with Wayland gives the following error:
(qalculate-gtk:1883): Gtk-WARNING **: cannot open display: :0

**Comment by cioma** [comment]
But it works if I set WAYLAND_DISPLAY to a bogus value as follows:
`> WAYLAND_DISPLAY=xyz qalculate.gtk`

**Comment by hanna-kn** [comment]
Fixed. 
An update snap package (2.2.0a), which sets the DISABLE_WAYLAND environment variable, has been released.

**Comment by cioma** [comment]
I can confirm it works OK now, many thanks!
