### ISSUE TITLE
Feature request: Drill Bit Size Convertion

### ISSUE THREAD

**Issue by cryptmin** [Qalculate/qalculate-gtk#312]
Requesting drill bit conversion feature. 

Metric/fractional/decimal to SAE (Wire Size, Letter Size, Fractional). Engineering Calculators offer this feature, including other features Qalculate would benefit from, such as speed and feed rates, etc

Great work, absolutely love Qalculate!

**Comment by foreachthing** [comment]
Drill bit conversion: How should that work? For one, there are capital letters (A, B, ..), fractions (7/16, 5/8, ..) and integers (6, 5, 4, ..).

>  I remember the horror when I used to work in the U.S... it was a good time but that imperial stuff - that still gives me the creeps.

And there are already countless (printed) charts for that.
Letter size convert to what? Area, width times length? To DIN size? Again: (online) charts are widely available.

And then: Wire sizes (gauges) are already included. See here:
![image](https://user-images.githubusercontent.com/10420187/128644103-293ab69f-ca0b-40b8-aa99-f962d47afa55.png)

**Comment by hanna-kn** [comment]
It seems as if it should be easy to implement as a function which either returns a length from a letter (character), which can then be converted to either mm or in, or a letter from a length (with optional unit). Conversion between in and mm, fractional and non-fractional does not require any new features.
