### ISSUE TITLE
Portable version for Windows

### ISSUE THREAD

**Issue by cioma** [Qalculate/qalculate-gtk#32]
It would be great to have a portable version of Qalculate for Windows:
- No installation, simply unzip and run
- Settings are saved to the folder with executable and neither Windows registry nor system/user account folders are used

**Comment by smaragdus** [comment]
I second the request for portable version.

**Comment by hanna-kn** [comment]
Please test this "portable" version: 
https://0x0.st/zNXu.zip
(sha256: 7c1d0c7f5361909f77955cdfb21eb965d5820fb1785763ab93263daca28ae88c)

**Comment by smaragdus** [comment]
@hanna-kn 

Thank you for the test build you provided!

I did a brief initial testing and **Qalculate!** version **3.1.0** (**pre**) and it does really have the behaviour of a portable program- all configuration files are saved in **user** sub-folder of the program folder. This is what I needed, indeed.

In fact I have never tested the installer version but the test build seems very powerful and customizable. I may suggest a couple of tiny, cosmetic enhancements.

I am glad you decided to release a portable version of **Qalculate!**- I use almost completely portable programs- they are easy to backup and to transfer from machine to machine with all their settings.

**Comment by cioma** [comment]
Seems to be working fine for me too, many thanks!
