### ISSUE TITLE
Qalculate 3.20.1 in Linux crashing when you try to create a new unit

### ISSUE THREAD

**Issue by SteveH66** [Qalculate/qalculate-gtk#321]
Is anyone else having a problem with Qalculate crashing when you try to create a new unit?  When I click on file->new->unit, Qalculate crashes right away, doesn't give me the create new unit window.  But I can create a new variable clicking file->new->variable, so I am thinking it is a bug with Qalculate and not something wrong with my Linux.  Can anyone else using Linux duplicate this bug?  Thanks

**Comment by SteveH66** [comment]
I downloaded qalculate-3.20.1-x86_64.tar.xz statically linked version again and unzipped it to my /opt/qalculate directory and then ran it again.  It is still crashing on me when I try to make a new unit.  Yes, I am using an older version of Mint which is based on Trusty (an older system I have not upgraded yet).  Did you incorporate the fix into that version? Is there something else I need to download? Do I need to download and install another version instead?  Thank you for for testing this and the fix you did hanna-kn.

**Comment by hanna-kn** [comment]
I've now updated the "self-contained" binaries (https://github.com/Qalculate/qalculate-gtk/releases/download/v3.20.1/qalculate-3.20.1a-x86_64.tar.xz).

**Comment by SteveH66** [comment]
Thank you for taking the time and effort to do that for us hanna-kn,  It seems to be working fine now for creating new units. I appreciate all your hard work on this great calculator and I am sure many many others do as well.
