### ISSUE TITLE
Customise key layout

### ISSUE THREAD

**Issue by goyalyashpal** [Qalculate/qalculate-gtk#325]
### Summary:
Is the function key layout of qalculaor customisable?
- if yes, then how can i do that?
- if no, then can that be implemented?

Similar thing that comes to mind: 
Keyboard layout editor: [site](http://www.keyboard-layout-editor.com) | [gh](https://github.com/ijprest/keyboard-layout-editor)

### Use Case:
Many Computer Based Tests (CBTs) provide online calculator in their exam console. And most all times that calculator is not available anywhere else to get used to it. So, if Qalculate has that capability, that would be a really good point - 'cz qalculate already has the underlying calculation engine, so.... I hope it makes sense.

Qalc (what we have) | Online (customisability goal)
-- | --
![qalc combined QtvapbE8To] | ![image] |
sample text to increase the content of this column so that both images can have roughly equal proportions asdfkjaskdfh sdfkajs dfka sdfkjasdf asdf asldkfj asdflkasdfkjasdfjas

[qalc combined QtvapbE8To]: https://user-images.githubusercontent.com/19423063/133851062-f1c0e8ef-8958-4dad-833e-5bbcd7afcc6c.png
[image]: https://user-images.githubusercontent.com/19423063/133850497-7c6469d6-2ec7-4af4-8828-a831f666c417.png

duplicate search: 🔍 [customize layout](https://github.com/Qalculate/qalculate-gtk/issues?q=is:issue+customize+layout)

**Comment by hanna-kn** [comment]
Only the right-hand side of the keypad can be customized (Edit->Customize Keypad Buttons). The left side can however be hidden and an additional column of buttons can be added (which I however assume is not enough in this case). The size, shape and colour of buttons can not be changed.

The keypad is not the primary way to enter an expression in Qalculate and I imagine that the users access to the full functionality might be problematic in some cases.

**Comment by yashpalgoyal1304** [comment]
> The size, shape and colour of buttons

these are not important either i'd say. if only the key layout (that is functionality wise) can be achieved, that'd be good enough as well.

> an additional column of buttons can be added

how?? ik that left side can be hidden, and that's good too, but can its keys be modified too??

**Comment by hanna-kn** [comment]
> how??

Specify actions for C1-C5 in the keypad customization dialog.

> ik that left side can be hidden, and that's good too, but can its keys be modified too??

Not at the moment. It is complicated by the menu attached to these buttons (the best solution might be to add a separate customizable page, in addition to the programming and general keypads).

The simplest solution to your request would probably be additional customizable buttons on the right side of the keypad.

**Comment by yashpalgoyal1304** [comment]
relevant term: exam mode

source: [GeoGebra Exam Mode](https://wiki.geogebra.org/en/Reference:GeoGebra_Installation#GeoGebra_in_Exams)
