### ISSUE TITLE
Suboptimal complex angle display

### ISSUE THREAD

**Issue by noneistaken** [Qalculate/qalculate-gtk#326]
`120cis(pi/2) to angle` yields `120∠(π ∕ 2)`;
`120cis(pi/3) to angle` yields `60 + √(3)(60∠(π ∕ 2))`.
It's correct, I checked by hand, but I expect it to spit out `120∠(π ∕ 3)` for the second calculation.
Is such an expectation reasonable? Am I even opening this issue on the right repository? If not, my apologies, I'm new to GitHub and I'm merely using the application for doing basic electric/electronics related calculations.

**Comment by noneistaken** [comment]
![Screenshot](https://user-images.githubusercontent.com/90960821/133884133-c9892851-5d0b-4207-a3db-d5feaf4a8de1.png)
Forgot to include a screenshot and to mention I am using Qalculate! GTK+ ver 3.20.1.

**Comment by hanna-kn** [comment]
Fixed (https://github.com/Qalculate/libqalculate/commit/a16c0363964f3e4dfad8d9fb53660adf7fc1f9cb).

**Comment by noneistaken** [comment]
Alright, compiling and `make install`ing from the repository gives me the following, which is way better. `120cis(pi/6)` still gives `120(−1)^(1 ∕ 6)` which again is not wrong, but do you think there should a way to make it display it as `120∠(π ∕ 6)`?
![Screenshot](https://user-images.githubusercontent.com/90960821/133980624-d1d21bfe-5f87-4d9a-86ef-2dcad6da5e9c.png)

**Comment by hanna-kn** [comment]
The complex formats (other than rectangular) have not been optimized for exact mode.

I have now fixed `120cis(pi/6)` (the arg() function has been improved to return the exact value for (-1)^a). `(200cis(−pi/6))/(100+100i−200i)` will now return `√(2)∠−0.75π(1∠((5 ∕ 6)π))`, which is obviously not optimal.

**Comment by noneistaken** [comment]
`(200cis(−pi/6))/(100+100i−200i)` should simplify down to `√(2)∠(pi/12)` IMO.
By the way, is there any documentation on `libqalculate` internals? I know C++, some documentation would be nice for patching it to do what I want to.

**Comment by hanna-kn** [comment]
`(200cis(−pi/6))/(100+100i−200i)` has now also been fixed (by using arg(ab)=arg(a)+arg(b), if a and b are non-zero).

**Comment by noneistaken** [comment]
`(200cis(−pi/3))/(120+120i−240i)` should give `(5sqrt(2)/6)cis(−pi/12)`. (currently giving `(2.5∠−0.25π) ∕ √(6) + (5∠0.25π) ∕ (6 × √(2))`).
Subtracting the expected output from the input (`(200cis(−pi/3))/(120+120i−240i) − ((5sqrt(2)/6)cis(−pi/12))`) gives an equation on Exact mode and `0.00000...∠0.00000...` otherwise. We're really just running in loops trying to simplify down all the possible combinations now, haha.

**Comment by hanna-kn** [comment]
`(200cis(−pi/3))/(120+120i−240i)` now returns `(5∠(−π ∕ 12)) ∕ (3 × √(2))`.

**Comment by noneistaken** [comment]
That's ideal. I would go further as to ask for it to return `(5√(2)/6)∠(−π ∕ 12)`, but considering it simplifies `(5√(2)/6)` to `5 ∕ (√(2) × 3)` that's probably either intended or a separate issue. Closing.

Anyhow, is the code documented or commented in some way? I would like to take a look at the source code and perhaps modify it to my liking somehow.
