### ISSUE TITLE
difference in results with qalc and qalculate

### ISSUE THREAD

**Issue by yashpalgoyal1304** [Qalculate/qalculate-gtk#327]
- on typing the expression: ` 2104*(1500/1560)` , the results are different in qalc and qalculate. 
- i _think_ (i.e. dont remember) i have adjusted the setting in qalculate : 
`Adaptive < Parsing < Mode` 
- but havent touched any setting in qalc.

1. So, how can i adjust the qalc to show same result as qalculate?
2. Also, any way to make the settings between both to sync?

![qalc vs qalculate_r3AtLFNHrN](https://user-images.githubusercontent.com/19423063/135019556-29574871-4bfd-4b22-98b3-294296564aca.png)

**Comment by yashpalgoyal1304** [comment]
https://github.com/Qalculate/qalculate-gtk/issues/154 <--  🔍 [qalc vs qalculate](https://github.com/Qalculate/qalculate-gtk/issues?q=is:issue+qalc%20vs%20qalculate) < duplicate search

**Comment by hanna-kn** [comment]
You have activated octal input base in qalc (hence the zeroes in front of the parsed numbers). Restore decimal number base using `base 10 10`. The expression does not use implicit multiplication (in denominator) and is thus not affected by the parsing mode.

Qalculate does not currently provide any way to synchronize settings between qalc and qalculate-gtk.

**Comment by yashpalgoyal1304** [comment]
> Restore decimal number base using `base 10 10`.

ohww, yeah, it worked 👍 
uhm, it's looking kinda magic. i mean, awesome, glad i asked. would have never been able to figure out myself.

> Qalculate does not currently provide any way to synchronize settings between qalc and qalculate-gtk.

yeah, it seems not so trivial to implement either righttt?

**Comment by yashpalgoyal1304** [comment]
hint for the formatting according to the base:

it matches with how language C formats the output with `#` so, like 
- `%d` gives decimal
- `%#o` gives octal with one leading "0"
- `%#x` gives hexadecimal with one leading "0x"

src: 
> chtp (C How to Program) - 6th
> by Deitel & Deitel
> Ch-9 "C Formatted I/O"
> Art-9.9 "Using flags in printf"
