### ISSUE TITLE
Matrix inverse bug

### ISSUE THREAD

**Issue by jogyg** [Qalculate/qalculate-gtk#337]
Version: 3.21.0   OS: Win-10
Bug-1: inverse exists when det is ZERO.
Qalculate reports inverse of a matrix, whose determinant it report as ZERO.
Details: Matrix is A=[[1, 2, 3], [4, 5, 6], [7, 8, 9]].  Qalculate shows det A=0 (it is correct). But, inv A does not exist as det A=0.  However, Qalculate shows: inv A=[[1, 0.5, 1 ∕ 3], [0.25, 0.2, 1 ∕ 6], [1 ∕ 7, 0.125, 1 ∕ 9]].

Bug-2: A and A-1 does not result in Identity matrix.
Details: A=[[1, 2, 3], [4, 5, 6], [7, 8, 10]] , invA=[[1, 0.5, 1 ∕ 3], [0.25, 0.2, 1 ∕ 6], [1 ∕ 7, 0.125, 0.1]].
A A-1 is not I, instead it gives: [[27 ∕ 14, 1.275, 1], [171 ∕ 28, 3.75, 17 ∕ 6], [72 ∕ 7, 6.225, 14 ∕ 3]]
Reason is that calculated inverse is incorrect. Actual value is:
-2/3	  -4/3	 1
-2/3	11/3	-2
   1	  -2	         1

**Comment by hanna-kn** [comment]
This was caused by confusing function naming. inverse() returns the inverse of a matrix, while inv() actually returned the element-wise reciprocal (equivalent to x.^-1). This has now been fixed.

**Comment by jogyg** [comment]
Thanks a lot. Yes, inverse() gives the correct result.  
I do have another suggestion. When the inverse() of a matrix fails due to ZERO det, the current version does not do anything. Rather, a proper ERROR message with:
opt-1: "inverse does not exist" OR
opt-2: "The determinant is 0, the matrix is not invertible"

**Comment by hanna-kn** [comment]
> I do have another suggestion. When the inverse() of a matrix fails due to ZERO det, the current version does not do anything.

There something wrong if you do not see an error message.

```
> inverse([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

  error: Inverse of singular matrix.
  inverse([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) = inverse([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

```

**Comment by jogyg** [comment]
Oh great! Sorry, I did not notice the Red Color (-) sign on the right side!  It showed correct diagnosis.
 Hanna ji, thanks a lot. You have solved all the issues.  
 
 I do suggest this to my students, as it is one the best available.  Eagerly waiting for the Android version. Hope, someday, it will be available.
 God bless all of you.
