### ISSUE TITLE
RFE: Use short names for magnetic_constant and electric_constant

### ISSUE THREAD

**Issue by genodeftest** [Qalculate/qalculate-gtk#34]
In qalculate's GUI, I'd like to see these suggestions while typing:

1. magnetic_constant: When typing `μ` (the greek letter) or `mu`, please suggest completion to `magnetic_constant`.  Also, it would be nice to call it `vacuum permeability` since that name is more common in some fields.

2. electric_constant: When typing `ε` (the greek letter) or `eps`, please suggest completion to `electric_constant`. Also, it would be nice to call it `vacuum permittivity` since that name is more common in some fields.

**Comment by hanna-kn** [comment]
Done (although the greek letters should have suggested completion to the constants, as μ_0 and ε_0, before).

**Comment by genodeftest** [comment]
Oh, μ_0 and ε_0 is even better, thank you!
