### ISSUE TITLE
Hide the numbers pad in Number Bases window

### ISSUE THREAD

**Issue by yashpalgoyal1304** [Qalculate/qalculate-gtk#342]
* The number input in number bases window takes up so so much of space, and i dont use it either. 
* so, would be nice to be able to disable it similar to how it can be done in main window.
* this number bases windows is accessible on clicking "All" button in top row in main window (in programming keyb mode i guess)

![image](https://user-images.githubusercontent.com/19423063/145414826-e8b72849-929a-4f7c-aead-aef93aeab6e2.png)

might be related: https://github.com/Qalculate/qalculate-gtk/issues/93
issue 🔍 : [hide](https://github.com/Qalculate/qalculate-gtk/issues?q=is%3Aissue+hide)

**Comment by hanna-kn** [comment]
I think it would make more sense to allow hiding the whole keypad.

> this number bases windows is accessible on clicking "All" button in top row in main window

...and a button in the regular keypad, and from the File menu, and using Ctrl+B...

**Comment by yashpalgoyal1304** [comment]
> hiding the whole keypad

yeah, as for that i was thinking smth else. :
* the idea of docks/areas (in blender)/panels
* docks:
    * conversion number fields
    * number pads
* so, the benefit will be that the panels can be deleted, or say that number field can be dropped in the main window itself

But this ofc is a matter of separate issue and is likely way too big of a change, which's why i didnt suggest it before.

**Comment by hanna-kn** [comment]
> > hiding the whole keypad
> 
> yeah, as for that i was thinking smth else. :
> 
>     * the idea of docks/areas (in blender)/panels
> 
>     * docks:
>       
>       * conversion number fields
>       * number pads
> 
>     * so, the benefit will be that the panels can be deleted, or say that number field can be dropped in the main window itself
> 
> 
> But this ofc is a matter of separate issue and is likely way too big of a change, which's why i didnt suggest it before.

That is more along the lines of how the new Qt GUI (https://github.com/Qalculate/qalculate-qt) is designed. It is not very likely that I will make such big changes in the GTK GUI (particularly successful design changes in the Qt GUI might be implemented in the GTK GUI, but I prefer the keep the two GUI:s different).

I would argue that the base conversion dialog is essentially superfluous when the programming keypad is visible.

**Comment by yashpalgoyal1304** [comment]
> I would argue that the base conversion dialog is essentially superfluous when the programming keypad is visible.

yeah, the normal view is that itself. unless one needs to use it. for example:
* i was using it to do an assignment on the conversions to all the basics (2, 8, 10, 16) 
* and it was fine without the conversion dialog as long as the requirement was integral
* but the moment i have to do non-integral parts, it became crucial
* 'cz the default window only shows the integral part (and rightly so imo to keep clutter free)

https://user-images.githubusercontent.com/19423063/145600319-92036360-dfda-4379-b1a7-573fd881aefa.mp4

**Comment by yashpalgoyal1304** [comment]
so umh, which one to use Qalc-gtk or Qalc-qt ? i dont have any preference about the UI toolkit. so, u have any suggestion? or like what are some notable differences?

**Comment by yashpalgoyal1304** [comment]
The qalculate (new) in 3.22.0 has done a fantastic job, awesome. 

oh wait, that's Qalculate QT errrr... i dont remember which variation i downloaded

![vivaldi_t5Resx2nD9](https://user-images.githubusercontent.com/19423063/151673707-d6f32224-5b43-407a-b378-9e2ef8c6c9c1.png)

**Comment by yashpalgoyal1304** [comment]
i used this link for downloading this package:

https://github.com/Qalculate/libqalculate/releases/download/v3.22.0/qalculate-3.22.0-x64.msi

does it include both qt and gtk now??

**Comment by yashpalgoyal1304** [comment]
I think this is available in QT-4.0
https://qalculate.github.io/news.html

![image](https://user-images.githubusercontent.com/19423063/154791471-ed2fdba6-926d-42f5-b1ab-c32d43c55992.png)

**Comment by yashpalgoyal1304** [comment]
> does it include both qt and gtk now??

@hanna-kn does it?

**Comment by hanna-kn** [comment]
> > does it include both qt and gtk now??
> 
> @hanna-kn does it?

Yes, it does ("Qalculate! (new)" = qalculate-qt.exe = Qt GUI, "Qalculate! (classic)" = qalculate.exe = GTK GUI).

**Comment by yashpalgoyal1304** [comment]
ahw, that's nice decision i think, so that user can experience or ratther, so that user gets both at once, and so doesnt have to think additionally. So, making the comparison and eventually the switch is much easier this way. So, like i earlier got stuck at the decision of "oh, so, i'll have to download a separate version of it again" - combining them in a package like this will eliminate that stuck point.
