### ISSUE TITLE
Improper output with quadratic inequalities.

### ISSUE THREAD

**Issue by Zorbatron** [Qalculate/qalculate-gtk#344]
When entering any quadratic and having it be less than or equal to a number, the output looks like this (x^2 - 2x - 15 <= 0)

![qalculate](https://user-images.githubusercontent.com/46525467/146206807-a0350b93-87ef-4670-a972-f8d1f9671814.png)

However, copying the answer does give the correct result of −3 ≤ x ≤ 5. This happens on earlier versions and the latest of the "classic" Qalculate.

**Comment by hanna-kn** [comment]
Fixed.
