### ISSUE TITLE
Feature request: find divisors of a number

### ISSUE THREAD

**Issue by tethragon** [Qalculate/qalculate-gtk#345]
This is a very useful function for elementary school and high school math. Please add it in qalculate app. Thanx.

**Comment by hanna-kn** [comment]
`divisors` function has now been added in libqalculate.

A divisors function can be added to the version 3.22 using the expression `select(genvector("j",1,x/2,1,"j",1),x%"i"=0,"i")` (it will however be highly inefficient for large numbers).

I imagine that in most cases, greatest common divisor and (prime) factors are more useful or close to equivalent.
