### ISSUE TITLE
How do I run Qalculate-GTK/make Qalculate-GTK work?

### ISSUE THREAD

**Issue by aangod** [Qalculate/qalculate-gtk#346]
I am completely dumbfounded looking at the README file of this repository. I am using Mac Catalina and a zsh terminal, and none of the commands work. I was searching all the repositories for at least an application or executable that can work. 

I ask that you can at least give me some advice on how the ever-loving god do I run this UI. Thank you.

**Comment by rickhg12hs** [comment]
I'm on Fedora/Gnome and the app is just a normal app that launches like all the others.  If you run `qalculate-gtk` from the terminal, what happens?

**Comment by jlu5** [comment]
Have you tried the binary packages (MacPorts, Homebrew) listed at https://qalculate.github.io/downloads.html ?

**Comment by aangod** [comment]
@jlu5 I have (on Homebrew), however, there are 3 folders named "qalculate-gtk" and one named "qalculate-gtk-master." None of them have a real application. What do I do with these folders, and how do I get to the calculator part with these folders?

**Comment by aangod** [comment]
Tried the solution @rickhg12hs provided... and whaddya know, it works like magic. Case closed
