### ISSUE TITLE
Graphics glitch in qalculate-gtk history

### ISSUE THREAD

**Issue by Claws81** [Qalculate/qalculate-gtk#35]
Hi

I'm experiencing glitching in qalculate-gtk 2.2.0, but I also had the problem with 2.0.0.

Since video explains it much better than words, I've attached a small clip.
[qalc.zip](https://github.com/Qalculate/qalculate-gtk/files/1634757/qalc.zip)

I've just compiled libqalculate and gtk from the website, so it is the newest.

Let me know how I can help solve it. 

Regards,
Claus

**Comment by hanna-kn** [comment]
Which operating system, gtk version and gtk theme are you using?

**Comment by Claws81** [comment]
Opensuse 42.3, libgtk-2 (2.24.31-14.24), libgtk-3 (3.20.10-9.1) and Breeze theme.

...and now that I checked which theme I use, I changed it from Breeze to Raleigh and the glitching stopped. Funny, because none of the other GTK programs I use from time to time, have any problems.

**Comment by hanna-kn** [comment]
I was able to trace the glitches to the row separators (the breeze theme does not handle them well).

Here is a relevant bug for the breeze theme:
https://bugs.kde.org/show_bug.cgi?id=380291

I you want use the breeze theme I suggest that you modify the source to remove the separators using either [35a.patch](https://gist.githubusercontent.com/hanna-kn/790b3eeba9d0a52c7de4ae9cebc3f2e9/raw/105538974db0e4700c60f92241ecc523f5cda032/35a.patch) or [35b.patch](https://gist.githubusercontent.com/hanna-kn/feae6e0121520cca4fc270aa9bc78c51/raw/6002c3e4aa4e3b2b8ea67a2b449938ca2fb3fe79/35b.patch).

I was not able to reproduce the big ugly equals button issue visible in the your clip.

**Comment by Claws81** [comment]
Thanks for checking it out. I don't really care what theme the gtk programs use, so I'll just avoid Breeze for now.
I haven't actually noticed that the '=' was bigger than the screenshot on the website, but I see it now :)
Thanks, I'll close the issue.
