### ISSUE TITLE
Assertion fail on save to history

### ISSUE THREAD

**Issue by MithicSpirit** [Qalculate/qalculate-gtk#354]
Yet another assertion failed error (like https://github.com/Qalculate/libqalculate/issues/390). This time it occurs on the GTK frontend (haven't tested Qt) whenever it saves to history for whatever reason (hitting `Enter`, pressing the equals button, or having "Add calculate-as-you-type result to history" enabled).
```
/usr/include/c++/11.1.0/bits/basic_string.h:1045: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
```

Reproduction steps:
1. Make sure it is compiled with assertions enabled
2. Open the GTK frontend `qalculate-gtk` (ideally in a terminal/shell so you can see the output)
3. Type literally anything (or even nothing at all!)
4. Hit enter
5. Assertion fails and core gets dumped.

**Comment by hanna-kn** [comment]
Fixed (occurred when history had not been not visible).
