### ISSUE TITLE
Crashing when you type sqrt inside another sqrt

### ISSUE THREAD

**Issue by enricosavegnago** [Qalculate/qalculate-gtk#356]
When you try to type a square root inside another square root (only if before the second sqrt there's a sum), the application crash. 
I'm using Linux.
Qalculate! (GTK)
3.22.0

**Comment by rickhg12hs** [comment]
`1+sqrt(1+sqrt(9))` works normally for version 4.0.0.

**Comment by hanna-kn** [comment]
Fixed.

I assume that calculate-as-you-type is active and that the expression was not completed (e.g. `sqrt(1+sqrt`).
