### ISSUE TITLE
Qalculate unexpectedly quits

### ISSUE THREAD

**Issue by dmlls** [Qalculate/qalculate-gtk#360]
Qalculate unexpectedly quits after certain steps are followed (see below).

- System: Arch Linux with KDE.
- Qalculate version: 4.0.0

**Steps to reproduce**:

1. Introduce `P := [0.9 0.1 0; 0.4 0 0.6; 0 0.2 0.8]` and press Enter.
2. Introduce `pi := [1 0 0]` and press Enter.
3. Introduce `pi × P^2`. After pressing Enter, Qalculate crashes:

```
/usr/include/c++/11.1.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = long unsigned int; _Alloc = std::allocator<long unsigned int>; std::vector<_Tp, _Alloc>::reference = long unsigned int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

**Comment by dmlls** [comment]
I haven't been able to replicate it on macOS.

**Comment by hanna-kn** [comment]
Fixed.

Considering the extensive changes to matrices in version 4.0, I'm not surprised that serious bugs appear.

The reason this occurs on Arch Linux and not other platforms is likely that Arch compiles with -D_GLIBCXX_ASSERTIONS in CXXFLAGS.

**Comment by dmlls** [comment]
Thanks a lot!
