### ISSUE TITLE
Help overlay stays visible after clearing calculation textbox

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/qalculate-gtk#364]
I'm under Windows and have configured the key repetition rate to be as high as possible under the OS's keyboard settings. When I have text in Qalculate's calculation textbox like `2d + 123` and press and hold <kbd>Backspace</kbd>, after everything is deleted, a help overlay stays visible that's almost as big as the the app window with visible history, that has the entries "day d" and "deci d" on top. I have to press <kbd>Esc</kbd> to hide it.

In the Windows keyboard settings dialog (the classic one, second slider), the problem happens more reliably the farther to the right the slider handle is positioned. For high settings, the problem always occurs; for intermediate settings, it sometimes occurs and sometimes doesn't; for low settings, it ceases to occur.

**Comment by hanna-kn** [comment]
Fixed.

I recommend that you use <kbd>Esc</kbd> to clear the textbox instead.
