### ISSUE TITLE
Double-clicking selected history item doesn't insert it

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/qalculate-gtk#367]
- Double-clicking any unselected history item inserts it into the calculation textbox.
- Double-clicking the *selected* history item doesn't insert it, as one would expect, but start in-place editing of the text.

When editing of the selected history entry is desired, a delay of [`GetDoubleClickTime()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdoubleclicktime) milliseconds must be accepted before editing starts, just like when single-clicking a file system object in Windows Explorer to rename it.

Making <kbd>F2</kbd> work to start renaming -- like it is customary in Windows Explorer, Thunderbird, VS Code etc. -- would additionally be a good thing.

**Comment by hanna-kn** [comment]
Fixed.
