### ISSUE TITLE
Typing a date uses Unicode minus symbols

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/qalculate-gtk#368]
- When using "Edit > Insert Date...", a correct ISO 8601 date with hyphens is inserted. Example: "2022-02-28"
- When trying to type the same, the following odd-looking text is created: "2022−02−28"

Both methods should result in the same date text with hyphens.

Perhaps, a similar approach to clipboard text transformation when pasting as discussed in https://github.com/Qalculate/qalculate-gtk/issues/361 would work? First, text -- at least date text -- in quotes must be defined as not getting its hyphens made into Unicode minus symbols (also not when pasting). When typing, text from unbalanced " to cursor position isn't transformed. When a balancing " is typed, the whole calculation text is transformed (and, of course, the cursor and scroll position restored, if necessary). You'd also need to handle removal of ".

**Comment by hanna-kn** [comment]
Fixed. I will not complicate things by replacing operators after removal quotation marks.
