### ISSUE TITLE
Right history buttons add new history entries

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/qalculate-gtk#369]
I turned the following setting off: "Add calculate-as-you-type result to history". History is always visible. When I click on one of the buttons vertically stacked on the right side of the history, as long as enough values for the operation are selected, a new history item for the corresponding calculation is added to the history right away. I find this to be unexpected and history-polluting.

If you plan to add a new setting for this, I think a new "History" settings category would be justified -- possibly even now. The history-related settings should definitively be grouped together with "Clear history on exit" being at the end of the group.

**Comment by hanna-kn** [comment]
Fixed (do not add directly to history if calculate-as-you-type is enabled).
