### ISSUE TITLE
Favor narrow no-break spaces over thin spaces

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/qalculate-gtk#370]
Currently, Qalculate uses thin spaces (U+2009) as digit separators. However, these spaces break at the end of the line; in LibreOffice Writer:

![LibreOffice Writer](https://user-images.githubusercontent.com/13482553/155907732-1eaf87f4-f058-4085-8c3f-7cd810406114.png)

This is even in contrast to how other digit separators behave that you get with other Qalculate settings:

![LibreOffice Writer](https://user-images.githubusercontent.com/13482553/155908041-988f262f-f7ff-4bd5-a415-f681760379f8.png)

Qalculate should use narrow no-break spaces instead (U+202F, [Wikipedia](https://en.wikipedia.org/wiki/Non-breaking_space#Width_variation), [Wikipedia](https://en.wikipedia.org/wiki/Thin_space)). This type of space can also be added with LibreOffice Writer under "Insert > Formatting Mark > [...]". As you can see, it behaves properly:

![LibreOffice Writer](https://user-images.githubusercontent.com/13482553/155908835-9c221ff5-9e77-478e-a42c-59cd2052271d.png)

One could only argue to use breakable thin spaces *after* the decimal separator, so that something like this doesn't happen:

![LibreOffice Writer](https://user-images.githubusercontent.com/13482553/155909144-00480e33-9f74-4d8a-b6da-89626721be99.png)

If Qalculate ever produces other visible digit separators than spaces after the decimal separator (like `,` or `.`), there are zero-width Unicode characters that specifically allow breaking at that point. I'd guess breaking *after* the digit separator instead of *before* would be preferred, just like with word hyphenation where the hyphen is at the end of the line.

---

Also, in German, a narrow space as opposed to a regular-width space between number and unit is preferred, specifically a non-breaking one (see [big table, 6th row](https://de.wikipedia.org/wiki/Schmales_Leerzeichen#Verwendung); "¦" represents NNBSP; try selecting text node, then `$0.nodeValue.charCodeAt(3).toString(16)` in dev console). Other languages will at least prefer a regular-width no-break space (U+00A0). Qalculate currently uses a regular space, which can lead to number&ndash;unit separation.

**Comment by hanna-kn** [comment]
> One could only argue to use breakable thin spaces after the decimal separator, so that something like this doesn't happen

The same can occur with very large numbers. My solution to this would be to use breakable thin space for very long numbers (with many digits before or after the decimal separator). The problem is that the width of a line is normally very different between a text document and a calculator window (this is not an issue in qalculate-gtk, where line-breaks are added manually, but it is in qalculate-qt).

Another potential issue is that NNBSP does not necessarily have the same width as narrow space.

> Also, in German, a narrow space as opposed to a regular-width space between number and unit is preferred, specifically a non-breaking one (see [big table, 6th row](https://de.wikipedia.org/wiki/Schmales_Leerzeichen#Verwendung); "¦" represents NNBSP; try selecting text node, then $0.nodeValue.charCodeAt(3).toString(16) in dev console).

I'm unable to find any other reliable sources for the correct width of the space between quantity and unit.

**Comment by h-h-h-h** [comment]
> The same can occur with very large numbers. My solution to this would be to use breakable thin space for very long numbers (with many digits before or after the decimal separator). The problem is that the width of a line is normally very different between a text document and a calculator window (this is not an issue in qalculate-gtk, where line-breaks are added manually, but it is in qalculate-qt).

That sounds like dangerous guesswork about the right threshold. Don't you think it matters that a number in a document can start at *any* horizontal position on a line? I think breaking decimal places generally doesn't create an issue with readability. But perhaps we should leave numbers with many pre-decimal-separator digits, which I think is a rare case, to manual typesetting (at least until someone with such a use case comes by and tells us their thoughts on the topic).

> Another potential issue is that NNBSP does not necessarily have the same width as narrow space.

If we want something non-breaking and narrow, this is our only hope. If necessary, we could compare the 2 characters for various fonts, but from my current experience, NNBSP and thin space are similar enough. They already seem to be used and recommended quite interchangeably.

> I'm unable to find any other reliable sources for the correct width of the space between quantity and unit.

For what language? German? English?

**Comment by hanna-kn** [comment]
Done.

NNBSP are now used for numbers with no more than 20 digits (quite arbitrary).

> For what language? German? English?

Any language that I understand...
I prefer to use international standards, and do not want to implement different spacing for different locales (unless defined in lconv). I primarily use the documents from BIPM (https://www.bipm.org/en/publications/si-brochure), but preferred width of spaces and use of non-breaking space are not mentioned.

**Comment by h-h-h-h** [comment]
Internet discussions confirm that, in the context of SI, there is no explicit recommendation that a narrow space should be used. It's just mentioned that a space must be used, as opposed to no space (one can argue that "space" doesn't define the width in any way).

Regarding German: Typographers are of different opinion whether a normal or a narrow space should be used. Using a narrow space is not a minority opinion among experts. They seem to agree, however, that a non-breaking space should be used.

Regarding English: Alledgedly, Americans have a bad habit of not using a space at all, which will be one reason why SI mentions that a space *must* be used. Using a narrow space would be an averaging solution and accommodate the "opinion" behind the tendency of not using a space. ["You can use either of U+202F NARROW NO-BREAK SPACE or just plain U+00A0 NO-BREAK SPACE, but you certainly should not let it risk being line-broken. I’m not so sure that the thinness matters half so much as the no-break property. You do not want to let the figures get orphaned without their units."](https://english.stackexchange.com/a/105557/296389) Among typography enthusiasts, the opinion whether the space should be narrow or not also doesn't seem to clearly go into one direction.

So, while I, from a German perspective, would advocate for a narrow space between number and unit, the consensus is to definitively use a non-breaking space, even if official SI info doesn't mention it, so that this doesn't happen:

![LibreOffice Writer](https://user-images.githubusercontent.com/13482553/156086999-857a895c-2ff9-4641-9a64-6f9bc735a835.png)

**Comment by hanna-kn** [comment]
> Just referring to digits before the decimal separator? Do you distinguish between before and after?

Referring to total digits before and after decimal separator.
