### ISSUE TITLE
Changing a calculation can result in unit error

### ISSUE THREAD

**Issue by h4ckerle** [Qalculate/qalculate-gtk#372]
### Step to reproduce

1. Enter a calculation returning a value with a unit
![image](https://user-images.githubusercontent.com/76652420/156792404-ea0e4a7c-3bbf-4630-ba96-9aa79267cde2.png)
2. Change that term to show in a different value
![image](https://user-images.githubusercontent.com/76652420/156792663-9ed4bbbf-08cf-4be5-897b-b5ec6b178b3f.png)
3. Append a Term which should cancel out that term

### What should happen?
No Unit is shown

### What is happening instead?
The Unit previously used is shown
![image](https://user-images.githubusercontent.com/76652420/156793359-64412cee-daaa-4e21-acbc-24cc17ffa297.png)

**Comment by hanna-kn** [comment]
This is caused by a coding error triggered by the fact that continuous conversion to gram is activated and that the result contains no unit (5 is multiplied by the SI base unit kg to enable conversion to g).

**Comment by hanna-kn** [comment]
Fixed (in libqalculate).

**Comment by h4ckerle** [comment]
Thanks for the quick fix, and also thank you for maintaining this tool, which is very valuable to me in my physics classes!
