### ISSUE TITLE
Update of Exchange Rates

### ISSUE THREAD

**Issue by frameworkplus** [Qalculate/qalculate-gtk#377]
Good day,
Updates of exchange rates failing
Running Qalculate! (GTK) 4.0.0 on Linux Ubuntu 21.10

![Screenshot from 2022-03-11 08-47-23](https://user-images.githubusercontent.com/101386539/157818537-1af30c0f-81e7-4497-af75-4e5906700fca.png)

Thank you
Eben

**Comment by hanna-kn** [comment]
Duplicate of https://github.com/Qalculate/qalculate-gtk/issues/349 (see https://github.com/Qalculate/qalculate-gtk/issues/349#issuecomment-1059117686)

**Comment by hanna-kn** [comment]
See https://github.com/Qalculate/qalculate-gtk/issues/349#issuecomment-1059117686

**Comment by kindle939393** [comment]
Why I still failed
