### ISSUE TITLE
Limit 'y' range for plotting

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/qalculate-gtk#38]
Currently plotting functions like 1/x, arcsin, arccos or tg causes plot to be stretched vertically , to fit in square window.

**Comment by hanna-kn** [comment]
You can zoom in part of the plot using the right pointer button to select an area. This might however been difficult to discover, and I will consider adding y main/max to the plot dialog.

The main issue here is however the handling of functions that in reality are discontinuous (such as 1/x and tangent). If zero is not included among the x values 1/x will clearly give an incorrect continuous plot (where 1/0=0). I do however think that I have now come up with an adequate solution (not yet implemented).

This should not be an issue with asin (y range pi/2...-pi/2) or acos (y range 0...pi).

**Comment by hanna-kn** [comment]
Y min/max has now been added to plot dialog.

**Comment by hanna-kn** [comment]
Enhanced handling of discontinuous functions has now been implemented.

**Comment by nick87720z** [comment]
Thanks, i got it).
