### ISSUE TITLE
Easier history search

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/qalculate-gtk#383]
When the history is focused and Ctrl+F isn't assigned otherwise, it would be great if Ctrl+F would do the same as the "Search..." context menu item: showing the search dialog.

Furthermore, the search should be performed case-insensitively. If necessary, add a "Case-Sensitive" or "Match Case" checkbox that isn't forgettable.

(And the label "Text" should end in a colon or be omitted altogether.)

**Comment by hanna-kn** [comment]
Ctrl+F is assigned to the open functions by default, and it is possible for the user to specify a keyboard shortcut for history search.

I've now made the search case-insensitive.

> (And the label "Text" should end in a colon or be omitted altogether.)

I've now removed the label and added an icon inside the text field. (Colon is generally not used in Gnome/GTK applications.)
