### ISSUE TITLE
Qalculate-gtk crashes when opening

### ISSUE THREAD

**Issue by lr-tech** [Qalculate/qalculate-gtk#387]
When I start qalculate-gtk it opens for a second and automatically closes (doesn't allow typing). Here is the terminal output:
```
(qalculate-gtk:18292): Gdk-CRITICAL **: 02:48:09.420: gdk_window_begin_draw_frame: assertion 'GDK_IS_WINDOW (window)' failed
(qalculate-gtk:18292): Gdk-CRITICAL **: 02:48:09.420: gdk_drawing_context_get_cairo_context: assertion 'GDK_IS_DRAWING_CONTEXT (context)' failed
Segmentation fault (core dumped)
```

**Comment by hanna-kn** [comment]
Which version are you using (version number, package, and operating system/distribution)?

**Comment by lr-tech** [comment]
Arch Linux (Kernel 5.16.14-arch1-1)
qalculate-gtk 4.1.0 (from Arch repo. I also tested git version from AUR, but I got the same error)
gtk3 version 3.24.33-1

**Comment by hanna-kn** [comment]
Presumably this occurs because the result widget has not been realized before trying to draw on it. I've however not been able to reproduce the issue (in Arch Linux). The issue should be fixed now.

You should be able avoid the segfault by providing an expression on the command line once.

**Comment by lr-tech** [comment]
It worked by running `qalculate-gtk -n`. Thank you very much! I really love this app and I've been using it for 2 years now.
