### ISSUE TITLE
Prevented history duplicates lead to extra separator lines

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/qalculate-gtk#388]
In the context of issue #362, you implemented prevention of history duplicates in succession. However, the number of times I press Enter is now the number of separator lines between history entries:

![Qalculate!](https://user-images.githubusercontent.com/13482553/159115520-22b9e4ba-ce36-4b23-8eee-305acb477fa6.png)

**Comment by hanna-kn** [comment]
Fixed.
