### ISSUE TITLE
Empty history entry created

### ISSUE THREAD

**Issue by h-h-h-h** [Qalculate/qalculate-gtk#394]
When the calculation textbox is empty and I press Enter, an empty history entry with result `0` is created. Since this cannot be useful, I suggest to prevent such a history entry. The result field showing `= 0` is fine. (Don't forget to also prevent the separator. 😉)

**Comment by hanna-kn** [comment]
Fixed (Enter now does nothing if expression is empty).

**Comment by h-h-h-h** [comment]
If you mean it doesn't even make the result display show `= 0`, then the result display also shouldn't show `= 0 [unit]` when you use the conversion section in one of the following ways:

- Click a list item (a unit).
- Type a unit in the textbox and press the "Convert" button.

**Comment by hanna-kn** [comment]
> If you mean it doesn't even make the result display show = 0, then the result display also shouldn't show = 0 [unit] when you use the conversion section in one of the following ways

Now also fixed.
