### ISSUE TITLE
Non-alpha units detection problem

### ISSUE THREAD

**Issue by jurov** [Qalculate/qalculate-gtk#4]
When I try to convert between °C and °F units get wrongly detected as coulomb/farad. 

Can this be fixed so that it can also support feet/inch notation like 6' + 1" ?

**Comment by hanna-kn** [comment]
The issue with temperature units has now been fixed (the degree sign was wrongly used for superscript zero which caused a conflict). 

If you do not use the development version of libqalculate, you can use oC, ℃, celcius, centigrades, etc... (and similarly for Fahrenheit) instead while waiting for a new version to be released.

Using ' and " for feet/inch conflicts with their current usage as quotation marks in Qalculate!.

**Comment by jurov** [comment]
Thanks for the answer.
