### ISSUE TITLE
Feature request: LCM and GCD with more than 2 arguments

### ISSUE THREAD

**Issue by tethragon** [Qalculate/qalculate-gtk#401]
Hi.

I know that is possible to calculate LCM and GCD with more than 2 arguments, using nested LCM and GCD.
(i.e. for calculating the LCM of the numbers 125,50,30 you type LCM(125,LCM(50,30))

Since the functionality is there, I propose you make LCM and GCD accept more arguments than 2. It would be a great help for primary and secondary education teachers and pupils. I believe it would be great to be able to type LCM (125,50,30) and get the result.

Thanx for your great work!

**Comment by hanna-kn** [comment]
Done.
