### ISSUE TITLE
Feature request: Make it possible to cycle between the autocomplete items in the popup menu with tab

### ISSUE THREAD

**Issue by isak102** [Qalculate/qalculate-gtk#407]
I am very used to cycling the autocomplete items by pressing Tab in code editors like Vim and VSCode, adding this option to Qalculate would help me alot and I assume many other people aswell who are used to this behaviour when programming

**Comment by hanna-kn** [comment]
I've now implemented a variant of this (I do not know exactly what you expect; I had a look at Vim and VSCode, but neither exhibited any such behaviour by default).

As before, if tab is pressed when the completion list is visible the first, or selected, item will be activated (and the list hidden). Subsequent tab key presses will however cycle through the completion items (in the now hidden list, using inline completion).

By default, tab will now also show the completion list if autocompletion is disabled or delayed.

**Comment by isak102** [comment]
> I've now implemented a variant of this (I do not know exactly what you expect; I had a look at Vim and VSCode, but neither exhibited any such behaviour by default).
> 
> As before, if tab is pressed when the completion list is visible the first, or selected, item will be activated (and the list hidden). Subsequent tab key presses will however cycle through the completion items (in the now hidden list, using inline completion).
> 
> By default, tab will now also show the completion list if autocompletion is disabled or delayed.

That was quick! This is sort of what I meant, but not completely

If the keybind to select the first entry has been changed to something else than tab, It would be great to have the autocomplete menu be kept open when you press tab, essentially making the tab (and shift+tab) keypresses behave exactly like the up and down arrows. And then once you are hovering over the item you want, you can press enter to select it.

**Comment by hanna-kn** [comment]
> If the keybind to select the first entry has been changed to something else than tab, It would be great to have the autocomplete menu be kept open when you press tab, essentially making the tab (and shift+tab) keypresses behave exactly like the up and down arrows. And then once you are hovering over the item you want, you can press enter to select it.

Done. (That was considerable simpler to implement.)

**Comment by isak102** [comment]
> > If the keybind to select the first entry has been changed to something else than tab, It would be great to have the autocomplete menu be kept open when you press tab, essentially making the tab (and shift+tab) keypresses behave exactly like the up and down arrows. And then once you are hovering over the item you want, you can press enter to select it.
> 
> Done. (That was considerable simpler to implement.)

Sounds promising!

However I can't test it becuase I get this output after running `make`:
```
make  all-recursive
make[1]: Entering directory '/home/isak102/Code/repos/qalculate-gtk'
Making all in data
make[2]: Entering directory '/home/isak102/Code/repos/qalculate-gtk/data'
Makefile:832: *** missing separator.  Stop.
make[2]: Leaving directory '/home/isak102/Code/repos/qalculate-gtk/data'
make[1]: *** [Makefile:437: all-recursive] Error 1
make[1]: Leaving directory '/home/isak102/Code/repos/qalculate-gtk'
make: *** [Makefile:369: all] Error 2
```
I have ran `./autogen.sh` and then `./configure` before running `make`. It is possible that I am missing something very simple
