### ISSUE TITLE
differential equations that are not solved

### ISSUE THREAD

**Issue by pawn2** [Qalculate/qalculate-gtk#410]
I have noticed that some differential equations the calculator cant solve them,even if they are very simple.For example :dsolve(x(diff(y,x))^2−2x=x^4, 5, 1).Even when i eliminate the x from both parts of the equation it couldnt solve it,which is strange because the equation is simple.

**Comment by hanna-kn** [comment]
What solution do you expect? The solutions returned by other calculators I've tried include the hypergeometric function (not supported by Qalculate) or an uncalculated integral.

**Comment by pawn2** [comment]
my mistake i confused the equation sorry
