### ISSUE TITLE
Selection replacement/enclosing behavior

### ISSUE THREAD

**Issue by formicant** [Qalculate/qalculate-gtk#414]
I believe, when selecting a part of expression which is not a valid expression itself, more natural behavior is to just replace the text rather than enclosing it in parentheses.

## How to reproduce

Type `2*3`. Then, select `*` and press `/`.

Expected input text:
`2/3`

Actual input text:
`2(*)/3`

(version 4.2.0, Windows)

(the qt app has the same issue: https://github.com/Qalculate/qalculate-qt/issues/46)

**Comment by hanna-kn** [comment]
Fixed.
