### ISSUE TITLE
Use default gnuplot style or allow to configure it, instead of hardcoded style settings.

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/qalculate-gtk#42]
I compared lines look in qalculate-gtk plot with raw gnuplot. Difference appears both for wxt and qt.
In raw gnuplot, by default, lines have width=1, and when zoomed out, don't lose quality. But in qalculate-gtk lines are initially thicker - nearly 2 pix. When zoomed out, some aliasing appears, and visually line begin to seem thicker, if not really. It is obvious, that there is different style. But when i tried to tune styles in gnuplot, "$ set style line 1 linewidth 3.0 pointsize 3.0 color '#444444' " did not work, so i don't know, how to reproduce it. However, i can ran "test" to see current style, and i can say, it is better.

As variant, there may be universal way to setup gnuplot not only for look, by running custom gnuplot commands, for experts.

**Comment by nick87720z** [comment]
Screenshots from pure gnuplot, samples=10000
![screen_2018-01-22_04-19-32](https://user-images.githubusercontent.com/3896190/35200199-82169428-ff2b-11e7-968f-3f3c089bd477.png)
![screen_2018-01-22_04-20-59](https://user-images.githubusercontent.com/3896190/35200215-d487667e-ff2b-11e7-8da5-50075918b8cf.png)
Same with qalculate-gtk
![screen_2018-01-22_04-24-21](https://user-images.githubusercontent.com/3896190/35200227-3145ad3a-ff2c-11e7-91f1-9af1ccfc1b5a.png)
![screen_2018-01-22_04-25-57](https://user-images.githubusercontent.com/3896190/35200240-613478c8-ff2c-11e7-8a0d-1e3bebcbe496.png)

**Comment by hanna-kn** [comment]
Line width is now configurable (default line width is 2).
