### ISSUE TITLE
Can't solve simple equation?

### ISSUE THREAD

**Issue by LSAXYZ321** [Qalculate/qalculate-gtk#422]
I tried to solve the following simple equation via Qalculate v 4.2.0

4^x+6^x-9^x=0
The result as Qal shows it ...
6^(x) - 9^(x) + 4^(x) = 0
, tried different modes without luck

I'm puzzled, why it can't find the value of x, which should be
x = 1,1868144

**Comment by rickhg12hs** [comment]
FYI, both `newtonsolve` and `secantsolve` find a good approximation.

**Comment by hanna-kn** [comment]
Fixed in libqalculate (https://github.com/Qalculate/libqalculate/commit/9e9cf000212db165689beeb88daf9da10d0b1813).

Qalculate will first try to find an exact solution, dividing by one of the terms. If no exact solution is found, Newton's method is used. This only works if _x_ is assumed real.

**Comment by LSAXYZ321** [comment]
Thanks for your answers :-)
Ps: Haven't noticed newtonsolve etc., interesting, will look into that
