### ISSUE TITLE
Feature request: set notation

### ISSUE THREAD

**Issue by Gamingzone123** [Qalculate/qalculate-gtk#426]
it would be nice to be able to use set notation, it would also make the program far more versatile and powerful

some example uses:

finding the expected value of a large probability distribution
i.e. you have a probability distribution of for instance expected value of the sum of the numbers rolled on two dice, as the formula is the sum of all possible outcomes multiplied by their respective probabilities you would have to input: 2* 1/36 + 3* 2/36 + 4* 3/36 + 5* 4/36 + 6* 5/36 + 7* 6/36 + 8* 5/36 + 9* 4/36 + 10* 3/36 + 11* 2/36 + 12* 1/36 to get 7, whereas with function notation you could do {2,3,4,5,6,7,8,9,10,11,12} * {1/36,2/36,3/36,4/36,5/36,6/36,5/36,4/36,3/36,2/36,1/36} to get the same result, you can already do this with the mean() and total() functions

multiplying sets of numbers where numbers are multiplied with their corresponding partner;
i.e. {1,2,3} * {3,2,1} = {3,4,3}

finding the sum of a set;
i.e. total({1,2,3}) = 6

having the "for()" function output to a set;
i.e. for(0,x,x<6,x+1,1,randbetween(1,20),y) would output something like y={12,3,17,8,2} or some other randomised set of 5 numbers between 1 and 20

there will be far more uses that i haven't listed

please consider adding this
thanks

**Comment by hanna-kn** [comment]
Try with parentheses or square brackets instead curly brackets, and use element-wise operators for multiplication, division, and exponentiation (`.*`, `./`, and `.^`, with a dot in front of the standard operator). If square brackets are used, comma can be replaced by space.

`(1,2,3).*(3,2,1) = [3  4  3]`
`total([1 2 3]) = 6`

`randbetween` (and other functions for random number) supports a third argument for specifying the number of values:
`randbetween(1, 20, 5) = [5  11  2  16  14]`

There are functions for manipulation of these kinds of sets (called vectors in Qalculate) in the Matrices & Vectors category.

**Comment by hanna-kn** [comment]
v4.4.0 supports use of curly brackets instead of parentheses, thus `total({1,2,3})` will now work as expected, but use of element-wise operators are still required.
