### ISSUE TITLE
Qalculate GTK doesn't always copy the results to clipboard 2

### ISSUE THREAD

**Issue by shocoman** [Qalculate/qalculate-gtk#429]
Hello. I'm having the exact same problem that was described and fixed in the issue #348.
By git-bisect'ing I found that the bug was reintroduced in [this commit](https://github.com/Qalculate/qalculate-gtk/commit/3bda98e45043f6494ca312da8696651df57cbfda#diff-bb1b0af870ecaff716968a3feb4987fd6d31296a2d832c0e390979dabab3b0afL30288)
Also, setting the "Delay" property in the Preferences to 0 seconds solves the problem

**Comment by hanna-kn** [comment]
I assume that automatic adding of result to history is not disabled when the bug occurs as was the case in the previous issue.

Should be fixed now.

**Comment by shocoman** [comment]
Thanks, it works now
