### ISSUE TITLE
`SIGSEGV` in `AliasUnit_Composite::AliasUnit_Composite(Unit*, int, Prefix*)`

### ISSUE THREAD

**Issue by AuroransSolis** [Qalculate/qalculate-gtk#430]
Not entirely sure why, but for the past few versions of `qalculate-gtk` it's always segfaulted on opening. Thought to run it through LLDB this time and this was the output:
```
(lldb) target create "qalculate-gtk"
Current executable set to 'qalculate-gtk' (x86_64).
(lldb) run
Process 19276 launched: '/usr/local/bin/qalculate-gtk' (x86_64)
Process 19276 stopped and restarted: thread 1 received signal: SIGCHLD
Process 19276 stopped
* thread #1, name = 'qalculate-gtk', stop reason = signal SIGSEGV: invalid address (fault address: 0x1)
    frame #0: 0x00007ffff6ceb85e libqalculate.so.21`AliasUnit_Composite::AliasUnit_Composite(Unit*, int, Prefix*) + 222
libqalculate.so.21`AliasUnit_Composite::AliasUnit_Composite:
->  0x7ffff6ceb85e <+222>: movq   (%rsi), %rax
    0x7ffff6ceb861 <+225>: callq  *0x30(%rax)
    0x7ffff6ceb864 <+228>: leaq   -0xf0(%rbp), %rcx
    0x7ffff6ceb86b <+235>: movq   %rcx, -0x100(%rbp)
```
I'm not particularly experienced with debugging C++, so if there's a recommended process/toolset for learning more about the segfault I'd appreciate hearing about it.

`qalculate-gtk` version 4.3.0 was compiled through Gentoo package installation with `COMMON_FLAGS="-O2 -pipe -march=native -mtune=native"`, and `CFLAGS`, `CXXFLAGS`, `FCFLAGS`, and `FFLAGS` are all copies of that. If it at all makes a difference, I also have `MAKEOPTS="-j12 -l12"`.

**Comment by hanna-kn** [comment]
Are you able to run `qalc` without segfault?

Does it work if you reset settings and/or user data (remove `~/.config/qalculate/qalculate-gtk.cfg` and `~/.local/share/qalculate/`, or set the environment variable `QALCULATE_USER_DIR`)?

You should get more informative debug output if you compile libqalculate and qalculate-gtk with debugging enabled in `CXXFLAGS` (e.g. `COMMON_FLAGS="-g -Wall`).

**Comment by AuroransSolis** [comment]
Thanks for the fast response (and sorry for my slow response to that)! Here's some answers:
1. Yes, I can run `qalc` without segfaulting.
2. Nope, I just did `rm ~/.config/qalculate/qalculate-gtk.cfg` and `rm -r ~/.local/share/qalculate/`, and it still segfaults.
3. Adding `-g -Wall` didn't really seem to change the debug output very much. I'll try cloning this and building it myself with hopefully the same options as Gentoo does and see if I can figure out what's going on.

**Comment by AuroransSolis** [comment]
Hmm, might be something wrong with the Gentoo ebuild. I built it manually and it seems to work fine.

**Comment by hanna-kn** [comment]
I tried qalculate-gtk (v4.3.0) ebuild on Gentoo (in virtualbox) and it ran without any apparent issues.

**Comment by AuroransSolis** [comment]
That's interesting. I wonder why that's happening. I tried running it through gdb-dashboard as well to see if I could get the source to display while it was running, but nope:
![image](https://user-images.githubusercontent.com/25749440/189786713-31b47ff3-1c52-433f-8491-87f8c5c856e5.png)
I made sure that both `libqalculate` and `qalculate-gtk` were compiled with `COMMON_FLAGS="-O0 -pipe -march=native -mtune=native -g -Wall"`. To get the `gdb` output I got the dashboard and then just did `gdb qalculate-gtk`, then `start`, then `ni` until the segfault hit.

**Comment by hanna-kn** [comment]
By default Portage strips binaries and this removes debug information. Add _nosplit_ or _splitdebug_ to FEATURES to avoid this. `-Og -ggdb` is recommended instead of `-O0 -g`. For more details see https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Backtraces.

**Comment by hanna-kn** [comment]
The gdb output is confusing. `CompositeUnit::add(Unit*, int, Prefix*)` is never called directly from `update_completion()`. During the launch of qalculate-gtk, `AliasUnit_Composite::AliasUnit_Composite(Unit*, int, Prefix*)` is only called when loading the definitions files, before `create_menus_etc(void*)` and `update_completion()`, using the same functions as qalc.

I found a potential culprit in `CompositeUnit::setBaseExpression(string)` which calls `CompositeUnit::add(Unit*, int, Prefix*)`. 
`for(size_t i2 = 0; i2 < mstruct.size(); i2++) {` at line 1265 in libqalculate/Unit.cc should be replaced with
`for(size_t i2 = 0; i2 < mstruct[i].size(); i2++) {`
It seems however impossible to reach this statement.

**Comment by AuroransSolis** [comment]
Cheers for the help - I haven't ever had to debug C++ binaries before, much less ones built by a system that's not more directly under my control. I'll rebuild the packages with those flags later today and run it through GDB again. Hopefully something interesting will pop up.

**Comment by AuroransSolis** [comment]
Oops, kinda forgot about this. Something at Some Point™ changed and now everything seems to work fine again, so I'll close this issue.
