### ISSUE TITLE
armhf and arm64 builds?

### ISSUE THREAD

**Issue by avoidik** [Qalculate/qalculate-gtk#436]
hello,

would you please consider adding armhf and arm64 builds? just for the reference how I built it on debian-bullseye-aarch64

```bash
sudo apt-get install -y build-essential intltool libcurl4-openssl-dev libgtk-3-dev libxml2-dev
git clone https://github.com/Qalculate/libqalculate
cd libqalculate/
git checkout tags/v4.4.0
./autogen.sh
./configure --prefix=/opt/libqalculate
make
sudo make install
```

```bash
export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/opt/libqalculate/lib/pkgconfig"
git clone https://github.com/Qalculate/qalculate-gtk
cd qalculate-gtk/
git checkout tags/v4.4.0
./autogen.sh
./configure --prefix=/opt/qalculate-gtk
make
sudo make install
sudo ln -s /opt/qalculate-gtk/bin/qalculate-gtk /usr/local/bin/qalculate-gtk
```

**Comment by hanna-kn** [comment]
There are ARM builds for the flatpak (arm64) and snap packages (arm64 and armhf), in addition to any packages provided by distributions.

I do not think that it would be worth the effort to provide additional builds for the self-contained binaries (built locally).

I have not investigated the feasibility of cross-compiling Qalculate for ARM architectures on Windows.

**Comment by avoidik** [comment]
I was wondering about traditional deb packages, if it's still no, then just close it

**Comment by hanna-kn** [comment]
> I was wondering about traditional deb packages, there is no such option in Makefiles, if it's still no, then just close it

I do not provide any distribution specific packages. For those who wish to use a newer version than the one available in the repository of their distribution, I primarily recommend the Flatpak package.
