### ISSUE TITLE
Hint - libqalculate.so.22

### ISSUE THREAD

**Issue by bsbhro** [Qalculate/qalculate-gtk#438]
I had an older libqalculate installed. After I reinstalled this library from source, the newly created qalculate-gtk was missing libqalculate.so.22 . I found it as a fresh symbolic link in /usr/local/lib, but I had to create a link in /usr/lib/x86_64-linux-gnu. That's how qalculate-gtk found it.

**Comment by mrumyantsev** [comment]
Thank you for an advice! But, I was just copied both link files: libqalculate.so libqalculate.so.23 from /usr/local/lib to /usr/lib and that's helped me.
