### ISSUE TITLE
Customize Keypad Buttons display empty window

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/qalculate-gtk#445]
step:
1.Edit>Customize Keypad Buttons>close window
2.Edit>Keyboard Shortcut>close window
3.Edit>Customize Keypad Buttons

It display an empty window.

qalculate display following error message in terminal.
(qalculate:9093): Gtk-CRITICAL **: 23:02:33.484: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

**Comment by hanna-kn** [comment]
Fixed (the window was destroyed instead of only hidden, after closing the window not using the close button).
