### ISSUE TITLE
randuniform, command fail

### ISSUE THREAD

**Issue by LaszloHars** [Qalculate/qalculate-gtk#446]
Qalculate 4.4.0 under Windows 10 - 64.
(1) randuniform(−1,6,2) returns two numbers between 6 and 7... In general, the parameters mean something different than lower and upper limits, what the Help tells.
(2) command("dir") goes awry. The string "dir" is parsed as an expression, instead of a text string, and no external command was executed. Other string parameters produce errors,  "failed to run external command ....".

**Comment by LaszloHars** [comment]
...it looks like the first parameter of randuniform() is the length of the interval, from where the random numbers are taken, and the second parameter is the upper end of this interval. Unfortunately, the error check prevents the workaround of randuniform(7,6), which otherwise would have the effect of the desired randuniform(−1,6). I have to use randuniform(7,7)-1.

**Comment by LaszloHars** [comment]
...and don't try command("help")! It crashed my Windows: the desktop started rapidly and randomly flashing, and no mouse click got registered anymore. Only the power button helps shut the PC down.

**Comment by hanna-kn** [comment]
command("dir") will try to calculate the output of the `dir` command (which lists the contents of the current directory).
command("help") tries to calculate the output of the `help` command (which returns the help text of the command prompt).
Both will result in the calculation of very long nonsensical expressions. The command() function makes it possible to calculate (part of) an expression using an external command. I advice you not to use it if for random commands.

`randuniform()` has now been fixed.

**Comment by LaszloHars** [comment]
Thank you for the quick fix!
Qalculate is so wonderful, it is now always on my desktop. Because it is open, I tried to use its command(...) for a quick peek into directories, so I won't need to open a terminal window. Maybe the manual could tell more details about it? E.g., the result is not treated as a text string, but as a (part of an) expression. Also, a way to treat the result as a string could be useful.

**Comment by hanna-kn** [comment]
command("help") supposedly causes issues because of the extremely large memory requirements for the resulting calculation, but I do not understand why this results in such a strange behaviour in Windows.

I will add checks to make sure that the output of a command is a reasonably sane expressions. Otherwise no calculation will be performed and instead an error with the output of the command will be shown.
