### ISSUE TITLE
can't scroll menu using mouse

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/qalculate-gtk#447]
When menu item too much, it should let user scroll the menu. Using arrow key on keyboard to move cursor to submenu can scroll the menu normally, but moving mouse cursor to submenu can't scroll the menu.

**Comment by hanna-kn** [comment]
Which operating system/distribution, and GTK 3 version and theme are you using?

**Comment by howaboutuser** [comment]
distribution: debian 10
GTK 3: 3.24.5-1
theme: LXQt 0.14.1

**Comment by hanna-kn** [comment]
qalculate-gtk uses standard GTK menus. Normally there should be an arrow at the bottom and/or top of the menu and when the cursor is placed over the area of the arrow the menu should scroll.
![Screenshot_20221225_135254](https://user-images.githubusercontent.com/19703699/209468720-86b9e581-c816-4231-84a2-366338cc9add.png)

**Comment by howaboutuser** [comment]
I try GNOME(3.30.2), but not work.

![qalculate2](https://user-images.githubusercontent.com/120489523/209470700-ab0e9e3d-ef1c-4739-ade5-70a95d47c72a.png)

**Comment by howaboutuser** [comment]
I try another distribution and it work well, it's my operating system's problem.
distribution: lubuntu 18.10
GTK 3: 3.24.1-1ubuntu2
desktop environment: LXQt 0.13.0
