### ISSUE TITLE
Error in base conversion

### ISSUE THREAD

**Issue by Carolus13** [Qalculate/qalculate-gtk#450]
Dear Hanna, when I try this 5297523313185661510416696899➞base 12, I get this 5677↊897↊906666↋04137↋10↊↋<sub>12</sub> instead of the correct answer which is 5677a897a90666666b04137b10ab<sub>12</sub>. According to the numerous tests performed the problem occurs from **the conversion of some number to base 12 only**, being this corroborated in the 2 variants of the calculator (classic and new) in its latest versions (4.5.0). I don't know if this is a bug.
Congratulations Hanna for your great work.

**Comment by hanna-kn** [comment]
`↊` and `↋` is equivalent to `a` and `b`.
The two extra sixes in 5677a897a906666**66**b04137b10ab is incorrect.

**Comment by Carolus13** [comment]
Dear Hanna, I am sorry for the error presented, it is not my intention to bother you, but it will be possible to change to the **standard implementation in the conversion**, i.e. **a=10** and **b=1**1 and no other characters to that effect.
Thank you very much for everything, best regards.

**Comment by hanna-kn** [comment]
An option to change symbols used for output of digits 10 and 11 in duodecimal numbers has now been added. Default digits are changed to A and B.
