### ISSUE TITLE
Allow "Amp" to be accepted as "Ampere"

### ISSUE THREAD

**Issue by chriszylstra** [Qalculate/qalculate-gtk#456]
If i type out the word _amp,_ Qualculate! interprets this as an error. 

It works correctly if I type out the full word _ampere_. 

![image](https://user-images.githubusercontent.com/13257196/214939449-cce3dd75-447a-4b93-b0db-1b6234e1afa0.png)
![image](https://user-images.githubusercontent.com/13257196/214939788-b43f599c-669e-4723-902b-8af05ada5312.png)

![image](https://user-images.githubusercontent.com/13257196/214939493-b830f3dd-9aa9-4c44-8081-7d24c930645b.png)

**Comment by hanna-kn** [comment]
Done (in libqalculate).
I recommend use of the standard symbol for ampere, "A", instead (e.g. `3.3V × 205 uA`).
