### ISSUE TITLE
Unused icons in windows binary?

### ISSUE THREAD

**Issue by arix00** [Qalculate/qalculate-gtk#458]
In Windows portable zip binary, there are `share\icons` folder contains lots of icon files, I assume they're part of GTK theme, but Qalculate, including theme, works fine without them.

Am I missing something(technical or license reason?) or can we have the binary without these icons in future release? 

Thanks.

**Comment by hanna-kn** [comment]
If the icons are omitted, some icons in qalculate-gtk are missing (e.g. on the top two history buttons) and most are different. Note that this only applies to GTK GUI ("classic", qalculate-gtk.exe), and not the QT GUI ("new", qalculate-qt.exe).
