### ISSUE TITLE
Is equals implicit such that operator followed by operand is applied to the prior answer?

### ISSUE THREAD

**Issue by noabody** [Qalculate/qalculate-gtk#460]
Common on handheld calculators where the equals key implicitly applies the operator followed by operand to the previous answer on subsequent presses such that:
`1 + 1 + 2` press _equals_ or _enter_ to get answer `4`.  
Subsequent press of equals/enter repeats with `4 + 2` and result is 6.  
Subsequent press is `6 + 2` ...

How can this function be accomplished?

**Comment by howaboutuser** [comment]
1. 1+1+2
2. ans+2
3. =...=...=...

**Comment by noabody** [comment]
I see.  It can also be loaded with a number.  I was trying to add hex 14c to hex 600 multiple times and this works:
1. 600
2. ans+14c
3. =...=...=

**Comment by hanna-kn** [comment]
A more efficient solution: `genvector(0x600 + 0x14c × x, 0, 99, 100)` (outputs 100 iterations at the same time)

**Comment by noabody** [comment]
> A more efficient solution for many iterations: `genvector(0x600 + 0x14c × x, 0, 99, 100)` (outputs 100 iterations at the same time)

I did get that to work for ten iterations in the form `genvector(0x600 + 0x14c × x, 0, 9, 1, , 1)` interpreted as:
```
genvector(0x600 + (0x14c × x), 0x0, 0x9, 0x1, undefined, 0x1)
[600  74C  898  9E4  B30  C7C  DC8  F14  1060  11AC]
```
As per [Appendix A](https://qalculate.github.io/manual/qalculate-definitions-functions.html#qalculate-definitions-functions-1-Matrices--Vectors): genvector(Function, Min, Max, Dimension / Step size[, Variable][, Use step size])
