### ISSUE TITLE
How to enter negative numbers in RPN mode?

### ISSUE THREAD

**Issue by TomasoAlbinoni** [Qalculate/qalculate-gtk#465]
Searched the manual, couldn't find it. Having to deduct the number from zero seems silly.

**Comment by hanna-kn** [comment]
Enter the number and negate it using Ctrl+minus, the "−x" RPN button, or right-click on the keypad minus button.

**Comment by TomasoAlbinoni** [comment]
@hanna-kn Thank you for your quick response, but I'm afraid none of the suggestions work. I don't see a "-x" RPN button, Ctrl doesn't change the behavior of the minus key and right-clicking does nothing. I'm running Qalculate! (GTK+) 2.8.2 on Ubuntu 20.04.

**Comment by hanna-kn** [comment]
I do not remember what options were available in that version. I suggest that you install a more recent version (2.8.2 was released in 2018).

**Comment by TomasoAlbinoni** [comment]
@hanna-kn Yes! Version 4.5.1 works perfectly. Thank you!
