### ISSUE TITLE
Different computers show different content

### ISSUE THREAD

**Issue by ItismyGithub** [Qalculate/qalculate-gtk#466]
The computer language of my friend and I is Simplified Chinese
The performance of this software on the two computers is not the same
Mainly the contents of these three tabs "function, variable, unit"
My computer displays English, but my friend's computer displays Chinese
Other contents are displayed in Chinese
I repeatedly confirmed that the installation package is CRC equal, and the computers are all Win10
How could there be such a strange thing?

**Comment by hanna-kn** [comment]
The GUI language are controlled by the language selected in the "Region and Language" dialog, while the language of functions, variables, and units follows the Windows display language.

**Comment by ItismyGithub** [comment]
I am make sure our computer is set to Chinese language
But different computers show different
Looks like this is a bug ,can this be fixed ?

**Comment by ItismyGithub** [comment]
I'm sure all the “Windows display language” options are "Chinese"
These options have been verified to be ok
So this could really be a bug
Looks like just adding a setting option

**Comment by hanna-kn** [comment]
`LCIDToLocaleName` is used with `LOCALE_CUSTOM_UI_DEFAULT` to determine the language for functions, variables, and units. I'm working on a language setting in the preferences of qalculate-gtk.

Does qalculate-qt use the correct language for the GUI. In my experience qalculate-qt always uses the same language for the GUI as is used for functions, variables, and units.
