### ISSUE TITLE
multisolve crash

### ISSUE THREAD

**Issue by Barbazzo** [Qalculate/qalculate-gtk#468]
The following command crashes Qalculate!:

multisolve([x×y=1000,y×z=2000,z×x=3000],[x,y,z])

**Comment by hanna-kn** [comment]
Fixed (in libqalculate)

**Comment by Barbazzo** [comment]
Thanks for the quick response and fix!

Does this mean this fix will be in the next public stable Qalculate update?

**Comment by hanna-kn** [comment]
> Does this mean this fix will be in the next public stable Qalculate update?

Yes, the fix was included in version 4.6.0, which was released yesterday.
