### ISSUE TITLE
Gnome Shell Provider no longer working

### ISSUE THREAD

**Issue by arrufat** [Qalculate/qalculate-gtk#472]
Hi, I've recently noticed that the GNOME Shell search provider is no longer working.
Is anybody else experiencing the same problem?

I tried with Qalculate-gtk versions 4.6.0 to 4.4.0 (I saw there were some changes in the search provider file then) and on GNOME Shell 43 and Arch Linux.

**Comment by hanna-kn** [comment]
It works in Manjaro with the latest official packages (gnome-shell 43.3 and qalculate-gtk 4.5.1).

**Comment by arrufat** [comment]
Oh, do you know how can I debug this?

**Comment by hanna-kn** [comment]
I can now confirm the issue with the latest packages on Arch Linux. It occurs  regardless of Qalculate version. The search provider seems to cause a segfault outside of Qalculate.

**Comment by arrufat** [comment]
Thank you for confirming the issue, yesterday i tried several versions until I tried one that i was sure it once worked, but now doesn't.

I'll investigate a bit more, then.

**Comment by hanna-kn** [comment]
Fixed.
