### ISSUE TITLE
old version via winget

### ISSUE THREAD

**Issue by DHD-Harper** [Qalculate/qalculate-gtk#477]
An old version is still offered via winget. Please keep the winget package source up to date.

Thank you in advance.

**Comment by hanna-kn** [comment]
New versions are (or were) added automatically (without my involvement) for the winget package. I don't know why the latest version wasn't (possibly related to the fact that a file was missing from the 32-bit installer for both version 4.6.0 and 4.6.1).

I've know submitted a pull request for the new version (https://github.com/microsoft/winget-pkgs/pull/103795).

**Comment by hanna-kn** [comment]
The latest version should now be available using winget.
