### ISSUE TITLE
qalculate-gtk is sereverly outdated for Ubuntu Jammy / latest Linux Mint

### ISSUE THREAD

**Issue by navid-zamani** [Qalculate/qalculate-gtk#481]
Hey, I just wanted to contact you, but [the contact page](https://qalculate.github.io/contact.html) said to do it here…

I just stumbled across the problem, that qalculate-gtk was unable to update the exchange rates. Checking the server, it seems to be unavailable, and has been for a while.  
I wanted to file a bug, but then noticed that my version was severely outdated: 3.22.0-1  
Worse, apparently, according to `apt`, this *is* the latest version.  
It clearly is not.

I then ended up at https://launchpad.net/ubuntu/+source/qalculate-gtk ,  
which shows Jammy having the outdated version for some reason.

The problem is: I’m running the latest version of Linux Mint (21.1 Vera). Which is based on Jammy.  
I also looked for a PPA, but couldn’t find one.

This can’t be because of the Ubuntu version being an LTS one, as Mint 21 isn’t *that* old, so Jammy can’t be *that* old either. I mean 3.22 must be *years* earlier, no?

So I thought I’d tell you, so someone can prod the maintainer over at Ubuntu with a stick. As he seems to be a dead skeleton or at least asleep something. ;)

The problem with “just” installing a version manually from your releases, is that it won’t get updated. Meaning I’d just be back to square one. Or square two maybe. But stuck with the same problem again.

So… what can I do to get the latest version with automatic updates on Mint. (And no anti-social containerization monolithism toxicity please. If anyone wanted that, he’d use Windows and move to planet Ferengon. ;)

**Comment by hanna-kn** [comment]
This is the problem with distributions without rolling releases. Version 4.5.1 (which fixes exchange rates updates for minor currencies outside of Europe) is available in Ubuntu 23.04.

The self-contained binary ([qalculate-4.6.1-x86_64.tar.xz](https://github.com/Qalculate/qalculate-gtk/releases/download/v4.6.1/qalculate-4.6.1-x86_64.tar.xz)) should work and be possible to update semi-automatically. I would however primarily recommend that you try the flatpak (https://flathub.org/apps/io.github.Qalculate) or the snap package (https://snapcraft.io/qalculate). 

There is also a Qt UI (https://flathub.org/apps/io.github.Qalculate.qalculate-qt, https://snapcraft.io/qalculate-qt) which is not available at all as an Ubuntu/Mint/Debian package.

**Comment by jlu5** [comment]
> So I thought I’d tell you, so someone can prod the maintainer over at Ubuntu with a stick. As he seems to be a dead skeleton or at least asleep something. ;)

That's not very nice :)

You're right that the package *was* not particularly actively maintained for a while, but it's being taken care of now. That's why Ubuntu 23.04 has 4.5.1.
FYI I'm the current maintainer for libqalculate in Debian (and by extension Ubuntu, sort of). But realistically for either OS, there is no shipping newer releases of most software into a stable release after it releases.

> So… what can I do to get the latest version with automatic updates on Mint. (And no anti-social containerization monolithism toxicity please. If anyone wanted that, he’d use Windows and move to planet Ferengon. ;)

Well in practice that's the currently quickest way to get automatic updates. So pick your poison. ;)

That said... I can probably make a PPA, but I can't commit to rigorously testing every version - I'm not a Ubuntu user personally.

**Comment by jlu5** [comment]
https://launchpad.net/~jlu5/+archive/ubuntu/qalculate has 22.04 builds now. More can be added if there's demand, I suppose
