### ISSUE TITLE
Is it possible to disable tooltips?

### ISSUE THREAD

**Issue by abs0023** [Qalculate/qalculate-gtk#486]
Hi I'm using qalculate (GTK 4.7.0) on a tablet, with PostmarketOS (Alpine linux),
The cursor (which is hidden but still exist) remains at the spot you last touched on the touch screen,
so if you tap any touch on the keypad unless you quickly tap somewhere else a tooltip will popup.
It can be a little annoying sometime as you can't "click/tap" what is underneath the tooltips.
I would like to disable/get rid of the tooltips if it's possible.
Maybe adding an option in "Preferences" to turn off tooltips?

**Comment by hanna-kn** [comment]
I will examine the feasibility of adding in option to turn off tooltips. Meanwhile I suggest that you try the workaround mentioned here: https://bbs.archlinux.org/viewtopic.php?pid=1750829#p1750829.

**Comment by hanna-kn** [comment]
Done.

**Comment by abs0023** [comment]
That was fast. Thank you for the time you put in it.
