### ISSUE TITLE
UX issue when expression ends in a minus sign

### ISSUE THREAD

**Issue by Gitoffthelawn** [Qalculate/qalculate-gtk#492]
There is a UX issue when the expression ends in a minus sign in Qalculate-GTK v4.8.1.

STR:
1. In the expression field, enter `10-8-`
2. As expected, the answer is `2`
3. Hit the `Home` key to go to the beginning of the expression
4. Enter `100-`
5. Notice that the result does not change.  Instead it stays as `2`.

When does this occur in the real world?

Sometimes, I'll be adding/subtracting many numbers.  I'll then need to subtract the current result from a value (without clearing the expression).  So I'll click the `Home` key and then type in a value and the operator.  But the result doesn't change if I had already added a minus sign to the end of the expression in preparation to subtract another value.

Could I just delete the trailing minus sign?  Yes.  But this has happened enough times when working quickly with large series of values that I deemed it worthy of an issue report.  Sometimes in a long series of numbers, the last character in the expression is no longer visible in Qalculate's expression field.  Thus, it appears that Qalculate is delivering an incorrect result.  It took me a little trial and error to determine that Qalculate doesn't handle trailing minus signs elegantly.

**Comment by hanna-kn** [comment]
Fixed.

The calculate-as-you-type result are not updated if the last character is an operator, which would normally only result in an unnecessary warning. The result will now be update if the cursor as not at the end of the expression, even if the last character is an operator.

You can force updating of the result by pressing `Enter`.

**Comment by Gitoffthelawn** [comment]
Thank you Hanna!  Closing.
