### ISSUE TITLE
Executable of Qalculate (GTK) changed in v4.81

### ISSUE THREAD

**Issue by Gitoffthelawn** [Qalculate/qalculate-gtk#494]
Hi Hanna,

The executable for GTK version of Qalculate was changed from `qalculate-gtk.exe` to `qalculate.exe` in v4.81.  Was this an oversight or intentional?  Either name is, of course, fine, but the change in name required updating several scripts here.

What's you plan for the name of the GTK executable? Personally, I have no preference, except the use of a consistent name.

If, for whatever reason, the executable name may change back and forth in the future, that's fine too... Just let me know and I'll write a little code to accommodate both names.

Thanks!

**Comment by hanna-kn** [comment]
Fixed.

It was not intentional. The binary is named qalculate.exe in the installer, and I forgot to change it before creating the zip file.
