### ISSUE TITLE
Was just wondering about a decimal time to 'clock' time function and vice versa

### ISSUE THREAD

**Issue by SteveH66** [Qalculate/qalculate-gtk#499]
Is there a function already that converts decimal time to 'regular' or 'clock' time?  And 'clock' time to decimal time?  If not, what would be a good way to write one?  I think this function is not only necessary but vital.  Let me give you some idea of my reasoning for this question.

I was doing up these functions, which I thought should have already been in the calculator, but I didn't find them, so I went to do my own.  I am no programmer, and no mathematician, so I will just say this --- I think I got the 3 functions right, but any programmer or mathematician or whatever who looks at them is going to say "that's some ugly looking stuff there!"

So the calculations are to find out time, like travel time or time for something to go from one location to another, if you already know distance to travel (or travelled) and speed of travel.  The 2nd one is to calculate distance, if you know the speed it is travelling at and home much time it has been travelling.  And the 3rd one is to calculate speed if you know the distance it has travelled and the time it has been travelling.  I spent like half an hour or an hour going to websites, looking up the formulas used to do these 3 calculations, and then putting them into new functions --- trying to make sure I got the right variables in the right place in each of the formulas and whatever.

I went to all this trouble because I read something in a news article, and it had the distance you could detect something away from you (due to curvature of the earth) and the speed it was travelling at --- but it didn't have how much time that would have taken.  So the more I wondered about how much time that had taken, the more I got this undeniable urge to find out.  So I had to do the time function.  So I saw the other functions on the online calculator called, oddly enough, the "decimal to time" calculator.  Thankfully, that online calculator converted the time to days hours minutes seconds --- because I needed that so that I could check my work as I did my own time distance and speed functions.  I will have to find a speed calculator and a distance calculator somewhere, so that I can double-check my work to do those calculators.

So, when I ran my function, it came out 0.068 or something, and I realized that this had to be decimal, so then I guessed that you would multiply 60 by .068 and it would give you your answer.  So I did, and it was 4.08.  So I just realized, I thought that was 4 minutes 8 seconds.  That is not correct, that is minutes in decimal.  .08 is not 8 seconds, it is 5 seconds.  Approximately.  I know that because when I THEN multiplied 60 (seconds) by .08, it came out 4.8, which is decimal seconds - and 4.8 decimal seconds would be rounded up to 5 seconds.

You run into the same problem with feet and inches by the way.  In calculators like Qalculate you have to convert decimal to inches.  If it's been a while since you had your last math class in school, and you don't have a job where you do a lot of conversion from decimal to inches, or decimal to seconds, you have to go online and look for a calculator --- or have a phone app.

But a lot of people might not even realize that decimal was a decimal and think it was seconds or inches (as long as the decimal was .12 or below when working with feet and inch length measurements) after the period.  That isn't that big a deal if you are not working on something important.  But what if you are making a medical calculation or something, like timing something for your doctor?  Not only would it be embarrassing, but it could be a problem if neither you or the doctor/nurse/whatever caught the mistake.

Maybe that could be a function added into the calculator itself?  Like a decimal converter where you could select what system you were working in - time or length or whatever?  Qalculate is a great calculator, and I really appreciate all the hard work you put into it already.  I am sure all the other users appreciate your hard work as well.

But if it wouldn't be too much trouble to build in decimal conversion for various systems, that would be a great feature for people who aren't really that great with math and calculators and such.  And maybe even from systems like inches or seconds converted to decimal, if that wouldn't be too much extra work.  Thanks

**Comment by SteveH66** [comment]
I realize it is easier for calculators to do everything in decimal, but it would be a nice function of the calculator to convert decimal to various systems, and possibly from various systems to decimal. Thanks

**Comment by hanna-kn** [comment]
Use units (e.g. `0.068 h` returns `4 min + 4.8 s`, and `5.2 ft` returns `5 ft + 2.4 in`, by default) or use an appropriate number base (`0.068 to time = 0:04:04.8`, "5.2 to duodecimal ≈ 5.2497").

**Comment by SteveH66** [comment]
Thanks Hanna, appreciate the information

**Comment by SteveH66** [comment]
Actually, that brings up another question.  When I put in "5.9 ft to mixed" it returns "5 feet + (10 + 4/5) inches" which is great if you want simplified fractions.  But in many trades here in the USA, they use 4ths 8ths 16ths etc.  How would you get your fractions in that form? Thanks

**Comment by hanna-kn** [comment]
I've now added options to specify denominator for fractions, e.g. `5.9 ft to 1/4` returns  `≈ 5 ft + (10 + 3/4) in` (`to 4ths` or a corresponding menu item can also be used).

**Comment by SteveH66** [comment]
Thank you Hanna, this is a wonderful new added feature to a calculator that I, and I am sure most others consider, one of the best available.  Thank you so much for your time and efforts on your program!

**Comment by SteveH66** [comment]
I just input 5.9 ft to 1/4 in in qalculate GTK and this is what showed up as the input calculation : 5.9 ft to 1/4 = 5.9 feet to 1 × 4^(−1)

The answer showed up as = (23.6/4) feet

**Comment by hanna-kn** [comment]
> I just input 5.9 ft to 1/4 in qalculate GTK and this is what showed up as the input calculation : 5.9 ft to 1/4 = 5.9 feet to 1 × 4^(−1)
>
> The answer showed up as = (23.6/4) feet

That is the expected behaviour when using version 4.8.1. The new conversion/option requires compilation of the latest source code of libqalculate and qalculate-gtk from Git.

**Comment by SteveH66** [comment]
Thank you for clearing that up Hanna.  Is there going to be a new version release soon that incorporates this, or do we need to try to compile from source?  Thanks

**Comment by hanna-kn** [comment]
> Is there going to be a new version release soon that incorporates this, or do we need to try to compile from source? 

A version which incorporates the new features will probably be released within four weeks.

**Comment by SteveH66** [comment]
Thanks Hanna
