### ISSUE TITLE
Fuctions bin(), oct() and hex()

### ISSUE THREAD

**Issue by Juebo** [Qalculate/qalculate-gtk#5]
These functions work the opposite way as expected.
From Hex(10) I would expect 0xA to be the result and not 16. Like for sin() where I expect the sine as result I would expect hex() has the hex-digit as result

**Comment by hanna-kn** [comment]
You are correct. It is a bit inconsistent. But mathematical functions never control the display of the result. 

The solution would be to rename the current hex() function to decifromhex() or similar, and possibly adding a hex() function that returns a text string representing a hexadecimal number (although to me to current syntax using "... to hex", which always affects the whole expression and does not introduce text strings, makes more sense).

**Comment by Juebo** [comment]
Well, this "to" thing does not work for me. "10 to hex" becomes "10 to hour"  and ends with "Error(s) in unitexpression". "10 to bin" becomes "10  to inch barn ≈ 3,9370079((Tb⋅in) ∕ µm^3)".  But "1 m to mm" works well. The other way entering 0xA works fine. So I would not need this wrong Hex() function which is exactly the same.

**Comment by hanna-kn** [comment]
Which version are you using?
The "to hex" syntax was introduced in version 0.9.8 (for older versions the menu options, or the convert number bases tool, can be used with the same result, but it is less efficient for conversion of a single result).

**Comment by Juebo** [comment]
Well, Ok, I am using the older one: 0.9.7. So I am looking forward the next update.

Btw: Qalculate is the best calculator, supporting units I know for linux. Big praise!
