### ISSUE TITLE
Start window position.

### ISSUE THREAD

**Issue by giuseppebin** [Qalculate/qalculate-gtk#500]
I would like the program to remember the position of the window at startup.

Thanks.

**Comment by hanna-kn** [comment]
Edit->Preferences->Look & Feel->Remember window position

**Comment by giuseppebin** [comment]
wow thanks. Awesome.

**Comment by giuseppebin** [comment]
isn't there the same option for the new interface? Many thanks.

**Comment by hanna-kn** [comment]
> isn't there the same option for the new interface? Many thanks.

The new interface (qalculate-qt) should remember the position by default, but I discovered that the position is only saved if the size of the window has been changed from the default (this has now been fixed).

**Comment by giuseppebin** [comment]
Got it! Many thanks.
