### ISSUE TITLE
Only view squares in Qalculate.gtk

### ISSUE THREAD

**Issue by bich30** [Qalculate/qalculate-gtk#51]
I have install qalculate by snap and i view only squares.

Thanxs

![qalculate](https://user-images.githubusercontent.com/10535855/37832709-a9a2f86c-2ea9-11e8-8107-3ba6864920ec.png)

**Comment by hanna-kn** [comment]
Which distribution/operating system and locale/language are you using?

**Comment by bich30** [comment]
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

$ locale
LANG=es_ES.UTF-8
LANGUAGE=es_ES
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=

**Comment by hanna-kn** [comment]
I am not able to reproduce the issue using my Ubuntu 17.10 test system.
It seems unlikely that this is an issue caused by any bug in Qalculate!.

**Comment by bich30** [comment]
Whats fonts is used by Qalculate.gtk ?

**Comment by hanna-kn** [comment]
The default font is not changed in the code (except for modification of size, color and weight in a few widgets).

What font are set as desktop default? Are you using a font saved to the home directory?

**Comment by bich30** [comment]
The desktop's font is "Ubuntu" type.
The font is saved in the directory "System"
I have instaled "pango".

**Comment by bich30** [comment]
How execute it in debug mode?
