### ISSUE TITLE
Feature suggestion: hexadecimal floating-point notation

### ISSUE THREAD

**Issue by suruena** [Qalculate/qalculate-gtk#514]
The IEEE 754-2008 standard (and C99) introduced a notation for floating-point literals to represent exactly the (binary) value of any floating-point constant (in contrast to decimal notation, which the conversion may depend on the compiler algorithms).

This notation uses the "0x" prefix, and the "p" exponent separator. For example: +0x1.921fb54442d18p+1 = 3.141592653589793

See for example https://en.cppreference.com/w/cpp/language/floating_literal

It would be very useful for programmers like me to have in the "Floating Point Conversion" window an additional "Hexadecimal notation" box to be able to represent exactly any FP value (in contrast to decimal FP notation). Thanks!!

**Comment by hanna-kn** [comment]
Done.

<img width="554" alt="Screenshot_20240131_124720" src="https://github.com/Qalculate/qalculate-gtk/assets/19703699/11efcda0-da21-4e54-bb58-9a6f7a921aed">
