### ISSUE TITLE
Add support for unit lightseconds (and lightminutes, and lighthours)

### ISSUE THREAD

**Issue by soleofthesea** [Qalculate/qalculate-gtk#515]
![Screenshot_20240208_144732](https://github.com/Qalculate/qalculate-gtk/assets/35699509/d8237a3c-15fe-41db-8f07-8a5383feb4c6)

**Comment by hanna-kn** [comment]
Done (https://github.com/Qalculate/libqalculate/commit/c1360ddba178fc1251e10b23c2ad9b8dbdd04e70).
