### ISSUE TITLE
error   230×(1−5.3%−1.25%)−4

### ISSUE THREAD

**Issue by better319** [Qalculate/qalculate-gtk#516]
230×(1−5.3%−1.25%)−4=210.935

![image](https://github.com/Qalculate/qalculate-gtk/assets/13842581/33f6c00b-23d5-4449-bd87-287f5f6f3339)

**Comment by better319** [comment]
![image](https://github.com/Qalculate/qalculate-gtk/assets/13842581/1de882e5-fab3-49dd-9d82-0993ee613261)

**Comment by hanna-kn** [comment]
Deactivate Simplified Percentage Calculation in Mode->Parsing Mode (模式->解析模式) menu.
