### ISSUE TITLE
Only ASCII characters in hexadecimal floating-point notation

### ISSUE THREAD

**Issue by suruena** [Qalculate/qalculate-gtk#517]
I'm just trying in V5.0 the new feature #514 showing hex p notation in the FP conversion window, and works really nice, thanks! The only comment would be that the sign of the exponent uses an Unicode minus sign character, so when copying it to a source code file the programmer needs to manually remove the minus sign and replace by an ASCII hyphen, otherwise it won't compile (at the end, the p notation is mostly needed by programmers I think).

I suggest then that qalculate-qtk produces directly the ASCII hyphen instead of the Unicode minus when producing numbers with p notation, so programmers do not need to modify that manually. The sign of the number is already using the ASCII hyphen, only the exponent is using Unicode minus sign character, for example value "−2^−23" is shown in V5.0 as "-0x1p−23" (first character is in ASCII, character after 'p' is Unicode), so my suggestion is that is is shown as "-0x1p-23" (so everything is in ASCII). Thanks in advance.

**Comment by hanna-kn** [comment]
Done.
