### ISSUE TITLE
[Feature Request] : Find multiples

### ISSUE THREAD

**Issue by tethragon** [Qalculate/qalculate-gtk#519]
Since there is a divisors() function implemented in Qalculate!, I am wondering if it would be possible to implement a multiples() function for a given number, between a given range (as multiples are infinite).

I was thinking something like that ( https://www.calculatorsoup.com/calculators/math/multiples.php ) , but more elegant.

For example if you want to find multiples of 9 between 50 and 100 you could type multiples(9;50;100) or something like this,

I hope the developer likes this idea and, if it is not that big of a trouble to implement, I hope to see it in a future version of this great calculator.

**Comment by hanna-kn** [comment]
Done (in libqalculate).
The new function uses the expression `genvector(n × x, ceil(y/x), floor(z/x))` (with modifications to handle negative _x_ and zero multiples).

**Comment by tethragon** [comment]
> Done (in libqalculate). The new function uses the expression `genvector(n × x, ceil(y/x), floor(z/x))` (with modifications to handle negative _x_ and zero multiples).

Does this mean we will be able to use multiples() function with the next update of qalculate? Possibly 5.1 version?
