### ISSUE TITLE
element index is reverse in matrix result

### ISSUE THREAD

**Issue by howaboutuser** [Qalculate/qalculate-gtk#521]
input
[1,2;3,4]

output
right click>View/Edit Matrix>click 3
current element: (1, 2)

The correct index is (2, 1).

![screen2](https://github.com/Qalculate/qalculate-gtk/assets/120489523/63286ee7-deb0-4b9f-89ad-000b0a9f7b5b)

**Comment by howaboutuser** [comment]
Isn't it a bug? 
a11 a12
a21 a22

**Comment by hanna-kn** [comment]
Fixed (I forgot this bug).
