### ISSUE TITLE
AltGr on W10 works differently than in other programs

### ISSUE THREAD

**Issue by mwrnckx** [Qalculate/qalculate-gtk#522]
On my keyboard (Czech QWERTY) normally AltGr+6=^ and AltGr+8=*. Everywhere, even here. But in Qalculate! AltGr+6= xor and AltGr+8=^. Why? In particular, I miss the * character a lot.

**Comment by hanna-kn** [comment]
Fixed.

When AltGr is pressed Ctrl is also reported as pressed in Gtk on Windows. Ctr+* is used as shortcut for ^, and Ctrl+^ for xor.
