### ISSUE TITLE
Windows 11 x64 Can't Install qalculate-5.0.0-x64.msi

### ISSUE THREAD

**Issue by datzent83** [Qalculate/qalculate-gtk#526]
Not sure what the issue is, but I can't seem to install qalculate-5.0.0-x64.msi. When I run the installer, it looks like its doing something, but nothing happens. Task Manger does not show anything at all.

**Comment by foreachthing** [comment]
You, most likely, need to unblock it. Go to the installer (the downloaded file), then open properties and check "unblock".
![image](https://github.com/Qalculate/qalculate-gtk/assets/10420187/51727efb-d1da-4006-b218-4e3213cfecd9)

**Comment by datzent83** [comment]
> You, most likely, need to unblock it. Go to the installer (the downloaded file), then open properties and check "unblock". ![image](https://private-user-images.githubusercontent.com/10420187/326112383-51727efb-d1da-4006-b218-4e3213cfecd9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNjYzOTUsIm5iZiI6MTcxNDE2NjA5NSwicGF0aCI6Ii8xMDQyMDE4Ny8zMjYxMTIzODMtNTE3MjdlZmItZDFkYS00MDA2LWIyMTgtNGUzMjEzY2ZlY2Q5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDIxMTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxYmVjZDc0NjU4NGZhOWE0M2U5MmZhMmE0MjBlNTA3YzU4YmQ5NzA2OTcwZDQ2ZGE3ZmFkYjNhOTNiODU4MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lqi4wXiDlB_ggWj6wotGJ2Yez7ltHTziHH2l1vLq6L4)

Thanks! That worked. It's the simplest things that cause havoc.
