### ISSUE TITLE
why auto exchange rates are put as -1 value ?

### ISSUE THREAD

**Issue by shirishag75** [Qalculate/qalculate-gtk#53]
Dear upstream, 

I was trying/fiddling around with qalculate and came across the config file in ~/.config/qalculate  where this is what is says about getting updated exchange rates - 

```
~/.config/qalculate$ cat qalculate-gtk.cfg | grep auto_update_exchange_rates
auto_update_exchange_rates=-1
```

This is somewhat related to #49 but not really.

**Comment by hanna-kn** [comment]
A auto_update_exchange_rates value of -1 means that the user will be asked before the exchange rates (if older than one week) are updated. A value > 0 means that the exchange rates will automatically be updated (without asking the user) when used if older than the number of days specified by the value. If auto_update_exchange_rates is zero, the exchange rates will only be updated manually (using exrates command).
