### ISSUE TITLE
Date & time of history items

### ISSUE THREAD

**Issue by UlyssesZh** [Qalculate/qalculate-gtk#537]
Is the date & time of each history item stored? Can I see it on the UI?

**Comment by hanna-kn** [comment]
It is not currently stored.

**Comment by UlyssesZh** [comment]
May it be a feature in the future? It can be very useful. Sometimes I want to see what I entered into the calculator back when I did a homework in the past.

**Comment by hanna-kn** [comment]
I will investigate the feasibility of this. I would probably prefer not to show the dates and only make it a searchable property. It might also be useful to be able to specify the maximum age of saved history items, instead of number of lines.

**Comment by hanna-kn** [comment]
As an alternative I recommend that you try the bookmarks (in history context menu) or comments (text after `#` in expression) features. Note that bookmarked items will never be removed from history.

**Comment by UlyssesZh** [comment]
Thank you for the tip. I was aware of that, but it is kind of hard to predict whether I will refer to a history item in the future.

**Comment by hanna-kn** [comment]
Done. Search by date has now been added to the context menu. The date of the selected history item is shown in the label of the menu item.
