### ISSUE TITLE
Settings: separate UI language from (locale) number format

### ISSUE THREAD

**Issue by knuth-konrad** [Qalculate/qalculate-gtk#539]
This is a suggestion, _not_ a bug report.

As far as I can tell, both the UI language and the number format is taken from the system's locale (on Windows) when the option "Ignore system _language_) is disabled.

I'm the strange German fellow that prefers an English UI, but still would like to use the German number format, i.e. recognize the "," as the decimal separator, as that's the character on the keyboard's number block. Which of course makes entering numbers easier than having to move over to the letter part of the keyboard to press the "." key.

I'd appreciate it if these two settings, UI language and number format _(and possibly dates as well, while your at it)_ could be configured separately.

**Comment by hanna-kn** [comment]
There is already an option the change the decimal separator: `Preferences->Numbers & Operators->Use comma as decimal separator`

Dates are always presented using the standard format YYYY-MM-DD (ISO 8601) and this also the preferred format for input.

There is support for specifying the language separately by adding a line starting with `language=` (e.g. `language=en_US`) to qalculate-gtk.cfg.

**Comment by knuth-konrad** [comment]
Thank you very much. Consider me blind, as I went not once but twice through the _Preferences_ dialog, but obviously missed that one.

**Comment by knuth-konrad** [comment]
ID10T-Problem, therefore solved.
