### ISSUE TITLE
Units window no longer renders when opened the second time

### ISSUE THREAD

**Issue by martinvonwittich** [Qalculate/qalculate-gtk#540]
I'm running qalculate-gtk 5.1.0 on NixOS 24.05 without a configuration file. When I open the Units window with Edit -> Units the first time, it works fine:

![image](https://github.com/Qalculate/qalculate-gtk/assets/6863569/c0b89eba-9a2f-431b-ba23-59e5af6d8eb6)

When I close it and then reopen it, it won't render anymore:

![image](https://github.com/Qalculate/qalculate-gtk/assets/6863569/e05a1460-73c0-4b4a-971d-34096d07ab8f)

Apart from that, Qalculate still works fine, so it doesn't crash or hang - I can still enter new expressions, and I can close the defective Units window by using the window list.

**Comment by hanna-kn** [comment]
Fixed.

This affected all versions of qalculate-gtk and most windows, when closed using window manager controls (e.g. title bar button). I was however only able to reproduce the issue on a very recently updated Arch Linux system.
