### ISSUE TITLE
Minor suggestion reg. "overstrike" mode

### ISSUE THREAD

**Issue by LSAXYZ321** [Qalculate/qalculate-gtk#549]
When using overstrike mode in Qalculate, I have noticed that this mode doesn't work correctly with operators
Take the following simple example:
240*10
If I want the edit that in overstrike mode to:
240/10
, Qalculate still work in "insert" mode with operators, so I get the following
240/*10
Would be nice if this behaviour would be updated to true "overstrike" mode

BR Lars

**Comment by hanna-kn** [comment]
Fixed.

**Comment by LSAXYZ321** [comment]
Thank you, that was fast :-)
