### ISSUE TITLE
Oversized subscripts/superscripts

### ISSUE THREAD

**Issue by BouncyMaster** [Qalculate/qalculate-gtk#550]
Superscript rendering:
![image](https://github.com/user-attachments/assets/1eba02ff-3fc8-4d9a-b87c-272a182a9cac)

Subscript rendering:
![image](https://github.com/user-attachments/assets/6b4748f4-ab5c-4cb8-9462-838ef66fec5d)

**OS:** Linux (Wayland)
**Versions affected:** 5.2.0, master

**Additional info:** Weirdly, I have another machine with a similar configuration, where this issue is not present. 

I have noticed that issue #535 is somewhat similar to this one, with a referenced commit b876a1eebe6540c5de9bc3bb81a970cad2126aa2. I have tried building the tree prior to this commit, but the issue is still present.

**Comment by hanna-kn** [comment]
I'm not able to reproduce this issue. Please provide more details (Gtk and Pango version, font, scaling, theme, desktop environment, Linux distribution).

**Comment by thesamesam** [comment]
To close the loop on this, OP reported it to Gentoo at https://bugs.gentoo.org/940923, and I've sent a patch to fontconfig at https://gitlab.freedesktop.org/fontconfig/fontconfig/-/merge_requests/333.
