### ISSUE TITLE
nounit() not working in sub-function / expression

### ISSUE THREAD

**Issue by VK2BEA** [Qalculate/qalculate-gtk#551]
I have an expression (VSWR) ... `(1+\1)/(1−\1) ` with a sub-function `10^(  nounit(\x) / −20.0)`
I want to be able to enter with a number ( say 20.1 ) or with the unit ( dB )

If I do this, using the number by itself works ... `VSWR( 20.1 )` gives `= 1.219 399 416` but `VSWR( 20.1dB )` gives `= VSWR(20.1 dB)`.
I can do `VSWR( nounit( 20.1dB ) )` which works. This implies that the nounit function in the sub-function does not work.

**Comment by hanna-kn** [comment]
I'm unable to reproduce this issue.

Which version are you using?
Have any properties for the function argument been specified (e.g. VSWR(20.1 dB) will fail if the argument definition requires a number)?

**Comment by VK2BEA** [comment]
Version 5.20 .. ah yes, I had defined it as a 'number'. 
I made it 'free' and it works. 
I do get a warning if I use "20.1 dB" ...  (do not enter sign) "Logarithmic ratio units are treated as other units and the results might not be as expected". Can I suppress that?
