### ISSUE TITLE
Qalculate for commercial use

### ISSUE THREAD

**Issue by Pikfisk** [Qalculate/qalculate-gtk#57]
Hi everybody,

I'm very fond of Qalculate and its functions, so I would like to install the software on my workstation at my job.
My immediate thought is that Qalculate is freeware, so it should not be a problem to use it as a tool while I'm working.
But since I need our IT admins to install the software on my PC, I need to document that we are allowed to use it commercial, even though it's freeware.

Does Qalculate have a writing about this somewhere, or can someone with the authority to grant permission to use it commerically?

Thank you in advance, 

Best Regards, 
Jonas

**Comment by hanna-kn** [comment]
Qalculate! is GPL licensed (GNU General Public License v2 or later). 

From Wikipedia:

> **Software under the GPL may be run for all purposes, including commercial purposes** and even as a tool for creating proprietary software, for example when using GPL-licensed compilers. Users or companies who distribute GPL-licensed works (e.g. software), may charge a fee for copies or give them free of charge. This distinguishes the GPL from shareware software licenses that allow copying for personal use but prohibit commercial distribution, or proprietary licenses where copying is prohibited by copyright law. The FSF argues that freedom-respecting free software should also not restrict commercial use and distribution (including redistribution):
>
> In purely private (or internal) use—with no sales and no distribution—the software code may be modified and parts reused without requiring the source code to be released. For sales or distribution, the entire source code need to be made available to end users, including any code changes and additions—in that case, copyleft is applied to ensure that end users retain the freedoms defined above.

**Comment by Pikfisk** [comment]
Thank you very much for a quick reply! :)
