### ISSUE TITLE
Auto Complete 

### ISSUE THREAD

**Issue by saileshkush95** [Qalculate/qalculate-gtk#59]
I'm new user of this amazing calculator and thanks for making this amazing calculator. But, When i press tab for auto complete is not working, I didn't know is this features is available or not and please add the features for dark theme and please include tab menu when changing from history to key pad and vice versa

**Comment by hanna-kn** [comment]
> But, When i press tab for auto complete is not working, I didn't know is this features is available or not

Tab is not used for completion. As you type, a list of completion suggestions is displayed from which you can do completion using the mouse or arrow and enter keys. 

> please add the features for dark theme

qalculate-gtk uses the current desktop-wide gtk+ theme.

You can run qalculate-gtk with a dark theme variant specified on the command line (but to change the window decorations you need to use xprop or similar): `GTK_THEME=Adwaita:dark qalculate-gtk`

If you are using Windows, I suggest that you add the environment variable "GTK_THEME" with value "Adwaita:dark" in advanced system properties.

> please include tab menu when changing from history to key pad and vice versa

I do not understand this request. Can you please provide a more detailed description.

**Comment by saileshkush95** [comment]
I'm unable to install it from kde neon  store, So i installed snap package of Qalculate.
Above method is not working for snap packages

**Comment by hanna-kn** [comment]
`GTK_THEME=Adwaita:dark qalculate.gtk` works for me using the snap package on Ubuntu 17.10 (the Breeze-Dark GTK theme, which usually will look nicer on the default KDE Plasma desktop, is however not available for the snap package).

**Comment by saileshkush95** [comment]
Thanks it works for me but it is not a permanent solution, it only woks when I execute  `GTK_THEME=Adwaita:dark qalculate.gtk` in terminal.

**Comment by hanna-kn** [comment]
Prepend GTK_THEME=Adwaita:dark to the command of the menu item for Qalculate! (right click the menu item under Applications->Utilities in the plasma menu and select Edit Application).

**Comment by saileshkush95** [comment]
It's works thanks a lot
