### ISSUE TITLE
Commas not ignored

### ISSUE THREAD

**Issue by Jonrysh** [Qalculate/qalculate-gtk#60]
Edit->Preferences shows "Ignore comma in numbers" checked, but commas are not ignored.  For example, typing
- 1,234
- Enter

produces 1 at the top of the stack and the error
"RPN syntax error. Values left at the end of the RPN expression"

Running Qalculate (GTK+) 2.0.0 in RPN mode under Fedora-28 Linux.

**Comment by hanna-kn** [comment]
Fixed.

This only occurs when RPN syntax (independent of the RPN stack) are enabled.

**Comment by Jonrysh** [comment]
Yes, changing Mode->RPN Mode from "Full RPN Mode" to "RPN Stack Only" cures the problem.  

Does the comment "Fixed" means that there is a later version in which the problem is also cured in RPN Syntax mode?

**Comment by hanna-kn** [comment]
> Does the comment "Fixed" means that there is a later version in which the problem is also cured in RPN Syntax mode?

It means that it was fixed a few minutes before my comment and that this fix be included in the next version.
