### ISSUE TITLE
Element-wise multiplication

### ISSUE THREAD

**Issue by MatthewScholefield** [Qalculate/qalculate-gtk#65]
Is there a way to multiply two vectors/matrices of the same dimentions, element by element (the hadamard product)?

Thanks!

**Comment by hanna-kn** [comment]
There is unfortunately not yet any easy way to calculate the hadamard product, but it can be done using for example `processm(x*element(matrix2;"i";"j");x;matrix1;"i";"j")` (you can add it as a new function with the expression `processm("x"*element(\y;"i";"j");"x";\x;"i";"j")`, or `processm("x"*element(y;"i";"j");"x";x;"i";"j")` if using simplified function editor).

**Comment by hanna-kn** [comment]
hadamard() function (as well as a generic entrywise() function for operations other than multiplication) has now been added in libqalculate.

**Comment by MatthewScholefield** [comment]
That's amazing! Can't believe the speed of new features. Will compile and test tonight.
