### ISSUE TITLE
Install problem with snap

### ISSUE THREAD

**Issue by jk-1** [Qalculate/qalculate-gtk#67]
I just installed snap qalculate into my ubuntu 16.04 virtual machnie desktop. Install went without errors but I cannot start qalculate.

	jk@mypc-a02:~$ sudo snap install qalculate
	[sudo] password for jk: 
	qalculate 2.6.2 from 'h-k' installed
	
	jk@mypc-a02:~$ qalculate --version
	The program 'qalculate' is currently not installed. You can install it by typing:
	sudo apt install qalculate-gtk
	
	
	jk@mypc-a02:~$ qalc
	The program 'qalc' is currently not installed. You can install it by typing:
	sudo apt install qalc
	
Then I tried to start binaries in /snap/qalculate/81/bin:
	
	jk@mypc-a02:~$  /snap/qalculate/81/bin/qalc
	/snap/qalculate/81/bin/qalc: error while loading shared libraries: libqalculate.so.19: cannot open shared object file: No such file or directory
	
	jk@mypc-a02:~$  /snap/qalculate/81/bin/qalculate-gtk 
	/snap/qalculate/81/bin/qalculate-gtk: error while loading shared libraries: libqalculate.so.19: cannot open shared object file: No such file or directory
	
	jk@mypc-a02:~$  /snap/qalculate/81/bin/desktop-launch 
	mkdir: cannot create directory ‘/.local’: Permission denied
	mkdir: cannot create directory ‘/.cache’: Permission denied
	mkdir: cannot create directory ‘/.config’: Permission denied
	cp: '/home/jk/.config/user-dirs.locale' and '/home/jk/.config/user-dirs.locale' are the same file
	mkdir: cannot create directory '/.config': Permission denied
	ln: failed to create symbolic link '/.config/dconf': No such file or directory
	mkdir: cannot create directory '/.config': Permission denied
	ln: failed to create symbolic link '/.config/gtk-3.0/settings.ini': No such file or directory
	mkdir: cannot create directory '/.config': Permission denied
	ln: failed to create symbolic link '/.config/gtk-3.0/bookmarks': No such file or directory
	mkdir: cannot create directory '/.config': Permission denied
	ln: failed to create symbolic link '/.config/gtk-2.0/gtkfilechooser.ini': No such file or directory
	mkdir: cannot create directory '/.config': Permission denied
	ln: failed to create symbolic link '/.config/ibus': No such file or directory
	/snap/qalculate/81/bin/desktop-launch: line 443: /flavor-select: No such file or directory

The file libqalculate.so.19 is in lib dir:

	jk@mypc-a02:/snap/qalculate/81$ ll lib
	total 17788
	drwxr-xr-x  2 root root      119 elo   16 10:35 ./
	drwxr-xr-x 10 root root      229 elo   16 10:35 ../
	-rw-r--r--  1 root root    12840 elo   16 10:30 bindtextdomain.so
	lrwxrwxrwx  1 root root       22 elo   16 10:34 libqalculate.so -> libqalculate.so.19.0.0*
	lrwxrwxrwx  1 root root       22 elo   16 10:34 libqalculate.so.19 -> libqalculate.so.19.0.0*
	-rwxr-xr-x  1 root root 18201264 elo   16 10:34 libqalculate.so.19.0.0*
	

After this I tried install again in another ubuntu 16.04 virtual machine using fresh environment and got these outputs:

	jk@mypc-a02:~$ sudo snap install qalculate
	[sudo] password for jk: 
	error: cannot install "qalculate": Post https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup
	       api.snapcraft.io on [::1]:53: read udp [::1]:42370->[::1]:53: read: connection refused

How to fix these? Thank you for your support!

**Comment by hanna-kn** [comment]
The correct commands for the snap package is
`qalculate.gtk`, and
`qalculate.qalc`.

There should also be a menu item in the program menu (or similar).

**Comment by jk-1** [comment]
Thanks for your support. 

Is this normal output of calc:

	jk@mypc-a02:~$ qalculate.qalc
	/snap/qalculate/81/bin/desktop-launch: line 25: /home/jk/.config/user-dirs.dirs: Permission denied
	ln: failed to create symbolic link '/home/jk/snap/qalculate/81/snap/qalculate/81/Documents': No such file or directory
	ln: failed to create symbolic link '/home/jk/snap/qalculate/81/snap/qalculate/81/Desktop': No such file or directory
	ln: failed to create symbolic link '/home/jk/snap/qalculate/81/snap/qalculate/81/Downloads': No such file or directory
	ln: failed to create symbolic link '/home/jk/snap/qalculate/81/snap/qalculate/81/Music': No such file or directory
	ln: failed to create symbolic link '/home/jk/snap/qalculate/81/snap/qalculate/81/Pictures': No such file or directory
	ln: failed to create symbolic link '/home/jk/snap/qalculate/81/snap/qalculate/81/Videos': No such file or directory
	ln: failed to create symbolic link '/home/jk/snap/qalculate/81/snap/qalculate/81/Templates': No such file or directory
	> 1+1
	
	  1 + 1 = 2
	
	> quit
	jk@mypc-a02:~$ 

Permissions were initially :

	jk@mypc-a02:~$ ll /home/jk/.config/user-dirs.dirs
	-rw------- 1 jk jk 0 syys  28 13:14 /home/jk/.config/user-dirs.dirs

But I fixed them to be as below but still same error message is printed when I start qalc.

	jk@mypc-a02:~$ ll /home/jk/.config/user-dirs.dirs
	-rw-rw-rw- 1 jk jk 0 syys  28 13:14 /home/jk/.config/user-dirs.dirs



When I start gtk, it prints this text. GUI opens and it seems to work OK. Should I fix the permission problem somehow?

	jk@mypc-a02:~$ qalculate.gtk
	Gtk-Message: 21:43:10.108: Failed to load module "topmenu-gtk-module"
	shm_open() failed: Permission denied

**Comment by hanna-kn** [comment]
The error messages is annoying but seems to be a general issue with snap packages and should be safe to ignore.
