### ISSUE TITLE
Missing help in the snap version of qcalculate

### ISSUE THREAD

**Issue by ajpmaclean** [Qalculate/qalculate-gtk#70]
I installed on Kubuntu 18.04 using snap with no issues. It seems to be working normally with no issues except for the missing help.

Pressing Help|Contents yields the following message:

![image](https://user-images.githubusercontent.com/8550459/46578371-bc479a80-ca4a-11e8-88de-467f23841004.png)

There is no **/share** in my Kubuntu 18.04 installation. I checked  **/snap/qalculate/current/share** and it just contains these folders: **appdata  gnuplot  locale  pixmaps  qalculate**

**Comment by hanna-kn** [comment]
Fixed (will open help available on Internet, because of problem opening local url).

**Comment by ajpmaclean** [comment]
Thankyou so much for your prompt response and fix. It is much appreciated.

Andrew Maclean

**Comment by ajpmaclean** [comment]
Tested
