### ISSUE TITLE
Converts to kilogram, but shows gram

### ISSUE THREAD

**Issue by haarp** [Qalculate/qalculate-gtk#74]
Hello,

I've just experienced a bug that made me go "huh". Type the following into Qalculate 2.8.1:

    4.25m÷13g

It returns

    326.92308 m ÷ g

That's not right. It seems to be converting to m/kg, but still shows m/g in the result.

Thanks!

**Comment by hanna-kn** [comment]
Fixed in libqalculate. (It's unfortunate that I missed such a serious bug and I should release a fixed version soon.)

**Comment by haarp** [comment]
Thanks, that was quick!
