### ISSUE TITLE
[2.8.2 snap] Wacky MPG -> L/Km conversion

### ISSUE THREAD

**Issue by smartavionics** [Qalculate/qalculate-gtk#75]
Hi, I just installed and started playing with qalculate, looks very useful but this has got me puzzled...

![screenshot_2018-12-09_10-10-07](https://user-images.githubusercontent.com/585618/49695984-e75d8000-fb9a-11e8-8715-4df69d907577.png)

The Km/L conversion is this:

![screenshot_2018-12-09_10-13-24](https://user-images.githubusercontent.com/585618/49696003-37d4dd80-fb9b-11e8-9678-3a0d0c84c29c.png)

**Comment by hanna-kn** [comment]
The result is mathematically correct, but obviously not very useful. Reciprocal unit conversion was not supported. This has now been fixed in libqalculate.

**Comment by smartavionics** [comment]
OK, thanks for the quick response and fix. Closing...
