### ISSUE TITLE
Units addition wrong result

### ISSUE THREAD

**Issue by GitterHubber** [Qalculate/qalculate-gtk#76]
![image](https://user-images.githubusercontent.com/2816034/50067118-63804500-01e5-11e9-9273-aea2a47d72cf.png)

add milliliter and liter gives result in nautcial mile as shown in the image.

OS: Windows7, 64bit
Qalculate! 2.8.2

**Comment by hanna-kn** [comment]
I'm unable to reproduce this issue (on Windows 7, 64-bit).
Make sure that nautical mile is not selected under conversion (tab), with continuous conversion activated. (If this is the case the issue should not recur after the application is restarted.)

**Comment by GitterHubber** [comment]
Yes indeed that was the case,  nautical mile was entered in the conversion tab.
Apologies for the false flag!
