### ISSUE TITLE
The terminal window for the windows version should be disabled by default

### ISSUE THREAD

**Issue by takao42** [Qalculate/qalculate-gtk#8]

**Comment by hanna-kn** [comment]
Please provide a description of the issue (there is neither a terminal window nor a Windows version for qalculate-gtk, but perhaps you have used the words differently than what I am used to).

**Comment by takao42** [comment]
The windows version I downloaded from here
http://chengsun.uk/2014/01/01/qalculate-windows-port.html
has a terminal window alreays open shown in the screenshot.
![qalculate windows](https://cloud.githubusercontent.com/assets/16948006/18502885/996262de-7a1f-11e6-9485-98cf17424d27.PNG)

**Comment by hanna-kn** [comment]
That is an old unofficial port, unsupported by the main developers (me). You should report any issues to Cheng Sun and the forked project.

**Comment by hanna-kn** [comment]
Fixed in new port
