### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by scx** [Qalculate/qalculate-gtk#82]
I created the flatpak package for Qalculate.
https://github.com/scx/qalculate-flatpak

I am in the process of submitting it to the Flathub repo.
https://github.com/flathub/flathub/pull/869
https://github.com/scx/flathub/tree/io.github.qalculate.Qalculate

It would be nice if you, as the author, decided to participate in the further development of this flatpak package.

**Comment by hanna-kn** [comment]
Excellent. I am not at all familiar with Flatpaks, but please let me know how I ought to participate and I will do my best.

**Comment by hanna-kn** [comment]
I have now taken control of the flatpak package and Qalculate! is now finally available at Flathub (https://flathub.org/apps/details/io.github.Qalculate).
