### ISSUE TITLE
Limited currency list

### ISSUE THREAD

**Issue by nocibambi** [Qalculate/qalculate-gtk#85]
I am not sure whether it is a bug or I set something somewhere which makes this, but suddenly I see only a limited number of currencies only.

There is no dollar, or font or other currencies I need. I do not remember making any configuration setting or tinkering whatsoever. Any ideas of how can I get back the previous behavior?

I am on Ubuntu 18.04.

![image](https://ibin.co/w800/4ZjUcuV7sSvG.png)

**Comment by hanna-kn** [comment]
Something likely went wrong when updating exchange rates. Have you tried updating the exchange rates manually (from the File menu), and restart the application.

I see that you are using an old version (<= 1.0.0). I highly recommend that you update to a newer version (current version is 2.9.0 and is available as a snap package which can be installed from Ubuntu Software Center or using `sudo snap install qalculate`).

**Comment by nocibambi** [comment]
Yes, an update did help. Somehow I assumed that it updates through `apt`. I removed it and reinstalled it with `snap` as you suggested. Works like a charm.

Thanks a lot!
