### ISSUE TITLE
Doesn't integrate some functions

### ISSUE THREAD

**Issue by nick87720z** [Qalculate/qalculate-gtk#88]
Si(n) and Ci(n) functions return input string as result even with numeric argument.
For these two:
sin((2*x-1)*pi)/((2*x-1)*pi)
sin(x)/x
integrate function directly says "unable to integrate"

However, it is able integrate() sin(x) and sinc(x) into some numeric result.

**Comment by hanna-kn** [comment]
Qalculate! is able to integrate sin(x)/x and sin((2x-1)pi)/(2x*pi), but not sinc(x) (unless x is defined as non-zero) or sin((2*x-1)pi)/((2x-1)*pi). sinc() integral has not been implemented, but definitive integrals can be approximated (using a simple but inefficient algorithm).

Calculation of Si() and Ci() has not been implemented.

**Comment by nick87720z** [comment]
ok, understood

**Comment by hanna-kn** [comment]
Simple sinc() integration and Si(), Ci(), Shi(), and Chi() calculation (need more testing)  has now been implemented in libqalculate (https://github.com/Qalculate/libqalculate/commit/90e54a35fa93d0a0db7be05449d37a076797ceb7).

**Comment by nick87720z** [comment]
I tested sin/cos diff and integration, both with 'x' and 1 arguments.
symbolic conversions are all ok, but for Si/Ci i expected same results as from integrate(). As with '1' argument they give different results from what integrate() gives with '1'.

Also diff gives zeros for sin(1) and cos(1). Not sure that i understand Si/Ci meaning correctly as i first saw it in output from some online solver mind service (i used it to get integral constants for window functions, for use with fftw).

**Comment by hanna-kn** [comment]
All tests return the expected results.

sinc(1) = sin(1)/1 = sin(1) ≈ 0.84

Si(_x_) is defined as the integral (antiderivative) of sin(_x_)/_x_ or sinc(_x_) (equals zero when _x_=0). The definitive integral of sin(_x_)/_x_, for the interval [_a_, _b_], equals Si(_b_) - Si(_a_).

What did you expect from `diff(sin(1))`? sin(1) is a constant function and thus the rate of change (slope/derivative) is zero. The integral of a constant function is the constant times _x_  (`integrate(sin(1)) = sin(1)*x + C ≈ 0.84x + C`).

**Comment by nick87720z** [comment]
Looks like i have to boost up my math before to test math software :).
Did not even notice, that substituting unknowns in source formula before using it in calculus gives rather useless result.
