### ISSUE TITLE
Allow multiple independent instances

### ISSUE THREAD

**Issue by ponderstibbons** [Qalculate/qalculate-gtk#9]
Right now, when I try to open a second qalculate it will just give focus to the first, but having multiple independent instances would be much more useful to me instead of forcing a global one.

**Comment by hanna-kn** [comment]
Use the command line flag --new-instance (-n).
Start independent instances with the command `qalculate-gtk -n`.

**Comment by ponderstibbons** [comment]
Oh, my bad. Should have checked that. Thanks for the quick reply, though!
