### ISSUE TITLE
function definition in qalc

### ISSUE THREAD

**Issue by Crides** [Qalculate/qalculate-gtk#90]
Hi, I've just started using qalc recently. However, I'm unable to find a way to define functions in the text interface, although I'm able to do so in the graphical interface. How can I be able to do that?

**Comment by hanna-kn** [comment]
From the output of the `help` command in qalc (>= 0.9.11):
`function NAME EXPRESSION`

```
> help function

Creates a function with the specified name and expression.
Use '\x', '\y', '\z', '\a', etc. for arguments in the expression.

Example: function func1 5*\x.
```

**Comment by Crides** [comment]
Is this in a new version? How can I check my version (there's no `-v`, `--version`, or `-V` option)? Because that's what I get in mine: 

```
> help function

Function: Function

function(Expression, Arguments)

Arguments
Expression: a text string
Arguments: a vector

> function f1 5*\x

  error: You need at least 2 argument(s) (Expression, Arguments) in function function().
  function("f15*\x") = function("f15*\x")
```

I'm on Ubuntu 18.04 and `qalc` is installed through `apt`.

**Comment by hanna-kn** [comment]
The version in Ubuntu 18.04 (and 18.10) is 0.9.10 (which did not yet provide a version command line switch). The current version is 3.0.0. The latest version is available on Ubuntu as a snap package (which can be installed using `sudo snap install qalculate`).

**Comment by Crides** [comment]
Okay, I see. I don't really use snaps, so I compiled a upstream version, and it works great! Thanks.
