### ISSUE TITLE
Windows x64 installer defaults to x86 Program Files

### ISSUE THREAD

**Issue by Hydroxides** [Qalculate/qalculate-gtk#92]
Similar to [issue 87](https://github.com/Qalculate/qalculate-gtk/issues/87), the current Windows x64 installer defaults to "C:\Program Files (x86)\Qalculate" which installs without error but prevents Qalculate from starting. Removing " (x86)" from the path at time of installation fixes this problem and allows Qalculate to start without fault.

Tested on Windows 7 using [Qalculate 3.1.0](https://github.com/Qalculate/libqalculate/releases/download/v3.1.0/qalculate-3.1.0-x64.msi) (MD5: C52E510C3B9A57DB1C727057E37113DC).

**Comment by hanna-kn** [comment]
Fixed (I did not realize that it was necessary to change ProgramFilesFolder to ProgramFiles64Folder for the 64-bit version).
