### ISSUE TITLE
Please add bookmarking (storing the entered expression permanently) items of the history

### ISSUE THREAD

**Issue by vporton** [Qalculate/qalculate-gtk#94]

**Comment by hanna-kn** [comment]
Is this mainly about keeping items in the history or adding bookmarks for access?
It would be quite simple to add a "protect" option to the history context menu. In addition to protecting the item from deletion, it would also be placed at the top of list upon restart. Would this be enough?
Perhaps you could describe the specific use case?

**Comment by vporton** [comment]
> Is this mainly about keeping items in the history or adding bookmarks for access?

Both.

> It would be quite simple to add a "protect" option to the history context menu. In addition to protecting the item from deletion, it would also be placed at the top of list upon restart. Would this be enough?

No. I want namely text labels for formulas.

> Perhaps you could describe the specific use case?

I am calculating my salary and taxes in different currencies. I want labels like: "The salary", "The taxes", etc.

**Comment by hanna-kn** [comment]
Done (although there probably a lot of bugs left to fix).

![History bookmarks](https://user-images.githubusercontent.com/19703699/57568809-8d344580-73ec-11e9-8208-5c7f9ad54923.png)

> No. I want namely text labels for formulas.

Formulas are normally best stored using functions.
