### ISSUE TITLE
error: possibly undefined macro: AC_PROG_INTLTOOL

### ISSUE THREAD

**Issue by evandrocoan** [Qalculate/qalculate-gtk#97]
When I run configure, I got this:
```
evandro@evandro-pc:/myfiles/Downloads/qalculate-gtk$ ./autogen.sh
configure.ac:27: error: possibly undefined macro: AC_PROG_INTLTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
evandro@evandro-pc:/myfiles/Downloads/qalculate-gtk$ 
Linux evandro-pc 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by evandrocoan** [comment]
I fixed it by running:
```
sudo apt-gen install autogen autoconf libtool sudo libgtk-3-dev
```

1. https://github.com/hishamhm/htop/issues/439
1. https://askubuntu.com/questions/101306/how-do-i-install-gtk-3-0/243636

But now, configure fails:
```
$ PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure
...
checking for QALCULATE... no
configure: error: Package requirements (
	libqalculate >= 3.2.0
	) were not met:

No package 'libqalculate' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables QALCULATE_CFLAGS
and QALCULATE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by hanna-kn** [comment]
`sudo apt-get install qalculate` (for an old version), or
`sudo snap install qalculate` (for the latest version)

If you want to compile the source code you should read the instructions, install the development packages for all listed requirements, and install libqalculate and qalculate-gtk in order.

I am not sure of what actually works if you are using such an ancient Ubuntu version as 13.04.

**Comment by evandrocoan** [comment]
> `sudo apt-get install qalculate` (for an old version), or
> `sudo snap install qalculate` (for the latest version)

This should be on readme.



> ancient Ubuntu version as 13.04.

I use Ubuntu 18

**Comment by hanna-kn** [comment]
> This should be on readme.

The downloads page (https://qalculate.github.io/downloads.html) includes information about installing the snap package. Instructions how to install packages on different distributions is available elsewhere (it is not my responsibility to provide installation instructions for every version of Debian, and numerous derivatives, openSUSE, Arch, Fedora, Gentoo, Slackware, etc.), and I recommend installing a more recent version of Qalculate! than the one available using apt on Ubuntu 18.

**Comment by evandrocoan** [comment]
> it is not my responsibility to provide installation instructions for every version of Debian, and numerous derivatives, openSUSE, Arch, Fedora, Gentoo, Slackware, etc.

You do not have to provide all of them. Just providing one as example and saying, for other distros the process is similar. For example:
> You can install this by your favorite package manager, for example, if your system is Debian based, the command would be:
> ```
> sudo apt-get install qalculate
> ```

Not being so obvious makes you package very hard to find for most people.

Anyways, it is not your problem people cannot use this because you have nothing to win.

**Comment by hanna-kn** [comment]
I just assumed that most Linux users are aware of the standard way of installing software. I've now added additional information.

**Comment by evandrocoan** [comment]
> I just assumed that most Linux users are aware of the standard way of installing software

It is not that they do not know that, but the problem is if you do not give a simple example of using one package manager, most users do not know how to answer these questions:
1. Is this package available by the package manager? Not all nice projects you find out there are available by a the package manager. And as the first thing you need on README.md is just how to build the project, then, I can only assume, I have to build it from the source if I would like to use this. But if you give an example about installing it using a package manager, I can already think, wow I do not have to build this from the source if I would like to use it, because I am also seeing there on README.md instructions to install it from the package manager.
1. What would be the name of the package? `qalculate-gtk`,  `qalculate`,  `qalculate-gui`?

**Comment by tarnalcock** [comment]
> > I just assumed that most Linux users are aware of the standard way of installing software
> 
> It is not that they do not know that, but the problem is if you do not give a simple example of using one package manager, most users do not know how to answer these questions:
> 
> 1. Is this package available by the package manager? Not all nice projects you find out there are available by a the package manager. And as the first thing you see on README.md is just how to build the project, then, I can only assume, I have to build it from the source if I would like to use this. But if you give an example about installing it using a package manager, I can already think, wow I do not have to build this from the source if I would like to use it, because I am also seeing there on README.md instructions to install it from the package manager.
> 2. What would be the name of the package? `qalculate-gtk`,  `qalculate`,  `qalculate-gui`?

`apt-cache search calculate`
