### ISSUE TITLE
qalc.exe - System Error

### ISSUE THREAD

**Issue by smaragdus** [Qalculate/qalculate-gtk#99]
Starting **qalc.exe** results in system error message:

`The program can't start because libpdcurses.dll is missing from your computer. Try reinstalling the program to fix this problem.`

**screen:**
![Qalculate! 3 2 0 - 2019-05-29 - error - 001](https://user-images.githubusercontent.com/9025757/58588136-ac91f600-8267-11e9-978e-4f4b79ebf684.png)

I am using **Qalculate!** version **3.2.0** portable  (**qalculate-3.2.0-i386.zip**) on Windows 8 x64. However downloading **libpdcurses.dll** and putting it in program folder resolves the problem.

Shouldn't **libpdcurses.dll** be includes in the archive?

**Comment by hanna-kn** [comment]
I updated the libraries, when adding the icon to the executable, and did not realize that libpdcurses.dll had become a requirement (unfortunately qalc still does not work well in interactive mode on Windows). This has now been fixed.

**Comment by smaragdus** [comment]
@hanna-kn 
Thanks.
